AliceO2Group/O2DPG

- MC/run/PWGHF/embedding_benchmark.sh
> adapt to option change

- GRID/utils/grid_submit.sh
A production split level can now be provided via
the --prodsplit n argument.
> grid_submit: support for production split

- MC/run/PWGHF/embedding_benchmark.sh
This reverts commit b9bd930accb604df95e24b217cd8d9da20e51ebd.
Doesn't work as expected.
> Revert "load taskwrapper only when not already there"

- MC/run/PWGHF/create_embedding_workflow.py
Demonstrator for a python script that can generate a typical
MC workflow. Produces a json format that can be run by
a dedicated scheduler/runner which takes care of runtime
optimizations.
Demonstrates how embedding can be treated as an option.
> python script as workflow.json generator

- MC/bin/o2_dpg_workflow_runner.py
It turns out that psutil.children() has not enough
priviledges to determine the list of child processes
on some GRID Unixes.
In such cases, we now use a custom solution based on
a bash function.
> pipeline runner: psutil Stability fixes and workarounds

- MC/bin/o2_dpg_workflow_runner.py
- MC/run/PWGHF/create_embedding_workflow.py
This is demonstrating how we can incorporate background caches
into the MC-pipeline.
We can use a sophistication in which we copy background files
in multiple stages, since not all files are needed at the same time.
This allows for hiding the copy latency and we can overlay the copy
of large hit files with signal transport simulation etc.
Moreover, we copy only what is needed by a workflow.
On a bookkeeping level we still need to verify compatibility
of background files with the curent software stack etc.
> Introduce demonstrator for background caches in embedding

- MC/run/PWGHF/create_embedding_workflow.py
* produce TPC digits in chunked mode, saving
lot's of RAM
* feed digits to reco using o2-tpc-chunkeddigit-merger
* split TPC clusterization and tracking in view
of doing clusterization in "sector"-steps in the future
(again to overcome memory problems)
> Restructure TPC digi-reco

- MC/bin/o2dpg_sim_workflow.py
- MC/run/PWGHF/embedding_benchmark.sh
Integrate features (from PWGHF/create_embedding_workflow)
into official script. This concerns notably the option to use
background event from alien caches.
This also reduces code duplication and starts using
the official o2dpg_sim_workflow for PWGHF embeddings.
> Move new features to o2dpg_sim_workflow

- MC/bin/o2dpg_sim_workflow.py
- MC/config/PWGGAJE/hooks/jets_hook.C
- MC/config/PWGGAJE/hooks/prompt_gamma_hook.C
- MC/config/PWGGAJE/trigger/decay_gamma_jets.C
- MC/config/PWGGAJE/trigger/prompt_gamma.C
- MC/config/common/pythia8/utils/mkpy8cfg.py
Also, add argument for particle detector acceptance filter.
> Fix Pb PDG and automatic energy setting for Pb and HI pythia configuration

- MC/bin/o2dpg_sim_workflow.py
So it does not need to be done separately. This should be merged after [PR5860](https://github.com/AliceO2Group/AliceO2/pull/5860) is merged to O2.
> TRD TRAP simulation is added to digitization

- MC/bin/o2dpg_sim_workflow.py
--rate 1 has exit/termination problems.
With a slightly higher rate (1000) this seems to work much better
while still avoiding busy CPU spinning problems in source
devices.
> Slightly higher DPL --rate settings

- MC/bin/o2_dpg_workflow_runner.py
This is fixing a stall problem in the pipeline runner, which was
observed on systems (GRID), where the runner was launched with an
increased nice value (>0).
In this scenario, allocated resources per task were not correctly
"un-accounted' and so the runner stalled at some moment since it couldn't
find free resources.
This commit is also adding some debugging mechanism with webhooks.
Later integration into the standard logging system would be nice.
> Fix stall problem in pipeliner runner in environments with nice>0

- MC/bin/o2_dpg_workflow_runner.py
- MC/run/PWGHF/create_embedding_workflow.py
- MC/run/PWGHF/embedding_benchmark.sh
Several improvements in pipeline runner:
* fix a bug with "skipping task" ... now much faster
* provide option to make core-dump checkpoint on failure
and upload to ALIEN
* offer possibility to re-schedule a failed task when
it matches a certain condition
(for instance random failures that happen very rarely)
> Adjustin IRate; improvements in pipeline runner

- MC/bin/o2dpg_sim_workflow.py
Trying to prevent the segfault/shm-problem in the GRID.
Also this might help to actually have yet better CPU efficiency
since the clusterization can now fill CPU holes.
> Split TPC clusterization into 1-core/1-sector pieces

- MC/bin/o2dpg_sim_workflow.py
MC disabled for now for the TRD tracking
> Add TRD tracking task

- MC/bin/o2dpg_sim_workflow.py
* scale number workers in case only a fraction of workers should be used
used for certain tasks
> Scale number of workers

- MC/bin/README.md
- MC/bin/o2dpg-workflow-tools.py
- MC/bin/o2dpg_sim_workflow.py
- MC/bin/o2dpg_workflow_utils.py
- MC/run/PWGHF/analysis_benchmark.sh
* revise command line usage of o2dpg-workflow-tools.py
* update README and provide usage of o2dpg-workflow-tools.py there
* implement common functionality in o2dpg_workflow_utils.py
currently used in o2dpg_sim_workflow.py and o2dpg-workflow-tools.py
* module import handled via relative paths:
sys.path.append(join(dirname(__file__), '.', 'o2dpg_workflow_utils'))
from o2dpg_workflow_utils import createTask, dump_workflow
> Update workflow handling

- MC/bin/o2dpg_sim_workflow.py
@sawenzel I split the TRD tracklet transformer workflow and the global tracking in https://github.com/AliceO2Group/AliceO2/pull/6585 so the script here needs to be adapted. I tested it locally and for me it works fine (even with the current O2 dev).
> Adapt TRD tracking task

- MC/bin/o2dpg_sim_workflow.py
* some simplification/system to manage global and local
configurable params in >= digi stages
* propagate timeframe HBF info to all reco stages
* now the bunch crossing info should be correct
> Propagate configValues to all stages in a timeframe

- MC/bin/o2dpg_sim_workflow.py
> Put special pp reco settings

- MC/bin/o2dpg_sim_workflow.py
@sawenzel this is to emulate the same pT cuttof in TPC as we effectively have in the async. reco.
> Introduce TPC q/pt cutoff to reduce loopers

- MC/bin/o2dpg_sim_workflow.py
To be seen if for grid jobs it is not better to use the sampling as
we do in data.
Needs: 
https://github.com/AliceO2Group/QualityControl/pull/909
which in turns needs:
https://github.com/AliceO2Group/AliceO2/pull/7321
@shahor02, FYI
> Adding ITSTPC matching, and using "direct" sampling for the script

- MC/bin/o2dpg_sim_workflow.py
jet-jet settings provided in dedicated scripts
> update default pp IR from 400 kHz to 500 kHz, remove jet-jet production settings

- MC/bin/o2dpg_sim_workflow.py
For now passing directly to AOD conversion.
> Option to pass run-number from outside

- MC/bin/o2dpg_sim_workflow.py
For, let's fetch these necessary files manually.
At some point they should be fetched by the tasks from CCDB.
> Download and use [ITS|MFT]dictionary.bin

- MC/bin/o2dpg_sim_workflow.py
> Remove MaxTimeBin config for TPC

- MC/bin/o2dpg_sim_workflow.py
MID-MCH matching is missing on the O2DPG generated workflow. 
This PR includes the MID-MCH matching workflow on `MC/bin/o2dpg_sim_workflow.py` and other changes necessary to produce GlobalMuonTracks in AO2D files.
> Adapt workflow to produce MFT-MCH-MID tracks

- MC/bin/o2dpg_sim_workflow.py
Speeding up startup time of executables by using
the absolute path of O2 executables:
* less system calls during forking and less
search in $PATH
Simplification of AOD creation (taking out
workaround no longer necessary)
> Speed up startup / simplification

- DATA/production/qc-async/its.json
Included parameter to avoid creation of TTree in ITS track task. This follows https://github.com/AliceO2Group/QualityControl/pull/994/files
> Update its.json qc async

- MC/bin/o2dpg_sim_workflow.py
This is asked for the pp production. Setting applied
according to input from @shahor02.
> Apply special ITS-MFT ALPIDE strobe setting for pp processing

- MC/bin/o2dpg_sim_workflow.py
Taken as suggested in https://alice.its.cern.ch/jira/browse/O2-2691
> Adjust pp specific setting for primary vertexer

- DATA/production/qc-sync/emc.json
- DATA/testing/detectors/EMC/qc/emcQCTasks_multinode.json
- DATA/testing/detectors/EMC/qc/emcQCTasks_singlenode.json
- DATA/testing/detectors/EMC/runEMCRawToDigitsRecoPilelineQClocal.sh
- [EMCAL-730] Align hostname to global processing
- [EMCAL-724] Update QCDB relocator in stand-alone configs
> [EMCAL-724, EMCAL-730] QC fixes for global processing

- DATA/production/qc-async/itstpctof.json
- MC/config/QC/json/tofMatchedTracks_ITSTPCTOF_TPCTOF_direct_MC.json
@chiarazampolli with this I uniform the two json by formatting them
> Format TOF json files to highlight discrepancies

- MC/bin/o2dpg_sim_workflow.py
Following request in production ticket
https://alice.its.cern.ch/jira/browse/O2-2679 (date 10.01.2022)
> Tuning pvertexer setting for high-energy pp

- MC/bin/o2dpg_sim_workflow.py
apparently these are not the same for pilot beam
and high energy pp
> more distinguished Alpide settings for pp

- DATA/production/qc-async/its.json
Modification of its.json in qc_async according to latest updates in ITS track task: https://github.com/AliceO2Group/QualityControl/pull/1008/files
In addition, update of parameters for vertex plots.
> Modification of its.json in qc_async

- MC/bin/o2dpg_sim_workflow.py
- MC/run/HEPscore/hep-score.sh
Maintaining the HEPscore script inside O2DPG.
Some accompanying adjustments/fixes in the workflow generation.
> Official HEPscore setup

- MC/analysis_testing/analysis_test.sh
- MC/analysis_testing/o2dpg_analysis_test_workflow.py
* make separate workflow file for analysis testing
* gain in flexibility and independent usage of sim workflow
* usage see o2dpg_analysis_test_workflow.py --help
> Provide script only to tes analyses

- MC/config/common/external/trigger/multiplicity_stableparticles_inFIT.C
- MC/config/examples/ini/trigger_multiplicity_stableparticles_inFIT.ini
- MC/run/common/run_PbPb_trigger_multiplicity_stableparticles_inFIT.sh
- MC/run/examples/trigger_multiplicity_stableparticles_inFIT.sh
Pb--Pb simulations with a trigger on the number of stable particles in the FIT acceptance
> Pb--Pb simulations with a multiplicity FIT trigger

- MC/bin/o2dpg_sim_workflow.py
For the moment via environment variable because
this is likely only for developer studies.
If need be, we can promote to real option later.
> Ability to control AOD truncation

- DATA/production/calib/its-threshold-aggregator.sh
- DATA/production/qc-async/its.json
- MC/config/QC/json/its-clusters-tracks-qc.json
Changes applied:
- modified its jsons for data and MC to reflect changes in ITS QC: https://github.com/AliceO2Group/QualityControl/pull/1025 and https://github.com/AliceO2Group/QualityControl/pull/1007 
- added nthreads to threshold calib workflow following this PR: https://github.com/AliceO2Group/AliceO2/pull/8021
> Update of ITS jsons + added nthreads for ITS THR calibration wf

- DATA/production/qc-sync/its.json
Hi @davidrohr, this PR can be merged now for the QC v1.45.1.
> ITS: update qc json for sync

- DATA/production/calib/its-threshold-aggregator.sh
- DATA/production/calib/its-threshold-processing.sh
This follows: https://github.com/AliceO2Group/AliceO2/pull/8093
> [WIP] ITS threshold scripts modified to work with new workflow scheme

- DATA/production/qc-async/emc.json
- DATA/production/qc-workflow.sh
- MC/bin/o2dpg_qc_finalization_workflow.py
- MC/bin/o2dpg_sim_workflow.py
- MC/config/QC/json/emc-digits-task.json
- EMCAL-755: QC workflow for MC
- EMCAL-756: QC workflow for async reconstruction
> [EMCAL-755, EMCAL-756] Adding EMCAL QC for MC and async reconstruction

- MC/run/PWGDQ/runBeautyToPsi_fwdy_PbPb.sh
Dear experts,
For MC, Non Prompt psi(2S) Forward Rapidity (MuMu) for Pb-Pb collisions at sqrt(5.02 TeV) run script  added.
> [PWG-DQ] Non Prompt psi(2S) run script for Pb-Pb added

- DATA/production/qc-async/its.json
- MC/config/QC/json/its-clusters-tracks-qc.json
@chiarazampolli this follows the already merged PR1038 in QC. https://github.com/AliceO2Group/QualityControl/pull/1038/files
> Updated ITS jsons based on QC PR1038

- DATA/production/configurations/2021/OCT/apass3_zerofield/async_pass.sh
- DATA/production/configurations/2021/OCT/apass3_zerofield/setenv_extra.sh
Ciao @chiarazampolli, 
This is just a clone of standard apass3, needed because we change the tag name for the B=0 runs reco - alien script looks into path from O2DPG, ie DPGRECO=$O2DPG_ROOT/DATA/production/configurations/$ALIEN_JDL_LPMANCHORYEAR/$ALIEN_JDL_LPMPRODUCTIONTAG/$ALIEN_JDL_LPMPASSNAME/async_pass.sh).
We could have bypassed it by using local scripts, but let's do it properly.
Thanks!
Yours,
Catalin.
> async pass3 zero field runs configuration (O2-2797)

- DATA/production/configurations/2021/OCT/apass3_zerofield/setenv_extra.sh
> Removing gain-related settings, see O2-2797

- DATA/production/configurations/2021/OCT/apass4/async_pass.sh
- DATA/production/configurations/2021/OCT/apass4/setenv_extra.sh
@catalinristea
Same scrips as for apass3, nothing changed.
> scripts for apass4

- MC/config/PWGHF/pythia8/decayer/force_hadronic_D.cfg
- MC/config/PWGHF/pythia8/decayer/force_hadronic_charmHadTrigger.cfg
The PDG code of the Lambda(1520) was updated starting from the pythia version 8.3
> Update pdg code of Lambda(1520)

- DATA/production/qc-async/cpv.json
- DATA/production/qc-async/phs.json
- DATA/production/qc-sync/cpv.json
- DATA/production/qc-sync/phs.json
- DATA/production/qc-workflow.sh
Hello! Json files for CPV qc-sync and qc-async reco are added. Also json files for PHS are prepared but this will be included into workflow later.
> added CPV jsons for qc-sync and qc-async workflows

- DATA/production/configurations/2021/OCT/apass3/async_pass.sh
- DATA/production/configurations/2021/OCT/apass3_zerofield/async_pass.sh
- DATA/production/configurations/2021/OCT/apass4/async_pass.sh
> fix trivial typo in a comment

- DATA/production/qc-sync/its.json
Hi @davidrohr, it can be merged now.
> ITS: update ITS qc json

- DATA/production/qc-workflow.sh
As instructed modified the MFT json link to point to the Consul.
> Pointing MFT json to fetch the version in Consul.

- MC/analysis_testing/o2dpg_analysis_test_workflow.py
- MC/config/analysis_testing/json/analysis-tesing.json
* introduce dedicated DPL configuration for analysis testing to not
interfer with the QC JSON used before
* add O2mult table to TPC analysis
> Update analysis testing

- DATA/production/qc-async/trd.json
- DATA/production/qc-sync/trd.json
- DATA/production/qc-workflow.sh
Add trd to syn async and in to qc-workflows.sh to get the qc in global runs amongst other things.
> add trd qc

- MC/bin/o2_dpg_workflow_runner.py
- MC/utils/o2dpg_sim_metrics.py
* added new utility script o2dpg_sim_metrics.py
* add meta such as cpu-limit or mem-limit information to pipeline_metrics
> Add metrics evaluation for o2dpg_sim_workflow

- MC/bin/o2dpg_sim_workflow.py
- MC/bin/o2dpg_sim_workflow_anchored.py
- MC/run/ANCHOR/2021/OCT/pass4/anchorMC.sh
- UTILS/parse-async-WorkflowConfig.py
* providing a production ready script for anchorMC (OCT 2021 pass4)
* dispatch more stuff to ccdb (such as field and bunchfilling) in case
of anchoring
* cleanup
* further configurability adjustments in O2DPG sim workflow creation
* Use of TPC files (GPU_global settings)
> More anchoring work

- MC/bin/o2dpg_qc_finalization_workflow.py
- MC/bin/o2dpg_sim_workflow.py
- MC/config/QC/json/tofMatchedTracks_AllTypes_direct_MC.json
Needs https://github.com/AliceO2Group/QualityControl/pull/1103
> additional TOF QC, using also TRD tracks

- MC/run/ANCHOR/2021/OCT/pass4/anchorMC.sh
Hi Sandro,
Here are some small changes. Please review and merge if these are fine with you.
Thanks!
Yours,
Catalin.
> LPMProductionTag swapping, full logs for grid, local qc

- MC/utils/o2dpg_sim_metrics.py
* Fix InfluxDB file structure
* stop plotting early if no data provided
> Fixes and protections

- DATA/production/configurations/2021/OCT/apass4/setenv_extra.sh
- MC/run/ANCHOR/2021/OCT/pass4/anchorMC.sh
@wiechula @sawenzel 
Needs to be validated by @wiechula
> Update TPC reco settings for data and MC

- DATA/production/calib/phs-led.sh
- DATA/production/calib/phs-pedestal.sh
- DATA/production/qc-workflow.sh
- DATA/production/standalone-calibration.desc
hello! PHS pedestal + standalone calibration added to DATA/standalone-calibration.desc
> PHS QC and standalone calibration: pedestal and LED

- DATA/production/configurations/2021/OCT/apass4/async_pass.sh
@wiechula @catalinristea @noferini
> Remove use of tarball for apass4 for TPC

- MC/bin/o2dpg_sim_workflow_anchored.py
It seems to be more reliable than taking this from RCT/Information.
And we can do it following https://github.com/AliceO2Group/AliceO2/pull/8459
Some accompanying features:
* ability to get CCDB object as JSON for direct treatment in python
> Query the run timerange from GRPECS

- DATA/production/configurations/2021/ctf_recreation/setenv_extra_ctf_recreation_phos.sh
@catalinristea
This explains the error in PHOS, sorry for the issue...
> fix settings for PHOS CTF recreation

- DATA/production/configurations/2021/ctf_recreation/emc-qc.json
> Fix CCDB path for EMC QC

- DATA/production/configurations/2021/OCT/apass4/setenv_extra.sh
Like https://github.com/AliceO2Group/O2DPG/pull/311, but there was a mess in my PR (showing conflicts), so this should be just to clean up.
> Remove DDS session ID for fetcher to work correctly

- MC/bin/o2dpg_sim_workflow.py
needs proper handling in sim workflow to use piping again
> Workaround race condition for trdcalibratedtracklets.root

- MC/bin/o2dpg_sim_workflow.py
* also cleanup:
- no longer download ITS/MFT cluster dictionaries since
they are fetched via CCDB directly in the tasks
> Consistently use matbud in MC workflows

- MC/run/ANCHOR/2021/OCT/pass4/anchorMC.sh
@sawenzel , @benedikt-voelkel , @noferini , @catalinristea, @gconesab
> Enabling analysis QC tasks in anchored MC

- MC/bin/o2dpg_sim_workflow.py
Needs https://github.com/AliceO2Group/AliceO2/pull/8537
> Assign HBFUtils.runNumber from the command line options

- DATA/production/calib/mft-noise-aggregator.sh
This change has to be deployed at P2 together with the O2 version containing this PR: https://github.com/AliceO2Group/AliceO2/pull/8587
> MFT: Sending the noise map to both production-CCDB and DCS-CCDB.

- DATA/production/standalone-calibration.desc
- DATA/testing/detectors/TPC/workflows.desc
@rmunzer , but we should rerun and check live
> Reduce TPC Laser SHMSIZE and fix typo

- DATA/production/configurations/2021/OCT/apass4/async_pass.sh
@benedikt-voelkel , @catalinristea, @noferini 
Needs https://github.com/AliceO2Group/O2DPG/pull/326
@catalinristea: once this is enabled, we need to add AnalysisResults.root in the output files.
> Adding analysis QC in data async reco

- DATA/production/configurations/2021/OCT/apass4/async_pass.sh
> Fix path to AO2D for AnalysisQC

- MC/analysis_testing/o2dpg_analysis_test_workflow.py
* add config really to each executable
* remove duplicated track-selection
> Fixes to analysis

- DATA/production/configurations/2021/OCT/apass4/async_pass.sh
- DATA/production/configurations/2021/OCT/apass4/setenv_extra.sh
- aligned geometry should not be a link but passed a input (till
CCDB access will be finalized)
- add " --run-assessment" for MFt reco
@catalinristea @shahor02 @rpezzi
> Update for apass4

- DATA/production/qc-async/pidft0tof.json
- DATA/production/qc-async/pidtof.json
- MC/bin/o2dpg_qc_finalization_workflow.py
- MC/bin/o2dpg_sim_workflow.py
- MC/config/QC/json/pidft0tof.json
- MC/config/QC/json/pidtof.json
Hi @noferini, could you have a look and let me know if something else is needed for porting PID QC?
> Include TOF-FT0 PID Task

- MC/bin/o2dpg_sim_workflow.py
This is helpful to try to reproduce locally things that happen on the grid
> Avoid complete randomness by default

- MC/bin/o2dpg_sim_workflow.py
Reverts AliceO2Group/O2DPG#351
The seeds don't work and the simulation crashed with 
```bash
PYTHIA Error: variable recognized, but its value not meaningful:
Random:seed = 6025226150559117445
```
> Revert "Avoid complete randomness by default"

- DATA/production/qc-sync/its.json
> Fix local copy of ITS sync QC

- MC/bin/o2dpg_sim_workflow.py
This modification follows the changes introduced by [PR 8516](https://github.com/AliceO2Group/AliceO2/pull/8516) in O2, so it should be merged after that PR is merged.
> follow changes in o2-muon-tracks-matcher-workflow

- DATA/production/common/readAO2Ds.C
- MC/config/PWGDQ/EvtGen/GeneratorEvtGen.C
- MC/config/PWGDQ/external/generator/GeneratorBeautyToJpsi_EvtGen.C
- MC/config/PWGDQ/external/generator/GeneratorBeautyToPsi_EvtGen.C
- MC/config/PWGDQ/external/generator/GeneratorBoxFwd.C
- MC/config/PWGDQ/external/generator/GeneratorBplusToJpsiKaon_EvtGen.C
- MC/config/PWGDQ/external/generator/GeneratorCocktail.C
- MC/config/PWGDQ/external/generator/GeneratorCocktailPromptCharmoniaToElectronEvtGen_pp13TeV.C
- MC/config/PWGDQ/external/generator/GeneratorCocktailPromptCharmoniaToMuonEvtGen_PbPb5TeV.C
- MC/config/PWGDQ/external/generator/GeneratorCocktailPromptCharmoniaToMuonEvtGen_pp13TeV.C
- MC/config/PWGDQ/external/generator/GeneratorParam.C
- MC/config/PWGDQ/external/generator/GeneratorParamPromptJpsiToElectronEvtGen_pp13TeV.C
- MC/config/PWGDQ/trigger/selectDaughterFromHFwithinAcc.C
- MC/config/PWGGAJE/hooks/jets_hook.C
- MC/config/PWGGAJE/hooks/prompt_gamma_hook.C
- MC/config/PWGGAJE/trigger/decay_gamma_jets.C
- MC/config/PWGGAJE/trigger/prompt_gamma.C
- MC/config/PWGHF/external/generator/GeneratorHF.C
- MC/config/PWGHF/pythia8/hooks/pythia8_userhooks_qqbar.C
- MC/config/PWGHF/pythia8_gun/generator_pythia8_gun.C
- MC/config/PWGHF/trigger/trigger_ccbar.C
- MC/config/common/external/trigger/multiplicity_stableparticles_inFIT.C
- MC/config/examples/external/generator/adaptive_pythia8.C
- MC/config/examples/external/generator/user_generator.C
- MC/run/common/detector_acceptance.C
- MC/utils/hepmc_reader.C
- MC/utils/merge_TTrees.C
- MC/utils/pythia8_reader.C
- UTILS/aod-size/counttracks.C
- UTILS/repairAOD.C
In preparation of adding clang-format and whitespace/tab check CI as
implemented for O2 to all C-like scripts
> Apply O2 clang-format

- DATA/common/getCommonArgs.sh
- DATA/common/setenv.sh
- DATA/production/workflow-setup.sh
> Some updates needed for calib workflows

- DATA/production/configurations/2021/OCT/apass4/async_pass.sh
- DATA/production/configurations/2021/OCT/apass4/setenv_extra.sh
@rpezzi , @catalinristea , @noferini
> updates for MFT + logs from AnalysisQC

- DATA/production/configurations/2021/OCT/apass4/setenv_extra.sh
> fix value for MFT

- DATA/common/setenv_calib.sh
Adding TRD @martenole , @davidrohr
> add TRD calib and fixes

- DATA/production/configurations/2021/OCT/apass4/async_pass.sh
- DATA/production/configurations/2021/ctf_recreation/ctf_recreation.sh
> Fixing ctf_recreation script after modification of dpl-workflow etc

- DATA/common/setenv_calib.sh
> fix logic to run calibrations

- MC/analysis_testing/o2dpg_analysis_test_workflow.py
- MC/bin/o2dpg_sim_workflow.py
* fix taking MID reco into account, dedicated handling in PV/SVFinder
and AOD producer
* add another forward analysis
> Fix and add analysis

- DATA/common/setenv_calib.sh
> Fix option to pass the name of the proxy/channel

- MC/utils/o2dpg_sim_metrics.py
* introduce sub-commands for CLI: extract, plot, influx
extract:
* extract metrics per pipeline
plot:
* possible to pass multiple extracted JSON metric files which will
also produce overlay plots for mem usage and CPU efficiency
influx:
* seperately construct a format suitable to be sent to InfluxDB
> Modularise metrics script

- DATA/production/qc-async/itstpc.json
- DATA/production/qc-async/itstpctof.json
- DATA/production/qc-async/pidft0tof.json
- DATA/production/qc-async/pidtof.json
- MC/config/QC/json/ITSTPCmatchedTracks_direct_MC.json
- MC/config/QC/json/pidft0tof.json
- MC/config/QC/json/pidtof.json
- MC/config/QC/json/tofMatchedTracks_AllTypes_direct_MC.json
- MC/config/QC/json/tofMatchedTracks_ITSTPCTOF_TPCTOF.json
- MC/config/QC/json/tofMatchedTracks_ITSTPCTOF_TPCTOF_direct_MC.json
> fix geom file name

- DATA/production/configurations/2021/OCT/apass4/setenv_extra.sh
(upon request by R. Pezzi)
@rpezzi
> Update MFT reco settings for apass4

- MC/bin/o2_dpg_workflow_runner.py
- MC/config/QC/json/tof-trending-hits.json
a) ability to combine DPL devices (via option)
b) setup ROOT environment variables to reduce ROOT startup overhead ("multiple short lived child-processes").
This complements and uses https://github.com/alisw/root/commit/d6ea57cb6226f37e517bba241a546ee576ed236e
> Speed improvements for MC workflow

- DATA/common/setenv_calib.sh
> Adding output proxy name - needed when >1 output proxiess are there

- MC/bin/o2dpg_sim_workflow.py
This is fixing the timestamp to the run number,
in case no external timestamp was passed.
> fetch timestamp based on run number

- MC/bin/o2dpg_sim_workflow.py
* make cmd args and timestamp of type int consistently
* extend and actually make tuple
> Small fixes

- DATA/common/setenv_calib.sh
@wiechula , @davidrohr 
@wiechula : can you check that the condition to enable the calibration is correct? For now it is just 
```
if has_detector_calib TPC; then
```
This PR goes with https://github.com/AliceO2Group/AliceO2/pull/8912
> adding TPC

- DATA/common/setenv_calib.sh
only whitespace change, merging
> FST: Fix indentation of calibration scripts

- MC/analysis_testing/o2dpg_analysis_test_workflow.py
- MC/analysis_testing/post_processing/PWGMMMDnDeta.C
- MC/config/analysis_testing/json/analysis-testing-mc.json
* Add analysis for tracking efficiency
* Introduce possibility of post processing of analysis results
> Update analysis WF

- DATA/production/qc-sync/tof.json
> TOF: Fix MO name in postprocessing

- DATA/common/setenv_calib.sh
@davidrohr 
I did not test it, though.
> from push/pull to pub/sub to allow dropping messages in the aggregator

- MC/bin/o2dpg_sim_workflow.py
Recent improvements through DPL device combination are now made default.
Needs prior merge of https://github.com/AliceO2Group/AliceO2/pull/9025
> Commission workflow improvements through DPL device combination

- RelVal/o2dpg_release_validation.py
* update default value
* add functionality to inspect JSON produced by RelVal script
> Update RelVal wrapper

- MC/config/QC/json/ITSTPCmatchedTracks_direct_MC.json
- MC/config/QC/json/tofMatchedTracks_AllTypes_direct_MC.json
- MC/config/QC/json/tofMatchedTracks_ITSTPCTOF_TPCTOF.json
- MC/config/QC/json/tofMatchedTracks_ITSTPCTOF_TPCTOF_direct_MC.json
The current version was misconfigured, and even if not used, it was making the QC crash.
> Remove checks from json since they are not used.

- RelVal/ReleaseValidation.C
* correctly set unique histogram name
* remove empty bins from summary plot
* apply O2 clang-format
> RelVal update

- DATA/production/qc-sync/mid-digits.json
- DATA/production/qc-sync/mid.json
This should fix the errors in the fullCI, waiting for a bump including https://github.com/AliceO2Group/QualityControl/commit/f154edfc4ad17919a15473addff8a2eef981c9d5
> Change back the MID digits query waiting for the QC to be bumped

- MC/analysis_testing/o2dpg_analysis_test_workflow.py
> Fix EventTrackQA analysis

- DATA/common/setenv_calib.sh
@davidrohr 
As for https://github.com/AliceO2Group/AliceO2/pull/9147, for now, I don't know which specs have Lifetime Sporadic, so this is WIP.
> Split proxies depending on lifetime of specs (O2DPG)

- DATA/production/configurations/2022/MayJunePilotBeam/apass1/async_pass.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass1/getTPCvdrift.C
- DATA/production/configurations/2022/MayJunePilotBeam/apass1/setenv_extra.sh
> updated macro for TPC vdrift + analysis QC optional + typo

- DATA/production/configurations/2022/MayJunePilotBeam/apass1/getTPCvdrift.C
> Restore writing to output file

- DATA/production/qc-async/tof.json
- DATA/production/qc-sync/tof.json
@njacazio @ercolessi 
Updating tof qc json for apass reconstructions
> tuning tof digit qc params

- DATA/production/configurations/2022/MayJunePilotBeam/apass1/async_pass.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass1/parse.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass1/setenv_extra.sh
@catalinristea, @noferini , please check, then I will merge.
> fix parse.sh and add TOF option

- DATA/production/configurations/2022/MayJunePilotBeam/apass1/async_pass.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass1/parse.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass1/selectSettings.sh
@catalinristea , @noferini , this PR:
- fixes the hopefully last issue with the parse script;
- allows to take parse.sh ans selectSetting.sh from local files (especially the selectSettings will need updates as soon as they change filling scheme, till we will use GRP)
- updates the selectSettings for the latest runs.
> Extra fix, and possibility to take parse.sh from local file

- DATA/production/configurations/2021/OCT/apass5/async_pass.sh
- DATA/production/configurations/2021/OCT/apass5/setenv_extra.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass1/selectSettings.sh
> Adding apass5 of Oct 2021 data + new runs from June 2022

- DATA/production/qc-async/its.json
- DATA/production/qc-sync/its.json
- MC/config/QC/json/its-clusters-tracks-qc.json
This follows PR1295 to QC (https://github.com/AliceO2Group/QualityControl/pull/1295) merged today. 
(cc @chiarazampolli )
> Add DPL channel VERTICESROF to ITS track task jsons

- RelVal/o2dpg_release_validation.py
* add conversion to files that can be uploaded to InlfuxDB
* revise description comment at the top of the script
* provide global summary in "tabular" JSON format when comparing 2
simulation directories
* small updates
* possible to inspect global summary from the comparison of 2 sim
directories
* skip non-existent files in hit comparison
(before e.g. ZDC comparison was done although it was deactovated)
* couple of minor fixes
> InfluxDB and other updates

- RelVal/README.md
- RelVal/o2dpg_release_validation.py
* make README more readible and add further information
* get a global summary format also when run only on 2 single files
* update inspection interface
* minor bug fixes
> Update README and small fixes/updates

- DATA/production/configurations/2022/MayJunePilotBeam/apass1/selectSettings.sh
> Settings for more runs

- DATA/common/setenv_calib.sh
> Adding CPV calib

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
- DATA/production/configurations/2022/LHC22f/apass1/getTPCvdrift.C
- DATA/production/configurations/2022/LHC22f/apass1/selectSettings.sh
- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass1/selectSettings.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass1/setenv_extra.sh
@catalinristea @shahor02 @noferini
> Update for PilotBeam + LHC22f (13.6 TeV)

- DATA/production/configurations/2022/LHC22f/apass1/selectSettings.sh
- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
- DATA/production/configurations/2022/LHC22f/apass1_TPCcalib/async_pass.sh
- DATA/production/configurations/2022/LHC22f/apass1_TPCcalib/getTPCvdrift.C
- DATA/production/configurations/2022/LHC22f/apass1_TPCcalib/selectSettings.sh
- DATA/production/configurations/2022/LHC22f/apass1_TPCcalib/setenv_extra.sh
@shahor02 , @catalinristea 
This is needed for the runs from last night:
520259
520265
520271
520282
520283
520288
520290
After that the strobe length was changed again, but for now, no run is GOOD in bookkeeping.
> ITS/MFT strobe adjusted + settings to include TPC calib in async reco

- DATA/production/configurations/2022/LHC22f/apass1/selectSettings.sh
- DATA/production/configurations/2022/LHC22f/apass1_TPCcalib/selectSettings.sh
@rpezzi , @shahor02 , @catalinristea , @JianLIUhep 
396 is now considered as default. In case it won't be anymore, we will need to change.
> Fix strobe length for runs with 396

- DATA/production/qc-workflow.sh
@davidrohr 
This is the PR we discussed to have TOF matching QC first than TOF other QCs
> move TOF match QC at the beginning of global json

- DATA/tools/parse
Must be merged AFTER https://github.com/AliceO2Group/AliceO2/pull/9274
> Updates for topology generation to use DPL DDS asset export instead of manual sed

- DATA/production/configurations/2022/LHC22f/apass1/selectSettings.sh
- DATA/production/configurations/2022/LHC22f/apass1_TPCcalib/selectSettings.sh
Ciao @chiarazampolli and @noferini,
Please review/amend/merge if you find this useful.
Thanks, Catalin.
> Removed ITS/MFT strobe, as now these are read from CCDB

- DATA/production/qc-async/trd.json
- DATA/production/qc-sync/trd.json
- DATA/production/qc-workflow.sh
change default qc for trd in qc-workflow.sh
> TRD fix trd default qc

- DATA/production/qc-sync/mft.json
- DATA/production/qc-sync/mft_track.json
- DATA/production/qc-workflow.sh
A PR to the QC repository is possibly failing due  the sync qc json file not being updated: https://github.com/AliceO2Group/QualityControl/pull/1359
> MFT: Sync QC json update

- DATA/production/calib/tpc-laser.sh
- DATA/production/calib/tpc-pedestal.sh
- DATA/production/calib/tpc-pulser.sh
Include Raw QC and data sending to Online Monitor for calibration runs.
> Tpc raw qc and om for calib

- DATA/common/setenv_calib.sh
@davidrohr @ehellbar @rmunzer @matthias-kleiner
> Adding TPC IDCs specs

- MC/analysis_testing/analysis_test.sh
- MC/analysis_testing/o2dpg_analysis_test_workflow.py
- MC/config/analysis_testing/json/analysis-testing-data.json
- MC/config/analysis_testing/json/analysis-testing-mc.json
@chiarazampolli @strogolo this for me worked on LHC22e data, I also added some improvement to the analysis script
> Align to recent changes and extension

- MC/bin/o2dpg_sim_workflow.py
@sawenzel this is needed following the addition of FIT and Calo's to vertex matching, but I see that the core vertexing / AOD sources were incomplete (ITS-TPC-TRD-TOF was missing added) and are not really following detector composition. I think these sources, when not taken from the anchoring, should be concatenated to the seed by each workflow which produces corresponding output, as it is done in the dpl-workflow.sh.
We can discuss this next week.
> Add FIT,Calos to vertex matching, fix other sources

- MC/bin/o2dpg_sim_workflow.py
- MC/bin/o2dpg_sim_workflow_anchored.py
for AOD, we will still need much more dynamic
source building ....
> some adjustments for anchoring MC

- DATA/production/qc-async/its.json
- DATA/production/qc-sync/its.json
- MC/config/QC/json/its-clusters-tracks-qc.json
> Updated all ITS jsons to match latest changes in QC PR1377

- DATA/production/calib/its-threshold-aggregator.sh
@davidrohr sorry, here a trivial bug fix.
> Fix trivial bug in ITS aggregator script for calib

- DATA/production/qc-sync/mft.json
- DATA/production/qc-sync/mft_track.json
- MC/config/QC/json/qc-mft-cluster.json
- Adding a query for the cluster dictionary in the json files in O2DPG
> MFT: Adding json query for cluster dictionary

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
@catalinristea , @shahor02 , @wiechula , @noferini 
If you agree, this reflects:
- new PV settings
- fetching vdrift from CCDB
The PR includes also a small fix.
> Update setenv_extra for 2022 13.6 TeV data apass1

- MC/bin/o2dpg_sim_config.py
New default for pp collisions : full cluster scan for MFT tracking
> Enabled FullClusterScan for MFT tracking

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
> Changing logic to avoid calling getTPCvdrift.C if not needed

- MC/bin/o2dpg_sim_config.py
- MC/bin/o2dpg_sim_workflow.py
- MC/run/PWGDQ/runBeautyToJpsi_fwdy_pp.sh
- MC/run/PWGDQ/runPromptCharmonia_fwdy_pp.sh
Adding the options `--fwdmatching-4-param` to switch to matching function excluding q/pt parameter, and `--fwdmatching-cut-4-param` to apply selection cuts on position and angular track parameters
> Adding options to change forward matching function

- MC/bin/o2dpg_sim_workflow.py
works mostly, apart from EMC
(needs additional fix https://alice.its.cern.ch/jira/browse/O2-3170)
> Optionally disable MC-label handling in O2DPG

- DATA/production/qc-async/its.json
- DATA/production/qc-sync/its.json
- MC/config/QC/json/its-clusters-tracks-qc.json
Update ITS QC jsons to support https://github.com/AliceO2Group/QualityControl/pull/1444
> update ITS cluster QC jsons

- RelVal/ExtractAndFlatten.C
- RelVal/README.md
- RelVal/ReleaseValidation.C
- RelVal/o2dpg_release_validation.py
* make summary grid (aka SummaryTests.png) in python * Done based on Summary.json so can be re-done on demand using the "inspect" sub-command * Possible to apply filters based on severity flag and object name matching * Add threshold and value to summary grid cells * sort objects in summary grid by name
* don't wait until the end before making summary plots but make them as soon as possible for each compared batch
* possible to filter on directories already during domparison step. Only objects in directories matching will be extracted
* possible to compare data and MC QC files if names of QC monitor collections are the same --> possible to specify the first comparison batch of all MC QC files and only pass one data QC file
* moved comparison of file sizes in two corresponding directories …
> RelVal Updates

- DATA/production/qc-sync/its.json
@JianLIUhep 
Without this tests on staging are failing
> Fix ITS QC json

- DATA/production/configurations/2022/repackCTFs/repackCTFs.sh
> Script to repack CTFs [O2-3167]

- DATA/production/qc-sync/qc-global-epn.json
@martenole : could you have a look at this, info is in the mail I am currently writing :)
> Sync workflow with QC: write QC log message to log file

- DATA/production/configurations/2022/LHC22f/apass1/selectSettings.sh
@catalinristea , @noferini , see in Bookkeeping first run of 22n
> B field for 22n, needed for QC

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
@rpezzi , @catalinristea, following mail thread .
@rpezzi : for `MFTTracking.forceZeroField=false`, it is not clear to me if this should already be set to `false` as in this PR, or if it needs new MFT alignment in order to be allowed to use it.
> Update MFT reco settings

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
@chiarazampolli : this allows to set the SHMSIZE to be used from extern. We need this in one or the other form. If you'd prefer to do it differently, also fine with me, then please open a PR.
> Don't override SHM sizes if set externally, + fix some whitespace

- MC/bin/o2dpg_sim_workflow.py
Check event count from existing background+signal kinematics to adjust numbers.
> Small adjustment to creation of collisioncontext

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
> Randomizing when we store output, and possibility to run with GPUs

- MC/run/ANCHOR/2021/OCT/pass4/anchorMC.sh
Du to current hangs of QC, independent of SW version
> Disable QC

- RelVal/ReleaseValidation.C
- RelVal/o2dpg_release_validation.py
* We are now using ROOT's TH1::Chi2Test, we don't have to re-invent the
wheel.
* Make test definition in Python script more dynamic and therefore
easier (adds e.g. cmd flags automatically instead of hard-coded)
>  Go to TH1::Chi2Test, small updates

- MC/config/QC/json/emc-cell-task.json
- MC/config/QC/json/its-clusters-tracks-qc.json
- MC/config/QC/json/qc-mft-async.json
- MC/config/QC/json/qc-mft-cluster.json
- MC/config/QC/json/tpc-qc-standard-direct.json
- MC/config/QC/json/tpc-qc-tracking-direct.json
Consul instance not available anymore, avoid communication attempt which leads to hanging QC tasks.
> Remove consul URL

- DATA/production/qc-sync/qc-global-epn.json
This reverts commit 74fa85b90ba41c83e6374ed728a7fe79c7e29844.
> Reenable logging for QC log files

- DATA/production/qc-sync/qc-global-epn.json
@davidrohr  
Test failed 2b6zVyP7Fr1 :(
> Fix typo for QC log file writing

- DATA/common/setenv_calib.sh
@davidrohr , @matthias-kleiner , @rmunzer
> Adding TPC SAC

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
Hello @catalinristea , 
This would be useful e.g. for [O2-3268](https://alice.its.cern.ch/jira/browse/O2-3268). What do you think?
> Possibility to add more output from JDL, or define what to keep from JDL

- DATA/production/configurations/2022/extractCalib/async_pass.sh
- DATA/production/configurations/2022/extractCalib/setenv_extra.sh
@catalinristea , @shahor02 , @noferini
> [O2-3268] Scripts for special reco for MeanVertex calib

- DATA/common/setenv_calib.sh
> Fix semicolon, which breaks topology generation

- MC/run/ANCHOR/2021/OCT/pass4/anchorMC.sh
- MC/run/ANCHOR/2022/JUN/pass1/anchorMC.sh
Will be implemented on in benchmark scripts used for alibi nightlies
> Remove alibi specifics

- DATA/production/qc-async/cpv.json
Hello! This update is to increase interval of fetching objects from CCDB and swithch fetching off (to be implemented yet in QualityControl).
> CPV: update async QC configuration

- DATA/common/setenv_calib.sh
Goes with https://github.com/AliceO2Group/AliceO2/pull/10226
@matthias-kleiner, @wiechula , @davidrohr , @rmunzer , @martenole
> move TPC time gain to barrel sporadic wf

- MC/bin/o2dpg_sim_workflow.py
New option to set the --condition-not-after T time to use a version of CCDB which was valid at time T.
See
https://alice.its.cern.ch/jira/browse/O2-3317
This commit applies to all CCDB queries using DPL fetcher. We still need to constrain queries coming through BasicCCDBManager.
> TimeMachine feature in O2DPG MC workflows

- DATA/common/setenv_calib.sh
Add "\0" subspec for the SAC specs in the input proxy
> Change SAC SPECS

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
> PbPb fix for primVtx and adjust TFDELAYSECONDS

- DATA/production/configurations/2022/LHC22f/apass1/selectSettings.sh
@catalinristea , @noferini : as always this might be needed for QC, if tasks use the files from local directories.
The selection in bookkeeping to get the run number was just "first good physics run".
> Updating settings for LHC22o,p,q,r,s,t

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
@chiarazampolli : Could you check if these changes are OK?
And we might want to apply them to all async scripts.
That said, it is kind of dangerous that we have so much copy&paste.
> Fixes / more flexibility for async reco script

- DATA/production/qc-async/its.json
- MC/config/QC/json/its-clusters-tracks-qc.json
> ITS track and cluster sampling fraction from 30 to 100%

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass1/async_pass.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass2/async_pass.sh
@shahor02 , @catalinristea : please check in detail that I did not forget anything. Thanks!
> Make the script useable for PbPb

- DATA/production/qc-async/tof.json
- MC/config/QC/json/tofdigits.json
@ercolessi @njacazio 
Just a tuning of tof digits QC (not urgent)
> tuning params in tof digits qc

- DATA/production/qc-async/emc.json
Standard settings used for internal clusterizer
> [EMCAL-756] Enable cluster QC in async reconstruction

- DATA/common/setenv_calib.sh
- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
> Possibility to add TRD calib and fixes

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
> Adding QC option for TRD reco when we run reco for TRD calib

- DATA/common/setenv_calib.sh
This accompanies changes in https://github.com/AliceO2Group/AliceO2/pull/10411
> Additional settings for TPC SCD calib

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
> Fix calib case: we need also calib and aggregator wf

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
> Possibility to define which detectors to process from JDL

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
@catalinristea , @shahor02 , following https://alice.its.cern.ch/jira/browse/O2-3446?focusedCommentId=294442&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-294442
> Adding ITSTPC extra bias plus other changes for PbPb

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
Ciao @chiarazampolli, all
Here are few fixes for the production setup.
Please review and merge if you find these appropriate.
Thanks!
Yours, Catalin.
> 22f/pass1:fixes related to recent commits for pp and trd setup

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
@catalinristea : if you could test, it would be great!
> Chopping AOD files according to defined size (default = 8 GB)

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
Need a tag with https://github.com/AliceO2Group/AliceO2/pull/10438
@chiarazampolli with this the pbpb apass4 can restart.
> Use TPC cluster time-bin shifts instead of ITS-TPC time shifts

- DATA/production/configurations/asyncCalib/createCorrectionMap.sh
- DATA/production/configurations/asyncCalib/createJobList.sh
> Adding TPC calib scripts to extract distortion maps [J. Wiechula]

- MC/utils/o2dpg_sim_metrics.py
* execute every command directly based on pipeline_metric.json files
* add plot for metrics averages vs. pipeline_metric file this is particularly useful if one wants to check averages, min and max values of a vcertain metric over time
* tidy up sub-commands of the python script
> Revise o2sim metrics evaluation script

- MC/config/analysis_testing/json/analysis-testing-mc.json
Previously, for MC always the Data process was run. No switched to MC process for simulation
> Fix process switch for Efficiency analysis

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
@chiarazampolli indeed, in the comment on your PR there was 1 extra orbit, thanks for noticing
> ZDC Orbit shifts for LHC22q runs

- RelVal/o2dpg_release_validation.py
- option to copy matching overlay plots in `inspect` command
- bug fix for filtering by flags in `make_single_summary` (should be based on the results applying the new thresholds, not the old ones)
- bug fix for using minimum instead of maximum when combining thresholds for Kolmogorov test
- bug fix for dividing by threshold margin instead of multiplying for Kolmogorov test (this could also be left as it was, such that the user has to provide a number <1 as threshold margin that is then multiplied. But then we have to change at least the default, that is currently 1.5, also to something <1)
> copy overlay plots and bug fixes

- DATA/production/common/getIRandDuration.C
- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
> Getting duration with IR

- DATA/production/qc-async/its.json
- DATA/production/qc-async/mft.json
- DATA/production/qc-async/mid.json
- DATA/production/qc-async/tof.json
@noferini , @bulukutlu , @rpezzi : I will merge before tonight, let me know in case you don't agree.
> Sampling fraction set to 1 for TOF, and MFT and remove sempling when it is 100%

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
Improves overhead reported on https://github.com/AliceO2Group/O2DPG/pull/794
A better solution will be deployed in O2 the next weeks.
> Reduce CPU cost of MFT track-finder

- DATA/production/common/readAO2Ds.C
- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
> Improving content of AODs merging DFs

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
> Changing number of OMP threads for CPU (5 gives issues)

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
> Adding lines removed by accident during update

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
> Disable metrics if we don't want it

- MC/bin/o2dpg_sim_workflow.py
Depending on 
https://github.com/AliceO2Group/AliceO2/pull/10431
> parsing pass name for digitization

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
> Option to use unoptimized multiplicities

- MC/bin/o2dpg_sim_workflow.py
* this brings QED background treatment for PbPb MC
* also brings a more consistent use of bunch filling (setup by grp-tool and queried from local CCDB thereafter)
> introduce QED background treatment

- MC/config/PWGDQ/EvtGen/GeneratorEvtGen.C
- MC/config/PWGLF/pythia8/generator_pythia8_longlived.C
- MC/config/PWGLF/pythia8/generator_pythia8_longlived_multiple.C
- MC/config/examples/external/generator/user_generator.C
* use new interfaces to ensure proper
* encoding of the HepMC and native status code
* set tracking falg correctly
> Adjusting custom generators

- MC/run/PWGDQ/runPromptCharmonia_fwdy_pp.sh
- test/PWGDQ/checkKine.C
- test/README.md
- test/run_tests.sh
- test/test-o2dpg_wf_basic.sh
- test/test-pwgdq_generator.sh
* add a first test (example) for custom PWGDQ generator
* can be used to base an additional CIs for instance
> Proposal for O2DPG tests

- test/README.md
- test/config.sh
- test/run_tests.sh
* possible to disable certain tests by default, e.g. when run on a certain platform
* update README.md
* small bug fixes
> Refinements

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
@noferini , @shahor02 , @catalinristea
> Possibility to run meanVertex calib in async reco

- MC/config/PWGLF/pythia8/generator_pythia8_longlived.C
- MC/config/PWGLF/pythia8/generator_pythia8_longlived_multiple.C
- MC/run/PWGLF/run_DeTrHeInjected.sh
Add possibility to inject one PDG per event
> Extend LF particle injector

- DATA/production/qc-postproc-async/emc.json
- DATA/production/qc-postproc-async/example.json
- MC/config/QC/json/tof-trending-hits.json
@mfasDa @njacazio Are you fine with applying the proposed post-processing task naming convention to your tasks?
> [QC-810] Rename QC postprocessing tasks

- DATA/production/qc-workflow.sh
broken + tested locally, merging
> qc-workflow: bugfix: don't add MCH QC tasks if MCH QC not requested

- DATA/production/qc-async/its.json
Small fix in .json to be up to date with the online QC
> Fixed json for ITS Cluster Task

- DATA/production/qc-async/mft.json
- MC/config/QC/json/qc-mft-async.json
- MC/config/QC/json/qc-mft-cluster.json
- MC/config/QC/json/qc-mft-digit-0.json
- MC/config/QC/json/qc-mft-digit-1.json
- MC/config/QC/json/qc-mft-digit-2.json
- MC/config/QC/json/qc-mft-digit-3.json
- MC/config/QC/json/qc-mft-digit-4.json
Adding the MFT cluster task to asnyc QC.
Deleting spaces at the end of some json files.
> MFT: Add cluster task to asnyc QC.

- MC/analysis_testing/o2dpg_analysis_test_workflow.py
@benedikt-voelkel what do you think? Tagging also @mfaggin @noferini @chiarazampolli
> Update analysis QC to run with compatibility mode

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
Hello @catalinristea , 
You can try the high IR with this. If it works, we can merge.
@noferini , @davidrohr , FYI.
> TIMEFRAME_RATE_LIMIT depends on IR

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
> Fix for ZDC_BC_SHIFT and extra setting for MeanVtx calib (no sec vtx)

- DATA/common/setenv.sh
avoid overriding MYDIR in setenv.sh
> source gen_topo_helper_functions.sh from O2DPG_ROOT directly

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
uses new configurable added in https://github.com/AliceO2Group/AliceO2/pull/10753
> in ALIGNLEVEL=1 mode apply extra error to TPC track

- test/run_tests.sh
* incorporate printing of relevant lines of further log files in case of failure. Those might be produced by launched sub-tasks of the test such as those produced by the simulation or the o2_dpg_workflow_runner.py
> Extend log file printing for tests when failing

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
- DATA/production/configurations/2022/LHC22f/apass1_TPCcalib/setenv_extra.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass1/setenv_extra.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass2/setenv_extra.sh
The default value is ok with the new alignment. Beside, I am going to remove this option to add 2 new ones for setting the resolution in x and y directions separately.
> use default MCH cluster resolution

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
- DATA/production/configurations/2022/LHC22f/apass1_TPCcalib/setenv_extra.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass1/setenv_extra.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass2/setenv_extra.sh
This little change slightly improve the resolution and efficiency of the MCH clustering. I open the PR in case it is still in time for the apass3. Otherwise, the current tuning is already good enough so this fine tuning can be made latter on (for 2023).
> slight improvement of MCH clustering parameters

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
The TPC track (inner) params will be corrected at gpu-reco level and the cov.matrix will be expanded. The same will be done in the TPC refits performed in the global matching devices. The trackTuneParams were tuned on the B- LHC22m, and extended to othe B- periods. For B+ periods the unbiasing signs were simply inverted (w/o testing).
> retune TPC cov.matrix expansion, unbias TPC params on source level

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
@catalinristea 
@dstocco , I am now excluding MID from the two runs giving issues - anyway even with code fixes, they are BAD for MID. @matthias-kleiner , I am adding the possibility to disable the 3D currents, just in case.
> Protection for noisy MID runs and possibility to disable 3D currents

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
This is an insignificant change.
> set TPC unbiasing in Z to 0 (not measured)

- DATA/production/gen_topo_helper_functions.sh
- DATA/production/setenv_calib.sh
> Add missing symlinks

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
@noferini , as you confirmed we can do.
> Removing storing TOF output

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
> Adding muontracks output

- DATA/production/qc-async/fv0.json
@catalinristea , @knopers8 , @jotwinow , see https://alice.its.cern.ch/jira/browse/O2-3540?focusedCommentId=296961&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-296961
Till https://alice.its.cern.ch/jira/browse/QC-940 is fixed.
> Disabling check, since it makes the merging crash

- DATA/tools/epn/gen_topo_logged.sh
- DATA/tools/epn/gen_topo_o2dpg.sh
> GenTopo wrappers: improve logging

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
Ciao @chiarazampolli, @davidrohr 
Here is the commit
following the discussion from 
https://alice.its.cern.ch/jira/browse/O2-3522?focusedCommentId=297165&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-297165
Thanks!
Yours, Catalin.
> Increased SHM size for GPUs

- test/run_generator_tests.sh
* if trigger is present in INI file for a given generator, use it
* probably, an external generator deriving from GeneratorPythia8 could be run with -g external -t pythia8. We might account for this scenario in the future
> Incorporate trigger

- DATA/production/configurations/asyncCalib/defineTimeBinsForCurrents.sh
- DATA/production/configurations/asyncCalib/mergeCurrents.sh
- DATA/production/configurations/asyncCalib/prepareBins.C
> Scripts and macro to merge TPC currents

- MC/bin/o2dpg_sim_workflow.py
avoids https://alice.its.cern.ch/jira/browse/O2-3587 (the real inconsistency needs to be fixed in O2)
> also QED simulation must depend on GRPs

- MC/config/PWGDQ/trigger/selectDaughterFromHFwithinAcc.C
- MC/config/PWGEM/external/generator/GeneratorBeautyToEle_EvtGen.C
- MC/config/PWGEM/ini/GeneratorHF_bbbarToDDbarToDielectrons.ini
- MC/config/PWGEM/ini/tests/GeneratorHF_bbbarToDDbarToDielectrons.C
- MC/config/PWGEM/ini/tests/GeneratorHF_bbbarToDielectrons.C
- MC/config/PWGEM/ini/tests/GeneratorHF_ccbarToDielectrons.C
- MC/run/PWGEM/runHFToDielectrons_pp.sh
Further script and fix for the heavy-flavour enhanced dielectron MC production.
> Heavy-flavour enhanced dielectron MCs

- DATA/production/configurations/asyncCalib/defineTimeBinsForCurrents.sh
> typo in cp command

- DATA/production/configurations/asyncCalib/defineTimeBinsForCurrents.sh
- DATA/production/configurations/asyncCalib/prepareBins.C
@catalinristea , just in case we need to change the macro. What do you think?
> Possibility to take the prepareBins from local files and fix includes

- MC/bin/o2dpg_sim_workflow.py
https://alice.its.cern.ch/jira/browse/O2-3619
> include CPV and PHS into AOD when active

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
For processing also ITS-TPC tracks standalone which were matched to the outer detectors
> TPC interpolation re-using seeding tracks

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
@davidrohr , @catalinristea , @noferini : This is to be able to run the WF splitting it in 3 parts. It needs https://github.com/AliceO2Group/AliceO2/pull/10928 still, then we could try it on the grid.
> adapting to run split wf

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
@davidrohr , @catalinristea : here a small fix for the splitWF (not needed for testing) + the exit codes in case anything fails. 
Let me know in case you spot any issue.
> Fix split wf + exit codes

- DATA/production/calib/its-noise-aggregator.sh
- DATA/production/calib/its-threshold-aggregator.sh
- DATA/production/calib/its-threshold-processing.sh
- DATA/production/standalone-calibration.desc
Added/modified:
- Noise calibration workflow with accumulators/normalizator + ccdb object for DCS (cc @shahor02 )
- Pulse length scan workflow 
- Threshold scan short without EoS
- VCASN tuning with back-bias
> Update ITS calib workflow

- MC/analysis_testing/o2dpg_analysis_test_config.py
* --status print current status ("ENABLED" or "DISABLED")
* --applicable-to print "mc" or "data"
> More on checks of test analyses

- DATA/production/configurations/2021/OCT/apass3/async_pass.sh
- DATA/production/configurations/2021/OCT/apass3_zerofield/async_pass.sh
- DATA/production/configurations/2021/OCT/apass4/async_pass.sh
- DATA/production/configurations/2021/OCT/apass5/async_pass.sh
- DATA/production/configurations/2021/ctf_recreation/ctf_recreation.sh
- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
- DATA/production/configurations/2022/LHC22f/apass1_TPCcalib/async_pass.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass1/async_pass.sh
- DATA/production/configurations/2022/MayJunePilotBeam/apass2/async_pass.sh
- DATA/production/configurations/2022/extractCalib/async_pass.sh
@davidrohr , as discussed.
Related to https://alice.its.cern.ch/jira/browse/O2-3611
> No need to rm shm files, run-workflow-on-inputlist.sh already does it

- DATA/production/configurations/asyncCalib/mergeCurrents.sh
> workaround: wf won't start on the grid otherwise

- MC/analysis_testing/o2dpg_analysis_test_workflow.py
- test/run_analysisqc_tests.sh
* tests whether the AnalysisQC workflow can be created. would fail if
* python script is corrupted
* any config JSONs are broken
> Add test for AnalysisQC workflow construction

- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
@davidrohr , i tested this with non split mode of the wf. Also, note that I had only 1 aod file produced in my test, so the for loop could not be tested. 
If you think it is ok, you can also merge this PR - it is anyway not tested in the CI.
As a side remark: locally, compiling the macro to get the IR and duration takes ~10 seconds.
> Adding timing to async reco

- MC/run/PWGGAJE/run_decaygammajets.sh
- MC/run/PWGGAJE/run_dirgamma.sh
- MC/run/PWGGAJE/run_dirgamma_embedding.sh
- MC/run/PWGGAJE/run_dirgamma_hook.sh
- MC/run/PWGGAJE/run_dirgamma_hook_embedding.sh
- MC/run/PWGGAJE/run_jets.sh
- MC/run/PWGGAJE/run_jets_embedding.sh
- MC/run/PWGGAJE/run_jets_hook.sh
- MC/run/PWGHF/embedding_benchmark.sh
- MC/run/PWGUD/runPythiaAndDiffEvents.sh
- MC/run/examples/O2DPG_pp_minbias.sh
* if runner is the last thing called, leave it at that
* if more complex, make sure to emit reasonable ode
* remove exit 0 everywhere, impossible to know by the caller
> Run scripts must return/exit with reasonable code

- MC/analysis_testing/o2dpg_analysis_test_config.py
- MC/config/analysis_testing/json/analyses_config.json
./o2dpg_analysis_test_config.py validate-output
* check if expected outputs are there for given analyses --> by default check all enabled analyses
* for more options see --help
> Validate analysis output

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
> Do not add extra errors in 22q if requested to not do so

- DATA/production/qc-async/mch-errors.json
Until https://github.com/AliceO2Group/AliceO2/pull/10995 is merged (and used in production(s)).
> MCH: disable (processing) error QC

- MC/bin/o2dpg_sim_workflow.py
* the whole MC workflow will now (by default) use the GLO/Calib/MeanVertex object from CCDB
* For expert mode / debugging, it is still possible to use the `-confKey "Diamond.width[2]=..."` options to set vertex properties. In this case, a local MeanVertex object will be created in the CCDB cache (instead of being fetched from the server) so that all sub-sequent tasks pick this up automatically.
> Consistently use MeanVertex from CCDB

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
> Always append options

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
@shahor02 : following your comment in the discussion about MC anchoring to data:
```
tuned time offsets, i.e. TriggerOffsetsParam.customOffset... and GPU_rec_tpc.clustersShiftTimebins.. settings used in  the setenv_extra.sh are not needed.
TPC ad hoc corrections (debiasing) is not needed, i.e. trackTuneParams.useTPCInnerCorr=true;trackTuneParams.tpcParInner[....] should be omitted, but the cov.matrix modifications
trackTuneParams.sourceLevelTPC=true;trackTuneParams.tpcCovInnerType=1;trackTuneParams.tpcCovInner[..] should be preserved for pp. In pbpb apasses we did not used them so they are not needed.
```
For PbPb, I did nothing so far because we will anchor to a new pass which we are preparing. This period is anyway not in the `if's` for the debiasing + extra TPC cov matrix, for now, so …
> Disabling a few settings not needed for MC

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
@shahor02 , I added the option `--correct-trd-trigger-offset` for 22f, but also the Pilot Beam. 
@lietava, can you confirm that it is needed also for the Pilot beam (22c, d, e)? 
Since we need this urgently for 22f, I would merge this PR soon, if no feedback for 22c, d, e comes and it is wrong, we can fix it later.
@davidrohr , I fixed the PR where I was appending new options too.
> Fix extra args and config + TRD CTP offset for 22c, e, d, f

- DATA/production/qc-async/its.json
- DATA/production/qc-async/itstpc.json
- DATA/production/qc-async/itstpctof.json
- DATA/production/qc-async/itstpctofwtrd.json
- DATA/production/qc-async/mch-tracks.json
- DATA/production/qc-async/mft.json
- DATA/production/qc-async/pidft0tof.json
- DATA/production/qc-async/pidft0tofwtrd.json
- DATA/production/qc-async/pidtof.json
- DATA/production/qc-async/tof.json
- DATA/production/qc-sync/glo-itstpc-mtch-qcmn-epn.json
- DATA/production/qc-sync/its.json
- DATA/production/qc-sync/itstpctof.json
- DATA/production/qc-sync/itstpctrdtof.json
- DATA/production/qc-sync/mft-full-no-tracks.json
- DATA/production/qc-sync/mft-full.json
- DATA/production/qc-sync/tof.json
- MC/config/QC/json/ITSTPCmatchedTracks_direct_MC.json
- MC/config/QC/json/its-clusters-tracks-qc.json
- MC/config/QC/json/mft-clusters.json
- MC/config/QC/json/pidft0tof.json
- MC/config/QC/json/pidft0tofNoTRD.json
- MC/config/QC/json/pidtof.json
- MC/config/QC/json/pidtofNoTRD.json
- MC/config/QC/json/tofMatchedTracks_AllTypes_direct_MC.json
- MC/config/QC/json/tofMatchedTracks_ITSTPCTOF_TPCTOF_direct_MC.json
- MC/config/QC/json/tofdigits.json
@shahor02 , @davidrohr , @knopers8
> askOnceAllButField changed to true in the GeomHelper

- DATA/production/calib/hmp-pedestals-processing.sh
HMPID - tested version for the Calibration
> Fix the CCDB hostname @ P2

- MC/config/PWGHF/external/generator/generator_pythia8_gaptriggered_hf.C
@fgrosa This should fix the issues spotted for the new run of the HF-injected MC.
> Set seed for external gaptriggered generator

- DATA/production/configurations/asyncReco/setenv_extra.sh
@shahor02 
Needs https://github.com/AliceO2Group/AliceO2/pull/11107
> Tracking parameters depend on IR and B field for 2023

- DATA/production/workflow-multiplicities.sh
`GEN_TOPO_AUTOSCALE_PROCESSES` is not set by default for our FST using tmux script
> Forgot unbound variable

- MC/bin/o2dpg_sim_workflow_anchored.py
@sawenzel .
We should take this number from CCDB, since in 2023 it is even different (32).
@catalinristea , @noferini , FYI.
> Orbits in a TF are 128, instead of 256

- DATA/production/configurations/asyncReco/setenv_extra.sh
@shahor02 , @catalinristea , @davidrohr , @noferini 
This allows to read the CTF files remotely. 
@catalinristea : I am also fixing the issue with passing a local file for QC.
> Possibility to use remote reading + fix for external QC file

- DATA/production/configurations/asyncReco/async_pass.sh
> fix for extracting statistics

- DATA/production/configurations/asyncReco/async_pass.sh
@davidrohr , can you check?
Pinging also @catalinristea
> Settings to run with full NUMA domain

- MC/bin/o2dpg_sim_workflow_anchored.py
@sawenzel 
This is a trivial fix I didn't notice before.
I realized it after finding a misbehavior in the output of simulation (EOR used instead of SOR).
This should fix. All the rest looks fine.
I think there is no need to wait for checks
> bug fix for anchoring

- DATA/common/getCommonArgs.sh
- DATA/production/common/setVarsFromALIEN_PROC_ID.sh
- DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
- DATA/production/configurations/CTFSkimming/ctf-skim-workflow.sh
- DATA/production/configurations/asyncReco/async_pass.sh
@shahor02 , @davidrohr , should it not be like this? Otherwise the change that uses O2JOBID will be ineffective, or not?
> Setting O2JOBID using ALIEN_PROC_ID

- MC/bin/o2dpg_sim_workflow_anchored.py
Applying FT0 efficiency to IR calculation.
Tested on GRID for LHC22f (5 runs in total) but run 520259 which has a corrupted ccdb entry for scalars
> correct IR for FT0 eff

- MC/config/PWGEM/external/generator/GeneratorCocktailLF.C
- MC/config/PWGEM/ini/GeneratorLFCocktailPbPb.ini
- MC/config/PWGEM/ini/GeneratorLFCocktailpp.ini
- MC/config/PWGEM/ini/tests/GeneratorLFCocktailPbPb.C
- MC/config/PWGEM/ini/tests/GeneratorLFCocktailpp.C
> LF cocktail for dielectrons

- DATA/tools/parse
> Fix GEN_TOPO_ENV_AT_RUNTIME handling

- RelVal/o2dpg_release_validation.py
give the possibility to combine the 'tuned' thresholds with the fixed thresholds, using max/min (i.e. always the least strict one)
> option to combine fixed and tuned thresholds

- MC/bin/o2dpg_sim_workflow.py
This is preloading trivial space charge corrections into the CCDB cache so that MC workflows effectively do not account for this effect.
This is needed in order to have consistency between digitization and reconstruction. (Reconstruction was fetching the corrections but digitization does not produce the effect yet).
As soon as TPC digitization is able to account for the effect, this commit should be reverted.
> Preload trivial TPC space-charge corrections

- MC/config/PWGEM/external/generator/GeneratorHFToEleFull_EvtGen.C
- MC/config/PWGEM/ini/GeneratorHFFull_bbbarToDDbarToDielectrons.ini
- MC/config/PWGEM/ini/GeneratorHFFull_bbbarToDielectrons.ini
- MC/config/PWGEM/ini/GeneratorHFFull_ccbarToDielectrons.ini
- MC/config/PWGEM/ini/tests/GeneratorHFFull_bbbarToDDbarToDielectrons.C
- MC/config/PWGEM/ini/tests/GeneratorHFFull_bbbarToDielectrons.C
- MC/config/PWGEM/ini/tests/GeneratorHFFull_ccbarToDielectrons.C
- MC/run/PWGEM/runHFFullToDielectrons_pp.sh
Trigger version of enhanced heavy-flavour dielectron MC (still without gap)
> Trigger version of enhanced heavy-flavour dielectron MC (no gap)

- GRID/utils/grid_submit.sh
* allow to specify JDL Output tag from command line or as #JDL_OUTPUT preamble in the script to be executed on the GRID
* improved waiting for jobs
* copy back result files from GRID to local computer when jobs are done
Check out the following example:
A simple hello world script "foo.sh" (mimicking a compute task):
```
#JDL_OUTPUT="out.txt@disk=1"
echo "hello world" > out.txt
hostname >> out.txt
```
Run 4 copies of this script on the AliEn GRID infrastructure , wait for the jobs to finish and copy back the resulting files:
```
$O2DPG_ROOT/GRID/utils/grid_submit.sh --script foo.sh --prodsplit 4 --wait --fetch-output
```
> grid_submit: Several improvements and new features

- MC/config/PWGLF/pythia8/generator_pythia8_longlived_multiple.C
> Update lf injector with gap

- DATA/production/configurations/asyncReco/setenv_extra.sh
> Fix typo preventing correct vdrift for <22m periods

- MC/run/PWGEM/runHFFullToDielectrons_pp.sh
> Fix external trigger

- DATA/production/configurations/asyncReco/setenv_extra.sh
> Fix IR for low IR, for scaling of TPC maps

- MC/bin/o2dpg_workflow_utils.py
- MC/utils/o2dpg_sim_metrics.py
Add also an option to convert pipeline_metric to pandas.DataFrame and dump to JSON for later analysis
> Always add meta info (default empty dict)

- RelVal/README.md
- RelVal/o2dpg_release_validation.py
- RelVal/o2dpg_release_validation_utils.py
- RelVal/o2dpg_release_validation_variables.py
* remove some unused code
* move helper and utility functions to o2dpg_release_validation_utils.py and common variables to o2dpg_release_validation_variables.py in view of implementations that allow for more in-depth metrics and threshold studies
* allow to directly pass flat ROOT files ==> no further extraction run in this case. Also in view of aforementioned studies
> [RelVal] Modularise and prepare, clean

- MC/config/PWGHF/external/generator/generator_pythia8_gaptriggered_hf.C
Use the new names for recently modified variables (fix)
> PWGHF: fix variables after renaming

- MC/bin/o2dpg_sim_workflow.py
- UTILS/parse-async-WorkflowConfig.py
should fix https://alice.its.cern.ch/jira/browse/O2-3812
> MC anchoring: Propagate tpc_corr_scaling + more configKeyValues

- DATA/production/configurations/asyncReco/setenv_extra.sh
@sawenzel , can you try?
@shahor02 , @catalinristea , @noferini , FYI
> Forcing MC reco to not apply any correction only if we do not apply distortions in sim

- DATA/production/configurations/asyncReco/async_pass.sh
@noferini , @catalinristea : this is for CPass, for TOF. 
@catalinristea , is it ok to use this var? I see it in the JDL of apass4, for example, and there it is set to -1.
> Enabling TOF output if in CPass mode

- MC/bin/o2dpg_sim_workflow_anchored.py
Better to consistently take run times
from RCT (these values are better according to Chiara).
> Use SOR-EOR from RCT

- MC/bin/o2_dpg_workflow_runner.py
use a combination of early timeframe then graph weight
> pipeline runner: Improved task weights

- MC/utils/o2dpg_sim_metrics.py
* add average values to tasks' bar plots (while bar plots show the max as usual)
* add per-task info to file to be sent to influx
> Plot and influx update

- MC/config/PWGHF/ini/tests/GeneratorHFOmegaCEmb.C
- MC/config/PWGHF/ini/tests/GeneratorHFOmegaCToXiPiEmb.C
- MC/config/PWGLF/ini/tests/GeneratorLFOmegaEmb.C
- MC/config/PWGLF/pythia8/generator_pythia8_box.C
Change in generator_pythia8_box.C: modified id of particle to be generated in order to allow also for anti-particles production
> PWGLF: fix generator to produce anti-particles

- RelVal/PlotOverlays.C
- RelVal/ReleaseValidation.C
- RelVal/o2dpg_overlay_plots.py
Some things still to fix:
- TH2
- use again TRatioPlot if somehow possible
- checks if all files/objects exist
- maximal number of histograms per plot
- return values in python script
Should work also with TTree, but not tested yet
> Script for producing overlay plots

- MC/bin/o2dpg_sim_workflow.py
Follows https://alice.its.cern.ch/jira/browse/O2-3830 
@benedikt-voelkel , what do you think?
> Strangeness tracking in o2dpg_sim_workflow

- MC/config/PWGDQ/ini/GeneratorJPsiHFCorr.ini
- MC/config/PWGDQ/ini/GeneratorJPsiHFCorr_ccbar.ini
- MC/config/PWGDQ/ini/tests/GeneratorJPsiHFCorr_ccbar.C
- MC/config/PWGDQ/pythia8/decayer/jpsi_hf_corr.cfg
- MC/config/PWGHF/external/generator/generator_pythia8_gaptriggered_hf.C
- MC/run/PWGDQ/run_pp_JpsiHFcorr_ccbar_gaptrigger.sh
@lucamicheletti93 this is the config for the MC simulation with c-cbar and Jpsi at forward rapidity triggers, as well as forced charm-hadron decays
> PWGDQ: Add config for MC with JPsi (fwdy) - HF (midy) correlations

- DATA/production/configurations/CTFSkimming/ctf-skim-workflow.sh
> Adjust skimming settings for grid jobs

- MC/config/PWGHF/external/generator/generator_pythia8_gaptriggered_hf.C
- MC/config/PWGHF/ini/GeneratorHFTrigger_OmegaCToXiPi.ini
- MC/config/PWGHF/ini/GeneratorHFTrigger_XiCToXiPi.ini
- update argument values in .ini file for Xic and Omegac generator
- update HF generator to trigger either on quark or on hadron
Hello @fgrosa and @ddobrigk, what do you think about the change in the generator?
> PWGHF: update values in .ini and update generator

- DATA/production/configurations/asyncReco/setenv_extra.sh
> LHC22c, d, e appear as JUN

- RelVal/PlotOverlays.C
allowing comparison plots for more than two TH2 with the PlotOverlays macro
> TH2 overlay plots

- DATA/production/configurations/asyncReco/async_pass.sh
> Add protection for CPass0 flag

- MC/bin/o2dpg_sim_workflow.py
Write confKey to user_config_key_params.json
Can be modified or extended and passed again with
--anchor-config user_config_key_params_modified.json
> [SimWF] Write confKeys, modify, pass again

- MC/run/ANCHOR/2021/OCT/pass4/anchorMC.sh
trivial fix (thanks to @robincaron13 for spotting), merging
> Fix typo in anchorMC.sh

- DATA/production/qc-async/trditstpc.json
- DATA/production/qc-sync/trd.json
- DATA/production/qc-sync/trditstpc.json
Adding input for `TRD/PULSEHEIGHT` 
https://github.com/AliceO2Group/QualityControl/pull/1886
> TRD PulseHeight input binding

- MC/bin/o2dpg_sim_workflow.py
This PR enables the writting of MCH-MID tracks in AODs
> Adding MCH-MID tracks to AOD

- MC/config/PWGEM/external/generator/Generator_pythia8_GapTriggered_HFLepton.C
- MC/config/PWGEM/pythia8/generator/pythia8_bbbar.cfg
- MC/config/PWGEM/pythia8/generator/pythia8_bbbar_forceddecayscharmbeauty.cfg
- MC/run/PWGEM/runHFGapToDielectrons_pp.sh
Update of the Gap trigger HF enhanced MC for dielectrons
> Update of Gap trigger HF enhanced MC

- MC/config/PWGEM/external/generator/Generator_pythia8_GapTriggered_HFLepton.C
- MC/config/PWGEM/pythia8/generator/pythia8_MB_gapevent.cfg
Tunning of MB event in the gap version of HF enhanced MC
> Tunning of MB event

- MC/bin/o2dpg_sim_workflow.py
@sawenzel @chiarazampolli O2 [PR-11713](https://github.com/AliceO2Group/AliceO2/pull/11713) should fix excessive memory and TBuffer overflow problems in SVertexing we see in PbPb, but the strangeness tracking in this case must be invoked directly from the svertexer. So, this PR should go to the production release only with the corresponding O2 [PR-11713](https://github.com/AliceO2Group/AliceO2/pull/11713) and O2Physics [PR-3259](https://github.com/AliceO2Group/O2Physics/pull/3259)
> StrangenessTracking called from the SVertexer following O2 PR-11713

- DATA/production/calib/mch-badchannel-aggregator.sh
download the file before instead
following https://github.com/AliceO2Group/O2DPG/pull/1141
> Do not access consul directly from MCH bad channel wf

- DATA/production/workflow-multiplicities.sh
> Set EVE_NTH_EVENT also for COSMICS

- DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
- DATA/production/configurations/asyncReco/setenv_extra.sh
Make sure it is applied for any dataset where it is requested.
> Move export of CTP offset outside of dataset block

- DATA/production/calib/its-noise-aggregator.sh
- DATA/production/calib/its-noise-processing.sh
- DATA/production/calib/its-threshold-aggregator.sh
- DATA/production/calib/its-threshold-processing.sh
> Added add_W for all ITS calib workflows

- DATA/production/qc-sync/qc-global-epn.json
> Set the bookkeeping url in qc-global-epn.json

- DATA/production/calib/tof-diagn-aggregator.sh
- DATA/production/calib/tof-standalone-cosmic-reco-time-calib.sh
- DATA/production/calib/tof-standalone-reco.sh
- DATA/production/calib/tof-time-calib-aggregator.sh
> modernization TOF workflows

- MC/analysis_testing/o2dpg_analysis_test_workflow.py
* allow checking files on alien
* allow using also input AOD lists
> Make autoset_convertes more flexible

- DATA/production/configurations/asyncReco/setenv_extra.sh
> ptCutoff decreased to 0.3 for TRD

- DATA/common/setenv.sh
> Complete TPC_CORR_SCALING explanation with new options

- DATA/production/qc-async/emc_PbPb.json
- DATA/production/qc-workflow.sh
Adaption of task parameters (mainly histogram
ranges of multiplicity-dependent observables)
based on data from run 543218
> [EMCAL-756] Async QC configuration for PbPb

- DATA/production/qc-workflow.sh
> Fix for EMC in qc-workflow

- RelVal/PlotOverlays.C
- RelVal/README.md
- RelVal/o2dpg_release_validation.py
* accept any number of histograms for overlay
* make 1D overlay plots nicer to look at
* automatic log10 scale if integrals differ by more than 2 orders of magnitude
* unified relative y-ranges for nominal and ratio plot
* choose different line colors
* unify label and title sizes
* re-position legends
* choose x-range such that everything is seen (sometimes the x-axis range is huge while entries are only in some of the first bins and nothing could be seen)
* more ratio plot directly underneath nominal plot and share x-axis
* indicate in overlay plots if something is empty
* always copy overlay plots with inspect command
* copy those overlays that satisfy selection criteria
* add brief QC section to README
> [RelVal] Updates

- DATA/production/qc-async/tpc.json
* proper ccdb
* grpGeom handler
Is required to enable the DCAr plots in TPC QC https://github.com/AliceO2Group/AliceO2/pull/11909
> Add modifications to activate TPC DCAr plots

- DATA/production/configurations/asyncReco/setenv_extra.sh
> Scaling of TPC corr maps for PbPb 2023

- DATA/production/configurations/asyncReco/setenv_extra.sh
Fix for FT0 already merged in O2
> re-enable fit in TOF calibs

- DATA/production/qc-async/itstpc.json
- DATA/production/qc-sync/glo-itstpc-mtch-qcmn-epn.json
> Updating GLO json, following PR O2-11974, QC-2001

- MC/bin/o2dpg_sim_workflow.py
https://github.com/AliceO2Group/AliceO2/pull/12027
> [Sim WF] Adapt strangeness tracker option in AOD

- MC/analysis_testing/o2dpg_analysis_test_config.py
- MC/analysis_testing/o2dpg_analysis_test_utils.py
- MC/analysis_testing/o2dpg_analysis_test_workflow.py
* at the same time, move code related to config and utility to separate file
> [AnalysisQC] Align checker

- DATA/production/configurations/asyncReco/async_pass.sh
Tested in zzi, taking for now this value. 
Further tuning might come.
> Updating PbPb settings

- DATA/production/configurations/asyncReco/setenv_extra.sh
> Possibility to disable strangeness tracking and cascades from JDL

- DATA/production/configurations/asyncReco/setenv_extra.sh
CC-ing: @shahor02 @chiarazampolli @mpuccio
> ITS-vertexer: disable low mult seeds for async PbPb

- MC/analysis_testing/analysis_test.sh
- MC/analysis_testing/o2dpg_analysis_test_utils.py
- MC/analysis_testing/o2dpg_analysis_test_workflow.py
* use for instance --add-common-args EMCAL-shm-segment-size 2500000000 which will be forwarded as a common argument and appended to the analysis pipeline of EMCAL analysis as --shm-segment-size 2500000000
> [AnalysisQC] Enable common args per analysis

- DATA/production/configurations/asyncReco/setenv_extra.sh
this will be needed for obtaining output from the TRD gain calibration in async reco. Ping @chiarazampolli
> TRD gain calibration settings for async

- DATA/production/configurations/asyncReco/setenv_extra.sh
@shahor02 .
@catalinristea , if this gets merged, then it is needed to process runs from 2023 PbPb without ZDC.
> If ZDC is not there, scale with FT0

- DATA/production/configurations/asyncReco/async_pass.sh
@shahor02 , @ktf , @davidrohr , @catalinristea
> To enable DPL REPORT PROCESSING from JDL

- DATA/production/configurations/asyncReco/async_pass.sh
> Possibility to limit the number of CTF files for debug

- DATA/production/configurations/asyncReco/async_pass.sh
> Avoid to print 2x

- MC/bin/o2dpg_qc_finalization_workflow.py
- MC/bin/o2dpg_sim_workflow.py
- MC/config/QC/json/cpv-clusters-task.json
- MC/config/QC/json/cpv-digits-task.json
- MC/config/QC/json/phs-cells-clusters-task.json
- MC/run/examples/README.md
Hi! This PR adds CPV and PHS QC to MC productions.
> CPV, PHS: add QC tasks to MC

- MC/config/PWGHF/external/generator/generator_pythia8_gaptriggered_hf.C
- MC/config/PWGHF/ini/GeneratorHF_D2H_bbbar.ini
- MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar.ini
- MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_and_bbbar.ini
- MC/config/PWGHF/ini/tests/GeneratorHF_D2H_bbbar.C
- MC/config/PWGHF/ini/tests/GeneratorHF_D2H_ccbar.C
- MC/config/PWGHF/ini/tests/GeneratorHF_D2H_ccbar_and_bbbar.C
@fgrosa @fcolamar @cterrevo @ZFederica @zhangbiao-phy @mfaggin
> Add generator info for each event + add alternate injection of charm and beauty

- MC/bin/o2dpg_sim_workflow_anchored.py
- MC/run/ANCHOR/2022/JUN/pass1/anchorMC.sh
> Fix determination of seed

- DATA/production/configurations/asyncReco/async_pass.sh
> 5 threads for sec vtx in case of PbPb with 2 TF in flight

- DATA/production/configurations/asyncReco/async_pass.sh
- DATA/production/configurations/asyncReco/setenv_extra.sh
- DATA/production/qc-async/mch-tracks.json
This changes are needed for the split async reco. 
@martenole , @aphecetche , please check the changes in setenv_extra (@martenole ) and MCH QC json (@aphecetche ).
Related to https://github.com/AliceO2Group/AliceO2/pull/12171
> Updates to be able to run async reco workflow in split mode

- DATA/production/configurations/asyncReco/setenv_extra.sh
needs https://github.com/AliceO2Group/AliceO2/pull/12207 https://github.com/AliceO2Group/AliceO2/pull/12151 https://github.com/AliceO2Group/AliceO2/pull/12043
> Fixes for PVertexing in PbPb

- MC/config/analysis_testing/json/EventSelectionQA/pbpb/analysis-testing-data.json
- MC/config/analysis_testing/json/EventTrackQA/pbpb/analysis-testing-data.json
- MC/config/analysis_testing/json/EventTrackQA/pp/analysis-testing-data.json
- MC/config/analysis_testing/json/default/pbpb/analysis-testing-data.json
- MC/config/analysis_testing/json/default/pbpb/analysis-testing-mc.json
- MC/config/analysis_testing/json/default/pp/analysis-testing-data.json
- MC/config/analysis_testing/json/default/pp/analysis-testing-mc.json
Setting values to the new defaults as in https://github.com/AliceO2Group/O2Physics/commit/505f13ee032701d54664a63580f0bb9a9a371c5a
> Change default setting of mult. axis for trackQC.

- MC/config/PWGHF/ini/GeneratorHFTrigger_OmegaCToXiPi.ini
- MC/config/PWGHF/ini/GeneratorHFTrigger_XiCToXiPi.ini
- MC/config/PWGHF/pythia8/generator/pythia8_charmtriggers_omegactoxipi.cfg
- MC/config/PWGHF/pythia8/generator/pythia8_charmtriggers_xictoxipi.cfg
- switch to pythia mode 2
- in the generator set doNoQuarkTrigger to default value (false)
> Change settings to generate omegac0 and xic0

- MC/bin/o2_dpg_workflow_runner.py
New production mode for the O2DPG MC workflow executor. In this mode, special end of task functions are run that permit
* intermediate file cleanup
* moving log files into a common archive etc.
For now this is targetting to reduce a problem with too many files on HPC supercomputers.
GRID jobs should enable this mode via `--production-mode`
> New pipeline runner production mode

- MC/config/PWGDQ/ini/GeneratorJPsiHFCorr_ccbar.ini
- MC/config/PWGHF/external/generator/generator_pythia8_gaptriggered_hf.C
- MC/config/PWGHF/ini/GeneratorHFTrigger_OmegaCToXiPi.ini
- MC/config/PWGHF/ini/GeneratorHFTrigger_XiCToXiPi.ini
- MC/config/PWGHF/ini/GeneratorHFTrigger_Xi_Omega_C.ini
- MC/config/PWGHF/ini/tests/GeneratorHFTrigger_Xi_Omega_C.C
- MC/config/PWGHF/pythia8/generator/pythia8_charmtriggers_xicomegac.cfg
- MC/run/PWGHF/run_pp_HFtriggers_xi_omega_c_gaptrigger.sh
- Added list of hadrons to be injected.
- Added a new generalized generator that requires lists of quarks and hadrons to be injected.
- The alternate injection is automatically managed based on the content of the lists.
> Generalizing alternate injection of quarks and hadrons

- DATA/production/qc-async/trd.json
- DATA/production/qc-sync/trd.json
Required for https://github.com/AliceO2Group/QualityControl/pull/2037
> Update TRD QC json for DPL CCDB fetcher

- DATA/production/qc-async/trd.json
Required when https://github.com/AliceO2Group/QualityControl/pull/2037 is merged
> TRD async QC json update CCDB objects

- DATA/common/setenv.sh
- DATA/production/configurations/asyncReco/setenv_extra.sh
Do not merge until https://github.com/AliceO2Group/AliceO2/pull/12264 is not merged.
> Adapt TPC_CORR_SCALING to PR12264

- GRID/utils/grid_submit.sh
- MC/bin/o2dpg_sim_workflow.py
- MC/bin/o2dpg_sim_workflow_anchored.py
* improvements in anchoring service (coll system, energy, interaction rate)
* protection agains zero or wrong interaction rates
> Improvements for anchoring

- DATA/production/qc-async/hmp.json
@gvolpe79 , @JianLIUhep , @noferini , @catalinristea
> fix HMP async QC json

- DATA/production/configurations/asyncReco/setenv_extra.sh
This is the first split of: https://github.com/AliceO2Group/O2DPG/pull/1336
It mirrors what is done for MC in: https://github.com/AliceO2Group/O2DPG/pull/1354
> [PbPb-async-DATA] ITS: Remove obsoleted selections

- DATA/production/configurations/asyncReco/async_pass.sh
> Env var starting with SPLIT are ignored by JDL parser

- DATA/production/qc-async/tpc.json
Implementation of the moving window in async qc of the TPC.
Tested following  instruction in https://github.com/AliceO2Group/QualityControl/blob/master/doc/Advanced.md#moving-windows-of-selected-plots-only.
> Moving window

- DATA/production/configurations/asyncReco/setenv_extra.sh
Restoring default config for reco PbPb
> FT0: restoring previous reco config for PbPb

- MC/run/PWGHF/run_pp_anchor2022_D2H_ccbar_and_bbbar_gap5.sh
Add example script to run D2H MC productions anchored to pp 2022. Same script as in branch `async-2022-apass4-pp-mc`, added also here for bookkeeping.
> Add bash script for D2H anchored MC

- MC/bin/o2dpg_sim_workflow.py
Hoping to reduce zombie jobs and expired jobs for PbPb productions on GRID
> Adjust mem estimates for sgnsim and tpcdigi

- MC/bin/o2dpg_sim_workflow.py
The field CCDB object is created as first step before simulation and Geant should just use this for better consistency.
> Always take field for sim from CCDB

- DATA/production/configurations/asyncReco/setenv_extra.sh
This will only work for tags containing the changes of AliceO2Group/AliceO2#12498
> Use perVertexProcessing in Pb-Pb for ITS tracking

- DATA/production/configurations/asyncReco/setenv_extra.sh
@matthias-kleiner , @catalinristea , let me know if this is fine. 
For now we can use a JDL variable, if we don't change tag for pp 2022 reco on skimmed data. 
Note that I don't know Marian's github account, I try with @mivanov.
> Change scaling factor to 10^-5 if we run on skimmed data

- DATA/production/configurations/asyncReco/setenv_extra.sh
> Enable M-shape correction by defualt if any correction is allowed

- MC/bin/o2dpg_sim_workflow_anchored.py
* remove `currenttime` and use `timestamp` everywhere
* add comments in determine_timestamp, especially making clear where seconds, milliseconds or microseconds are used
> [SimWF] Comments for anchored WF script

- DATA/production/configurations/asyncReco/setenv_extra.sh
Since the CTP lumi is requested by default even if scaling with IDCs is used, the parameters to configure TPC corrections `TPC_CORR_SCALING` are modified as:
`ALIEN_JDL_MEANIRFORTPC`  (by default: empty)
```
>0 : use at face value to set TPCCorrMap.lumiMean, overriding mean lumi of the map
<0 : disable ALL corrections
```
`ALIEN_JDL_INSTIRFORTPC` (by default: CTP)
```
>0 : use at face value to set TPCCorrMap.lumiInst which will override ONLY CTP lumi value.
(which does not affect the lumi used for scaling with IDCs)
CTP: use Lumi from the CTP Data (as above: not necessarilly for corrections scaling) 
CTPCCDB: extract CTP lumi from CCDB CTP scalers and override CTP Lumi TPCCorrMap.lumiInst (same comment as above)
```
New variable defining what is used for corrections scaling was added …
> Adjust TPC scaling options to O2 PR12653

- MC/bin/o2dpg_sim_workflow.py
https://its.cern.ch/jira/browse/O2-4612
> prototypic addition of TPC time series O2-4612

- DATA/production/configurations/asyncReco/setenv_extra.sh
> Bug fix for sampling

- UTILS/FileIOGraph/README.md
- UTILS/FileIOGraph/analyse_FileIO.py
- UTILS/FileIOGraph/monitor_fileaccess.cpp
A small set of tools allowing to produce a report of which O2DPG MC task reads and produces which files
> Utility to produce and analyse file-task graph relationships

- DATA/production/qc-async/trd.json
- DATA/production/qc-sync/trd.json
Implementing minor suggestions from https://its.cern.ch/jira/browse/QC-1060
> Update TRD QC json files

- .github/workflows/check-json-syntax.yml
As requested here: https://github.com/AliceO2Group/O2DPG/pull/1453#issuecomment-1937833030
> Check JSON syntax for pull requests

- MC/bin/o2dpg_qc_finalization_workflow.py
- MC/bin/o2dpg_sim_workflow.py
Hi @chiarazampolli, @benedikt-voelkel, 
With this PR, we can upload MC QC objects to the newly created qcdb by @Barthelemy: https://its.cern.ch/jira/browse/QC-1094 
I tested it locally, and all looked good. If you agree, we can merge it and see if everything goes well with nightly tests. 
Thank you.
> moving MC QC from test ccdb to qcdb

- MC/run/ANCHOR/anchorMC.sh
> Update anchorMC.sh - added proc arg

- MC/bin/o2_dpg_workflow_runner.py
following a recent change in class data layout
introduced here: https://github.com/AliceO2Group/O2DPG/commit/ec4acee8f0d38616b6fa45809661213c9b938acc
> pipeline_runner: Fix script creation

- MC/bin/o2dpg-workflow-tools.py
- MC/bin/o2dpg_sim_workflow.py
- MC/bin/o2dpg_sim_workflow_anchored.py
* o2dpg_sim_workflow_anchored.py
* remove unused function from CCDBAccessor due to undefined utility function that is used inside it
* fix variable name
* o2dpg_sim_workflow.py
* fix dependency of cleanup task
* o2dpg-workflow-tools.py
* use return value of function correctly
> [SimWF] Small fixes

- UTILS/o2dpg_make_github_pr_report.py
* applicable to different repos
* distinguishes between merged and other (simply closed or still open) PRs
* dumps the output into a simple text file for further proessing
> Add tool to fetch PR information based on assigned labels

- MC/run/ANCHOR/anchorMC.sh
- MC/run/ANCHOR/tests/test_anchor_2023_apass2_PbPb.sh
- MC/run/ANCHOR/tests/test_anchor_2023_apass2_pp.sh
- test/common/utils/utils.sh
- test/run_workflow_tests.sh
Runs a very simple anchored production, 2TFs, 2PbPb each
> [Anchor] Add test for anchored MC

- GRID/utils/extractErroredLogFiles.sh
- GRID/utils/grid_submit.sh
Fix issues found in https://github.com/AliceO2Group/O2DPG/pull/1469, in addition to those fixed in https://github.com/AliceO2Group/O2DPG/pull/1479.
> Fix Bash syntax issues found by shellcheck

- DATA/production/qc-async/itstpc.json
- DATA/production/qc-async/itstpctof.json
- DATA/production/qc-async/itstpctofwtrd.json
- DATA/production/qc-sync/glo-itstpc-mtch-qcmn-epn.json
- DATA/production/qc-sync/itstpctof.json
- DATA/production/qc-sync/itstpctrdtof.json
- MC/config/QC/json/ITSTPCmatchedTracks_direct_MC.json
- MC/config/QC/json/tofMatchedTracks_AllTypes_direct_MC.json
- MC/config/QC/json/tofMatchedTracks_ITSTPCTOF_TPCTOF_direct_MC.json
@shahor02 , @noferini , @ercolessi , @njacazio 
@ercolessi , @njacazio , @noferini : for TOF, the same should be done online
> Do not ask for geometry in GLO ITS-TPC and TOF matching QC

- DATA/production/configurations/asyncReco/async_pass.sh
> Do not split the metrics, as it is too slow, unless requested

- MC/run/ANCHOR/anchorMC.sh
Additionally, some minor clarifications and transparent changes.
> [Anchor] Remove -k from QC run, return error code

- DATA/production/configurations/asyncReco/async_pass.sh
@catalinristea , @noferini , @shahor02
> Possibility to take QC alone when we split the wf

- MC/analysis_testing/o2dpg_analysis_test_workflow.py
- MC/bin/o2dpg_sim_workflow.py
- MC/bin/o2dpg_workflow_utils.py
* centralise function that creates the task
* apply also when using AnalysisQC CLI
> [SimWF] Use __global_init_task__ more consistently

- DATA/production/configurations/asyncReco/async_pass.sh
@shahor02 
Now by default the rate limiting is the one of the full wf, also if we split. 
This means that it will depend on whether we run on CPU or GPU, and if we are in pp or PbPb.
Do you prefer that I give a fixed value instead?
> Adjusting the logic for the rate limiting in split wf

- DATA/production/calib/phs-led.sh
- DATA/production/calib/phs-pedestal.sh
Hello! This PR is for modernization of PHS standalone calibration workflows, namely Pedestal and LED calibration.
> PHS: modernize Ped and LED calibration workflows

- MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_and_bbbar_gap3_Mode2.ini
- MC/config/PWGHF/ini/tests/GeneratorHF_D2H_ccbar_and_bbbar_gap3_Mode2.C
- MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays.cfg
- MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_Mode2.cfg
@cterrevo @ZFederica @zhangbiao-phy @fgrosa @fchinu
> Enhance fraction of D+ to KKpi in D2H MC + new configuration

- DATA/production/qc-async/its.json
- MC/config/QC/json/its-clusters-tracks-qc.json
This has to go with https://github.com/AliceO2Group/QualityControl/pull/2203
> ITS: flag to disable 1 histo in track task

- DATA/common/setenv_calib.sh
Goes with https://github.com/AliceO2Group/AliceO2/pull/12924
> add RCT updated workflow to calib aggregator

- DATA/production/qc-async/cpv.json
- DATA/production/qc-async/phs.json
Hi! These changes bring modification of qc async jsons for CPV and PHS which were discussed during qc review 2023 together with Barth and Piotr.
> CPV, PHS: update qc-async json config according to QC review 2023

- DATA/production/qc-workflow.sh
To be merged once QC 0.138 becomes available
> qc-workflow: Do not try to write to InfoLogger at all if not in online mode

- DATA/common/setenv_calib.sh
> Fix in the RCT updated deployment

- MC/config/PWGLF/xsection/g4config_had_x2.in
> Use inelastic XS for nuclei

- DATA/production/calib/tpc-pedestal.sh
- DATA/production/calib/tpc-pulser-long.sh
- DATA/production/calib/tpc-pulser.sh
- DATA/testing/detectors/TPC/tpc-laser-raw-filter.sh
Reported in https://github.com/AliceO2Group/O2DPG/pull/1568#discussion_r1549250830
> Fix type lcoalhost -> localhost

- MC/config/PWGLF/ini/GeneratorLF_Resonances_PbPb5360_injection.ini
- MC/config/PWGLF/ini/GeneratorLF_Resonances_PbPb5360_trigger.ini
- MC/config/PWGLF/ini/GeneratorLF_Resonances_pp1360_injection.ini
- MC/config/PWGLF/ini/GeneratorLF_Resonances_pp1360_trigger.ini
- MC/config/PWGLF/ini/GeneratorLF_Resonances_pp900_injection.ini
- MC/config/PWGLF/ini/GeneratorLF_Resonances_pp900_trigger.ini
- MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_PbPb5360_injection.C
- MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_PbPb5360_trigger.C
- MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_pp1360_injection.C
- MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_pp1360_trigger.C
- MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_pp900_injection.C
- MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_pp900_trigger.C
- MC/config/PWGLF/pythia8/generator/resonancelistgun_inj.json
- MC/config/PWGLF/pythia8/generator/resonancelistgun_trig.json
- Split the method: injection and Triggering
- Use injection only the resonances not produced by Pythia.
- Add PbPb injection script.
We're currently comparing the efficiency between injection and triggering. Once it's done, we'll ping.
> Update Resonance injection scripts

- DATA/production/configurations/asyncReco/async_pass.sh
> Possibility to set delay to 0

- MC/config/PWGEM/external/generator/GeneratorCocktailWithGap.C
- MC/config/PWGEM/external/generator/Generator_pythia8_GapTriggered_LFee.C
- MC/config/PWGEM/external/generator/Generator_pythia8_GapTriggered_LFgamma.C
- MC/config/PWGEM/ini/Generator_GapTriggered_LFee.ini
- MC/config/PWGEM/ini/Generator_GapTriggered_LFgamma.ini
- MC/config/PWGEM/ini/tests/Generator_GapTriggered_LFee.C
- MC/config/PWGEM/ini/tests/Generator_GapTriggered_LFgamma.C
MC/config/PWGEM: add Generator.C and ini for LF->ee/gamma in PWGEM
> MC/config/PWGEM: add Generator.C and ini for LF->ee/gamma in PWGEM

- MC/analysis_testing/analysis_test.sh
- MC/analysis_testing/o2dpg_analysis_test_config.py
- MC/analysis_testing/o2dpg_analysis_test_utils.py
- MC/analysis_testing/o2dpg_analysis_test_workflow.py
* update o2dpg_analysis_test_config.py
* take user config if given
* fall back to config in analysis output directory
* fall back to default O2DPG config
* update analysis_test.sh
* copy a config to the analysis output directory to contain the MergedAnalyses analysis
> [AnalysisQC] Align some depending code

- UTILS/README.md
- UTILS/o2dpg_make_github_pr_report.py
* report all PRs that are marked with "async-*" labels merged, closed (not merged), open
* sort then by label
> [AsyncSW] Update fetching of PRs

- MC/config/PWGLF/ini/GeneratorLF_Resonances_PbPb5360_injection.ini
The GeneratorPythia part is not working with the injection script.
> PWGLF: Disable generator for the injection script

- DATA/production/qc-async/mft.json
- DATA/production/qc-sync/mft-full-no-tracks.json
- DATA/production/qc-sync/mft-full.json
- MC/config/QC/json/mft-clusters.json
Remove the changes introduced in the ITS commit fae72c3
> MFT json files: revert to 2ce7d32

- DATA/production/qc-async/tof.json
- MC/config/QC/json/tofdigits.json
Change required after the merge of this PR: https://github.com/AliceO2Group/QualityControl/pull/2261
Following also https://its.cern.ch/jira/browse/QC-1166
Could you confirm if this change enough @ktf @chiarazampolli ?
cc: @noferini @njacazio
> TOF: adapt to change in CCDB fetcher

- MC/config/ALICE3/pythia8/generator_pythia8_ALICE3.C
Correcting the printout for the seed used by the generator.
> ALICE3: Correcting printout

- MC/config/PWGEM/external/generator/Generator_pythia8_GapTriggered_HFLepton.C
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_BeautyForcedDecay_Gap3.ini
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_BeautyForcedDecay_Gap4.ini
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_BeautyForcedDecay_Gap5.ini
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_BeautyForcedDecay_Gap6.ini
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_BeautyForcedDecay_Gap7.ini
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_BeautyNoForcedDecay_Gap3.ini
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_BeautyNoForcedDecay_Gap4.ini
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_BeautyNoForcedDecay_Gap5.ini
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_BeautyNoForcedDecay_Gap6.ini
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_BeautyNoForcedDecay_Gap7.ini
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_Charm_Gap3.ini
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_Charm_Gap4.ini
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_Charm_Gap5.ini
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_Charm_Gap6.ini
- MC/config/PWGEM/ini/GeneratorHFGapTriggered_Charm_Gap7.ini
Add flags to identify different external generators.
@feisenhu @rbailhac @dsekihat could you check that is implemented as we discussed?
> PWGEM: Lmee add generator flags

- GRID/utils/grid_submit.sh
> Fix return code in grid_submit

- MC/config/ALICE3/ini/pythia8_PbPb_536tev.ini
- MC/config/ALICE3/ini/tests/pythia8_PbPb_536tev.C
- MC/config/ALICE3/pythia8/generator/pythia8_PbPb_536tev.cfg
We would like to add a PbPb configuration for OTF simulations on hyperloop
> ALICE3: Add PbPb configuration

- MC/config/PWGEM/ini/GeneratorEMCocktail.ini
change weighting mode in .ini file
> MC/PWGEM: update .ini for LFCocktail

- MC/config/PWGHF/external/generator/generator_pythia8_embed_hf.C
- MC/config/PWGHF/external/generator/generator_pythia8_gaptriggered_hf.C
This PR adds the pT-hard bins as in Run2, that were missing in https://github.com/AliceO2Group/O2DPG/pull/1666
> PWGHF: Add possibility to pass pT-hard bins from script

- MC/config/PWGEM/external/generator/Generator_pythia8_GapTriggered_LFee.C
- MC/config/PWGEM/external/generator/Generator_pythia8_GapTriggered_LFgamma.C
PWGEM/MC: remove J/psi from ee and add K0S for nm
> PWGEM/MC: remove J/psi from ee and add K0S for nm

- MC/config/PWGEM/ini/Generator_GapTriggered_LFee_all_np1_gap8.ini
- MC/config/PWGEM/ini/Generator_GapTriggered_LFgamma_np1_gap2.ini
- MC/config/PWGEM/ini/Generator_GapTriggered_LFgamma_np1_gap4.ini
- MC/config/PWGEM/ini/Generator_GapTriggered_LFgamma_np1_gap6.ini
- MC/run/PWGEM/runAnchoredPythia8GapTriggeredLFee_pp_np1_gap10.sh
- MC/run/PWGEM/runAnchoredPythia8GapTriggeredLFee_pp_np1_gap8.sh
- MC/run/PWGEM/runAnchoredPythia8GapTriggeredLFgamma_pp_np1_gap2.sh
- MC/run/PWGEM/runAnchoredPythia8GapTriggeredLFgamma_pp_np1_gap4.sh
- MC/run/PWGEM/runAnchoredPythia8GapTriggeredLFgamma_pp_np1_gap6.sh
MC/PWGEM: add ini and sh files for LF->ee and gamma
> MC/PWGEM: add ini and sh files for LF->ee and gamma

- test/common/utils/utils.sh
- test/run_generator_tests.sh
- test/run_relval_tests.sh
- test/run_workflow_tests.sh
* function renaming for more clarity
* allow filtering on tests
> Changes to generator testing script

- MC/config/PWGEM/external/generator/Generator_pythia8_GapTriggered_HFLepton.C
@dsekihat This should fix the edge effects in number of trigger events per job
> Add offset to mitigate edge effects min bias to trigger event ratio

- MC/config/PWGHF/external/generator/generator_pythia8_embed_hf.C
This PR fixes the mother indexing in HF generator @mfaggin @fgrosa
> PWGHF: adjust mother-daughter indexing in generator

- MC/config/PWGLF/ini/GeneratorLF_SyntheFlow.ini
- MC/config/PWGLF/ini/tests/GeneratorLF_SyntheFlow.C
- MC/config/PWGLF/pythia8/generator_pythia8_syntheFlow.C
@njacazio @otonvd (not sure if I can find everyone to tag here, might send a mail later)
> Synthetic flow generator added

- MC/config/PWGLF/ini/GeneratorLF_Strangeness_PbPb5360_injection.ini
- MC/config/PWGLF/ini/tests/GeneratorLF_Strangeness_PbPb5360_injection.C
- MC/config/PWGLF/pythia8/generator_pythia8_extraStrangeness.C
@njacazio a re-do of the stale https://github.com/AliceO2Group/O2DPG/pull/1605 , this works just fine and adds 5x more multi-strange than a realistic curve (while keeping Nch within a percent of original, give or take)
> LF: add multi-strange enriched generator

- DATA/production/calib/its-threshold-processing.sh
cc @shahor02 
to go with https://github.com/AliceO2Group/AliceO2/pull/13459/ (which is already merged)
> ITS calib: always parse trigger option

- MC/config/ALICE3/ini/pythia8_pp_13tev.ini
- MC/config/ALICE3/ini/pythia8_pp_ropes_13tev.ini
- MC/config/ALICE3/ini/pythia8_pp_shoving_13tev.ini
- MC/config/ALICE3/ini/tests/pythia8_pp_13tev.C
- MC/config/ALICE3/ini/tests/pythia8_pp_ropes_13tev.C
- MC/config/ALICE3/ini/tests/pythia8_pp_shoving_13tev.C
- MC/config/ALICE3/pythia8/generator/pythia8_pp_13tev.cfg
- MC/config/ALICE3/pythia8/generator/pythia8_pp_ropes_13tev.cfg
- MC/config/ALICE3/pythia8/generator/pythia8_pp_shoving_13tev.cfg
Hi! With this PR we want to add the following 13 TeV pp configurations: Monash, Ropes, and Shoving.
> ALICE 3: Add 13 TeV pp configurations

- MC/run/PWGLF/run_StrangenessInjected_PbPb.sh
- MC/run/PWGLF/run_SyntheticFlow_PbPb.sh
> [LF] add scripts to run simulations for PbPb

- DATA/production/calib/emc-pedestal-aggregator.sh
Needed for start / end of message instruction in object
send to the DCS CCDB
> [EMCAL-1118] Request addRunNumber in calibrator task

- UTILS/checkCorruptedAO2Ds.C
- UTILS/findCorruptedAO2Ds.sh
@chiarazampolli this is the script to find the corrupted AO2Ds, as discussed offline
> Add simple script to find corrupted AO2Ds in MC productions

- DATA/production/configurations/asyncReco/setenv_extra.sh
@wiechula , @alcaliva , @catalinristea , @shahor02 , @aschmah
> ZDC scaling factor should be used from 2023 on, not just 2023

- MC/run/PWGLF/run_SyntheticFlowXi_PbPb.sh
@njacazio @ChiaraDeMartin95 @ercolessi sorry, forgot the tester script so we can test also the synthetic flow with xi generator - now added!
> PWGLF: add synthetic flow with xi tester

- MC/config/PWGEM/external/generator/Generator_pythia8_GapTriggered_LFmumu.C
- MC/config/PWGEM/ini/Generator_GapTriggered_LFmumu.ini
This PR is linking to the following PR.
https://github.com/AliceO2Group/AEGIS/pull/21
> Configured Exodus for dimuon decay

- DATA/production/qc-async/its.json
Added several moving window objects to ITS aQC:
- Cluster Task: cluster occupancy for 7 layers
- Track Task: NClustersPerTracks, NTracks and AngularDistribution
> ITS: Added Moving Window objects

- DATA/production/configurations/asyncReco/setenv_extra.sh
> Bug fix when selecting TFs

- MC/config/analysis_testing/json/analyses_config.json
Centrality task dependence missing
> Disable qa-efficiency task in AnalysisQC

- MC/config/PWGEM/ini/GeneratorEMCocktail_Run3pp_v2.ini
for on-the-fly cocktail simulations
> [PWGEM] LMee: added new ini file for 13 TeV pp cocktail

- MC/config/PWGHF/ini/GeneratorHF_mu_bbbar_gap3_Mode2_accSmall.ini
- MC/config/PWGHF/ini/GeneratorHF_mu_ccbar_gap3_Mode2_accSmall.ini
- MC/config/PWGHF/ini/tests/GeneratorHF_mu_bbbar_gap3_Mode2_accSmall.C
- MC/config/PWGHF/ini/tests/GeneratorHF_mu_ccbar_gap3_Mode2_accSmall.C
- MC/config/PWGHF/ini/tests/GeneratorHF_mu_ccbar_gap5_Mode2_accInt_muTrig.C
- MC/config/PWGHF/ini/tests/GeneratorHF_mu_ccbar_gap5_Mode2_accLarge.C
- MC/config/PWGHF/ini/tests/GeneratorHF_mu_ccbar_gap5_Mode2_accLarge_muTrig.C
- MC/config/PWGHF/ini/tests/GeneratorHF_mu_ccbar_gap5_Mode2_accSmall.C
1- new ini files and macros for charm and beauty  production of muons  with gap3
2- correction of typos in macros for charm production with gap5
> PWGHF: muon production with gap3 and correction of typo in charm macros with gap5

- DATA/common/setenv.sh
- DATA/production/configurations/asyncReco/setenv_extra.sh
This reverts commit a0c44bc6c1330e84deee2813a7e3bb2343127a62.
Sorry, my fault, this was not needed. See discussion in https://github.com/AliceO2Group/O2DPG/pull/1925.
> Revert "Move some part back to setenv.sh"

- MC/bin/o2dpg_sim_workflow.py
> Big shared mem for TPC

- DATA/production/configurations/asyncReco/setenv_extra.sh
Time gain is now take from a specific MC entry
> TPC: Remove disabling TimeGain in MC

- MC/bin/o2dpg_qc_finalization_workflow.py
- MC/bin/o2dpg_sim_workflow.py
until https://its.cern.ch/jira/browse/O2-5885 is fixed
> disable MCHMFT QC task until it is fixed

- DATA/production/configurations/asyncReco/setenv_extra.sh
Goes with https://github.com/AliceO2Group/AliceO2/pull/14144
@wiechula
> Possibility to digest ALIEN_JDL_TPCDEDXCLMASKALT and ALIEN_JDL_TPCEDGETWOPADS

- DATA/production/qc-async/itstpc.json
- DATA/production/qc-sync/glo-itstpc-mtch-qcmn-epn.json
@f3sch , as we discussed.
Fixed also the json in the qc_sync folder, even if I don't think it is used.
> Remove sources and inputs in async json, and fix for sync

- DATA/production/qc-async/ft0.json
- MC/config/QC/json/ft0-reconstruction-config.json
preparation for next FT0 reco patch in QC
> FT0 recoQC: askGRPLHCIF added into cfg

- MC/config/PWGLF/ini/GeneratorLFHyperNucleiPbPbGapWithFlow.ini
- MC/config/PWGLF/ini/tests/GeneratorLFHyperNucleiPbPbGapWithFlow.C
> Fix generator path for nuclei with flow

- MC/run/PWGLF/run_HyperNucleiInjectedGapWithFlow.sh
> Add runTask for injected nuclei with flow

- MC/config/PWGEM/ini/Pythia8_Beauty_Cocktail_pp13.ini
- MC/config/PWGEM/ini/Pythia8_Charm_Cocktail_pp13.ini
- MC/config/PWGEM/pythia8/generator/pythia8_hf_cocktail_pp13.cfg
> HF cocktail for 13 TeV

- MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_Mode2_CorrBkg.cfg
- MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_Mode2_hardQCD_5TeV_CorrBkg.cfg
This PR fixes the decay table of correlated backgrounds. @mfaggin @fgrosa for your knowledge.
> [PWGHF] Fix correlated bkg configs

- MC/bin/o2dpg_sim_workflow.py
In the same spirit as already possible for signal + background event simulation.
> Possibility to pass ConfigKeyValues for the QED simulation

- MC/config/PWGDQ/external/generator/GeneratorPromptCharmonia.C
Fixing issue with 5TeV generator
> [PWGDQ] Fixing issue with 5TeV generator

- MC/config/PWGUD/external/generator/GeneratorStarlight.C
- MC/config/PWGUD/ini/makeStarlightConfig.py
-Jpsi to Lambda + AntiLambda
-NeNe setup
> Extra Jpsi decay and Neon setup

- MC/config/PWGDQ/ini/Generator_InjectedPromptCharmoniaFwdy_TriggerGap_OO5TeV.ini
- MC/config/PWGDQ/ini/tests/Generator_InjectedPromptCharmoniaFwdy_TriggerGap_OO5TeV.C
- MC/config/PWGDQ/pythia8/generator/pythia8_inel_triggerGap_OO5TeV.cfg
Adding configuration for light nuclei
> [PWGDQ] Adding configuration for light nuclei

- MC/config/PWGHF/pythia8/generator/pythia8_HFe_Mode2.cfg
Delete light meson decays and change the heavy-flavour decay products
> modify decay chains

- MC/config/analysis_testing/json/dpl/o2-analysistutorial-mc-histograms.json
fixing this problem reported by @marslandALICE
> New config for analysis task - reduce verbosity

- MC/config/PWGHF/ini/GeneratorHF_HFe_ccbar_and_bbar_gap5_Mode2.ini
> change eta gap
