AliceO2Group/O2DPG

MC/run/PWGHF/calc_embedding_speedup.sh
MC/run/PWGHF/embedding_benchmark.sh

A PWGHF benchmark for embedding that can be run on the GRID or locally (when ALIEN_PROC_ID is set).
Multiple timeframes can be digitized, each reusing the same background events
with different signal.
The goal is to obtain embedding gain numbers as a function
of the number of timeframes, etc.

adding a complete benchmark for embedding

---

MC/run/PWGHF/embedding_benchmark.sh

SHMSIZE adjustment (learning from first GRID exercise)

Adjustments for PWGHF embedding benchmark

---

MC/run/PWGHF/embedding_benchmark.sh

Introducing better organization: Persistent results
are collected in an output folder. (So that's its easier for a GRID
job to know what to keep).

GRID embedding bench: Collect output + cleanup

---

.github/workflows/release.yml

This should fix the error seen in
https://github.com/AliceO2Group/O2DPG/runs/1430098425.

Update apt repos before installing

---

MC/config/common/pythia8/generator/pythia8_KrKr.cfg

Kr-Kr config file

---

MC/run/PWGHF/embedding_benchmark.sh

* some minor adjustments: be able to set engine

HF embedding: complement workflow up to AOD

---

MC/run/PWGHF/embedding_benchmark.sh

* clusters need to be sent per sector to prevent
ROOT serialization problems
* tpc-reco: constrain to given number of cores
(otherwise benchmark might be slightly wrong when
executed on many-core architectures)

Changes to PWGHF embedding script

---

GRID/utils/grid_submit.sh

Utility to submit arbitrary scripts to the GRID.
Takes care of interaction with ALIEN and provides some
logging/monitoring and control framework.
For instance, the following command
```
./grid_submit.sh --ttl 40000 --script job_test.sh --topworkdir foo --label bar --jobname baz  \
--o2tag nightly-20210125-1                                                   \
--mattermost https://mattermost.web.cern.ch/hooks/HOOKID
```
submits the script 'job_test.sh' to the GRID with a TTL of 40000, to be stored
in top-level folder 'foo' (relative to the users home), having 'baz' as process name in ALIEN,
carrying production label 'bar', using the nightly software release 'nightly-20210125-1', and
sending progress information to an **optional** mattermost webhook

Add grid_submit utility

---

MC/config/PWGHF/pythia8_gun/configOmegaAnd20Pions_randomCharge.ini
MC/config/PWGHF/pythia8_gun/config_custom_OmegaC.cfg
MC/config/PWGHF/pythia8_gun/generator_pythia8_gun.C

Event generator based on Pythia8 that injects only the desired particles in the event, which can be used with o2-sim.
Files:
1) generator_pythia8_gun.C: it contains the class with the generator  and the custom functions to be called from the *.ini file;
2) config_custom_OmegaC.cfg: custom settings for OmegaC generations.
In this version: decay forced to Omega-pion; ctau set to 80 micron;
3) configOmegaAnd20Pions_randomCharge.ini: example of config file used to call the gun.
The function produces events containing a Omega (with random sign) plus 10 pi+ and 10 pi-.
The function is defined inside the file in point 1).

First commit of Pythia8 gun event generator

---

.github/workflows/release.yml

This allows an optional trailing letter on the version, for multiple releases in a day.

Update GH action for new release convention

---

MC/bin/o2dpg_sim_workflow.py
MC/run/PWGHF/create_embedding_workflow.py
MC/utils/merge_TTrees.C

... Mainly geared to being able to process 100PbPb within 16GB.
Changes to workflow generator
* Split TPC clusterization into 2 stages
so that we can fit into 16GB for ~100PbPb.
* Introduce additional cluster merging step
to prepare one file for TPC reco
* Add ROOT macro helper for the merge step
(to be generalized later)
* Adjust some memory/cpu resource estimates
(based on ~100PbPb dataframes)
* Don't use --rate 1 for TOF reco workflow.
Now terminates much faster.

Some changes on workflow generation

---

MC/bin/o2_dpg_workflow_runner.py
MC/bin/o2dpg_sim_workflow.py

* do not use default /tmp dir for socket files,
as they may leak and pose a problem in the long run
* offer configurability of fairmq-ipc-prefix
* the pipeline runner set this to a new local .tmp
folder

Do not leak FairMQ socket files

---

MC/bin/O2DPG_pp_minbias.sh
MC/bin/o2dpg_sim_workflow.py
MC/config/QC/json/dpl-config.json
MC/config/QC/json/its-clusters-tracks-qc.json
MC/config/QC/json/qc-mft-cluster.json
MC/config/QC/json/qc-mft-digit.json
MC/config/QC/json/qc-mft-track.json
MC/config/QC/json/tpc-qc-tracking-direct.json
MC/config/QC/json/trd-digits-task.json
MC/config/QC/json/vertexing-qc-direct-mc.json
MC/run/examples/O2DPG_pp_minbias_one_tf_qc.sh

This adds 5 QC Tasks, which can be enabled with --include-qc flag passed to o2dpg_sim_workflow.py. In this iteration they publish results directly to QCDB (at ccdb-test) and results from many TFs and sub-jobs are not merged.
More Tasks to come, also merging will be done in future PRs.
An example to run it can be found in `MC/run/examples/O2DPG_pp_minbias_one_tf_qc.sh`

Initial integration with QC Tasks

---

MC/run/PWGDQ/runPromptCharmonia_fwdy_pp.sh
MC/run/PWGDQ/runPromptJpsi_midy_pp.sh

Running scripts for running PWGDQ simulations (min. bias pythia + prompt charmonium signals, mid / fwd rapidity). 
@sawenzel: these are tested locally at MC truth level. If possible, we would like to include them in one of the nightlies tests for testing the full simulation chain. Thanks a lot in advance for any comment.

running scripts (PWGDQ)

---

MC/bin/o2dpg_sim_workflow.py
MC/run/examples/O2DPG_pp_minbias_multiple_tf_qc.sh

This configures QC to merge results across the simulated TFs.
On occasion I enabled the previously broken MFT Digits QC, but I had to disable TPC tracking QA, which seems to be broken now:
```
[17958:QC-TASK-RUNNER-TPCTrackingQA]: [17:01:35][ERROR] Exception caught: Incomplete set of MC labels received 
```
I will let David know.

[QC-602] Merge QC results over timeframes

---

MC/config/PWGDQ/external/generator/GeneratorBeautyToJpsi_EvtGen.C
MC/config/PWGDQ/ini/GeneratorHF_bbbar_fwdy.ini
MC/config/PWGDQ/ini/GeneratorHF_bbbar_midy.ini
MC/config/PWGDQ/trigger/selectDaughterFromHFwithinAcc.C
MC/run/PWGDQ/runBeautyToJpsi_fwdy_pp.sh
MC/run/PWGDQ/runBeautyToJpsi_midy_pp.sh

Dear all, the commit includes:
1) running scripts for non-prompt jpsi simulations (full chain, mid-y / fwd-y) 
2) function (selectDaughterFromHFwithinAcc.C) for triggering on the rapidity of the non-prompt J/psi (since in the current version in O2DPG a rapidity cut is applied only for at least one b or bar{b}, so a lot of J/psi from b  go outside the acceptance). We plan to use the same function for Low Mass Dilepton pairs (from HF) simulations. 
3) small fix / update of initialization files -> name of fileName and funcName of external generator are provided in the initialization files (i.e. file.ini) and not from the command line; in addition I’ve added the lines for triggering on the rapidity (i.e. “[TriggerExternal]” field)
4) update of generation macro -> remove the centrality …

update of scripts+macros for non-prompt J/psi simulations

---

MC/bin/o2dpg_sim_workflow.py
MC/config/QC/json/tofMatchedTracks_ITSTPCTOF_TPCTOF.json

@knopers8 , @sawenzel , @noferini , this is to add the TOF QC to the simulation processing. The QCG shows the plots correctly. I tried reading the object from the file, but for that I had issues, but probably I am doing it in the wrong way, see below for reference. 
Despite this, if you think the PR is ok, we could merge it. 
One more think: the json is copied from QualityControl, isn't it better to find another way?
Chiara
```
Attaching file TOFMatchQC.root as _file0...
(TFile *) 0x3316260
root [1] .ls
TFile**		TOFMatchQC.root	
TFile*		TOFMatchQC.root	
KEY: o2::quality_control::core::MonitorObjectCollection	MatchedTracksITSTPCTOF_TPCTOF;1	object title
root [2] o2::quality_control::core::MonitorObjectCollection* c = (o2::quality_control::core::MonitorObjectCollection*)_file0->Get("MatchedT …
```

Adding TOF matching QC

---

MC/config/QC/json/tofMatchedTracks_ITSTPCTOF_TPCTOF.json

Putting the same parameters as in other tasks, mainly to make the results go to "qc_mc" directory.

Update the parameters for the TOF matching QC

---

MC/config/PWGDQ/EvtGen/DecayTablesEvtgen/BTOPSITOELE.DEC
MC/config/PWGDQ/EvtGen/DecayTablesEvtgen/BTOPSITOMU.DEC
MC/config/PWGDQ/EvtGen/GeneratorEvtGen.C
MC/config/PWGDQ/external/generator/GeneratorBeautyToPsi_EvtGen.C
MC/config/PWGDQ/external/generator/GeneratorCocktailPromptCharmoniaToElectronEvtGen_pp13TeV.C
MC/config/PWGDQ/ini/GeneratorHF_bbbar_Psi2S_fwdy.ini
MC/config/PWGDQ/ini/GeneratorHF_bbbar_Psi2S_midy.ini
MC/run/PWGDQ/runBeautyToPsi_fwdy_pp.sh
MC/run/PWGDQ/runBeautyToPsi_midy_pp.sh
MC/run/PWGDQ/runPromptCharmonia_midy_pp.sh

Dear Experts,
We prepared MC simulation chains for non-prompt Psi(2S) Mid and Forward Y and Prompt Charmonia Mid Y.
Modifications are:
-Added .DEC Fİles h_B to Psi(2S) to Dielectron and Dimuon (for non-prompt Psi(2S) Mid and Forward Y)
-GeneratorEvtgen.C modfied for Non-Prompt Psi(2S) decays.
-Added Generator Config Macros for non-prompt psi(2s) and prompt charmonia mid rapidity.
-Added .ini files for non-prompt Psi(2S) Forward and Mid Y
-Added Run scripts for non-prompt psi(2s) and prompt charmonia mid rapidity

Modifications

---

MC/bin/o2dpg_sim_workflow.py

The added options disable the default mode for MFT reconstruction (optimized for a misaligned detector).

Adding options to MFT reco 

---

MC/bin/o2dpg_sim_workflow.py
MC/run/PWGDQ/runBeautyToJpsi_fwdy_pp.sh
MC/run/PWGDQ/runBeautyToJpsi_midy_pp.sh
MC/run/PWGDQ/runBeautyToPsi_fwdy_pp.sh
MC/run/PWGDQ/runBeautyToPsi_midy_pp.sh
MC/run/PWGDQ/runPromptCharmonia_fwdy_pp.sh
MC/run/PWGDQ/runPromptCharmonia_midy_pp.sh
MC/run/PWGDQ/runPromptJpsi_midy_pp.sh

Added option `--mft-reco-full` to enable full MFT reconstruction, used by PWGDQ scripts. The default is the simplified tracking for a misaligned detector.

Putting MFT full reconstruction as an option

---

MC/analysis_testing/analysis_test.sh
MC/bin/o2dpg_qc_finalization_workflow.py
MC/bin/o2dpg_sim_workflow.py

This seems no longer necessary. Sockets will be anonymous
and not populate /tmp or other visible directories anymore

take out fairmq-ipc-prefix

---

MC/bin/o2dpg_sim_workflow.py

This should fix the issue referred in the Jira ticket: 
https://alice.its.cern.ch/jira/browse/O2-2723

Fix typo that prevented correct round robin scheme in MC with embedding

---

MC/bin/o2dpg_qc_finalization_workflow.py
MC/bin/o2dpg_sim_workflow.py
MC/config/QC/json/qc-mft-async.json

MFT Async QC task is used in central reconstruction and should also be used in official productions.
Also changed `MFTAlpideParam.roFrameLengthInBC` to our lucky number.

[MFT] Switch to MFT ASync QC task

---

DATA/production/qc-async/itstpctof.json
MC/config/QC/json/tofMatchedTracks_ITSTPCTOF_TPCTOF_direct_MC.json

@noferini @ercolessi 
According to discussion with TPC experts this should be indeed better for the matching efficiency

Require more TPC clusters in TOF aSync QC

---

MC/config/common/pythia8/utils/mkpy8cfg.py

This enables diffraction in pythia8 for pp simulation, which is, in particular, required for pilot beam simulation. 
See, for example, pythia8 configs at http://mcplots.cern.ch/?query=plots,ppppbar,mb-inelastic,eta#pp900

Enable diffraction for pp sim

---

MC/bin/o2dpg_sim_workflow.py
MC/run/PWGDQ/runPromptCharmonia_fwdy_pp_assessment.sh

Add options to enable assessment workflows to `o2dpg_sim_workflow.py`
* `--mft-assessment-full` enables MFT standalone assessment workflow, produces `MFTAssessment.root`
*  `--fwdmatching-assessment-full` enables global forward matching assessment workflow, produces `GlobalForwardAssessment.root`
Working example on `MC/run/PWGDQ/runPromptCharmonia_fwdy_pp_assessment.sh`

o2dpg_sim_workflow.py: options to enable forward assessment

---

MC/config/PWGDQ/external/generator/GeneratorCocktailPromptCharmoniaToMuonEvtGen_PbPb5TeV.C
MC/run/PWGDQ/runPromptCharmonia_fwdy_PbPb.sh

Dear Experts,
p_T distributions and Rapidity shapes (parameters) are different for Proton - Proton and Pb-Pb collisions system (For Monte Carlo Simulations).
According to AliDPG Generator Config Macro for J/psi --> Dimuon for Pb-Pb Collision system, I prepared a new generator config macro for Quarkonia Fwdy Pb-Pb MC (PWG-DQ).
You can check reference generator config macro in below:
`https://github.com/alisw/AliDPG/blob/master/MC/CustomGenerators/PWGDQ/Muon_GenParamJpsi_PbPb5TeV_1.C`
Best Regards

Generator Config Macro for PWG-DQ Pb-pb Quarkonia Forward Y and Update run script

---

MC/bin/o2dpg_sim_workflow.py

Allow to specify a timestamp value at which the MC
workflow should execute.
Timestamp is propagated to all parts consistently.
Note:
For the moment, there is no check if the timestamp
is consistent with a given run number. It is foreseen
than an external tool samples the timestamp given
a run number and then passes it forward to the workflow generation.
But we can also offer the option that
a timestamp is automatically chosen based on a run number.

Global timestamp option and consistent propagation

---

MC/bin/o2dpg_sim_workflow.py
MC/config/QC/json/tpc-qc-standard-direct.json

We found an issue with the Clusters task, which will likely lead any MC production to crash. This was not spotted in the small-scale tests done before. For now, it has to be deactivated. Will be reactivated, as soon as the issue could be solved.

TPC-QC: deactivate Clusters Tasks in MC

---

DATA/production/qc-sync/mch.json

following a (long...) debug session we found that : 
- for some yet unclear reason, the `localMachines` list must start with `localhost`
- the task name must match the one in Consul (we'll have revisit the tasks naming at some later date)
Also, the configuration for the checks was removed from this one as the checks run only on the merger (which is configured only with the Consul config.)

MCH: update mch.json for QC

---

DATA/production/calib/its-noise-aggregator.sh
DATA/production/calib/its-noise-processing.sh
DATA/production/standalone-calibration.desc

To use clusters input one should select ITS-noise-calibration-clusters from the
`standalone-calibration.desc`
This PR depends on https://github.com/AliceO2Group/AliceO2/pull/8186

[R3C-752] Change ITS noise calib to digit inputs with 32 threads

---

DATA/production/qc-async/emc.json
DATA/production/qc-sync/emc.json

DigitQcTask has been renamed in
QualityControl v1.46 to CellTask for
consistency with its input source.

[EMCAL-524, EMCAL-525] Renaming digits to cell task

---

MC/config/PWGDQ/external/generator/GeneratorBoxFwd.C
MC/run/PWGDQ/runFwdMuBoxGen_PbPb.sh
MC/run/PWGDQ/runFwdMuBoxGen_pp.sh

This PR adds a generator for forward muons. Examples for embedding in pp and PbPb collisions are provided. This is necessary for forward matching performance studies.

Add forward box generator for matching studies

---

DATA/tools/parse

Thx @aphecetche for reporting.
The problem is: The workflow generation loads the O2DPG module once at the beginning, to have access to the general scripts.
Then it goes to the O2DPG folder specified (either by hash or path), and executes the workflow generation there.
Now, that workflow generation loads an O2PDPSuite, which contains O2DPG in itself.
If that O2DPG version differs from the one that was initially loaded, it loads the other version as well, and that overrides the $O2DPG_ROOT env variable.
This should not happen after we have already explicitly cd'ed to the correct folder, and made that our O2DPG_ROOT.
This is kind of a hack to maintain the env variable, but I see no better solution unfortunately.

Make sure that module loading during workflow generation does not change the O2DPG_ROOT of the current O2DPG that executes the job

---

MC/bin/o2dpg_sim_workflow_anchored.py

A python script that determines timestamp (and production offset)
properties for MC jobs.
This timestamp and other properties are then passed forward
to the known simulation workflow creation.
This is an incremental step towards anchoring, demonstrating the
basic mechanism.
Future improvements are foreseen, such as doing it in a more pythonic
way and sharing functionality between the variuous python scripts.
@Co-Author: Sandro Wenzel

Introducing simple anchoring service layer

---

DATA/production/calib/its-noise-aggregator.sh
DATA/production/calib/its-noise-processing.sh
DATA/production/standalone-calibration.desc

Defaults are set to 4 and 6 respectively, can be modified by NITSDECTHREADS=2 NITSDECTPIPELINES=4 ...

Add env.vars to set nthreads and lanes of ITS decoder in noise processing

---

DATA/production/qc-async/its.json
MC/config/QC/json/its-clusters-tracks-qc.json

added parameter nBCbins to define the number of bins for plots showing bunch-crossing info. 
(ref: https://github.com/AliceO2Group/QualityControl/pull/1060/files)

updated ITS json for QC async and MC according to QC PR1060

---

MC/config/QC/json/tofdigits.json

This is the QC digits to be added in MC workflow as for the data (really needed with anchoring!).
The typical workflow is something like
o2-tof-reco-workflow -b --input-type digits --output-type none| o2-qc -b --config json://${O2DPG_ROOT}/MC/config/QC/json/tofdigits.json --local-batch TOFDigitQC.root

add TOF digits QC for MC

---

MC/bin/o2dpg_sim_config.py
MC/bin/o2dpg_sim_workflow.py
UTILS/parse-async-WorkflowConfig.py

This commit is a step in the direction of being
able to anchor MC workflows to the settings use in
DATA reconstruction passes.
This is achieved via a couple of ingredients:
a) improved configurability of o2dpg_sim_workflow:
- we can give a json config externally, which
may include ConfigKeyValues and other keys
to which the MC workflow creation is sensitive
- separation of default config creation into extra
script
- slight change in the way how tasks declare what ConfigKeyValues
they need / are sensitive too
- can now configure list of sensitive detectors
- can now configure input lists for vertexers and track matcher tasks
b) A script that can parse DPL topologies and parameters from
a file created by DATA reconstruction, and which creates
a json config that can be fed to MC workflow …

DATA-reco anchoring and improved configurability

---

DATA/production/configurations/2021/OCT/apass4/setenv_extra.sh

@noferini , @shahor02 , @sawenzel , @martenole , @tdietel
TRD is now disabled for apass4. 
@sawenzel , can you confirm that you will use this folder for the MC anchored to apass3, to take the correct TPC calibrations, as discussed yesterday?
If so, this is correct, because we want to exclude TRD from MC reco, since in data we saw very low matching efficiency and this cannot now be reproduced in MC.

Remove TRD from reconstructed detectors for apass4

---

DATA/production/calib/its-threshold-aggregator.sh
DATA/production/calib/its-threshold-processing.sh

Changes:
- added 6 pipelines for decoder --> compatible with PR8346 in O2
- added QC workflow for calibration scans 
- removed DCS CCDB link from its-aggregator-wf to use the object upload through ccdb-populator-wf
- added --enable-eos to use end-of-stream at P2
- 1 thread in the decoder: multiple thread meaningless in calibration mode because 1 RU data per TF
- 4 threads in o2-its-thr-calib because the improvement is negligible with more threads.

adapt ITS threshold scripts to PR8346 in O2 + added QC

---

MC/bin/o2dpg_sim_workflow.py
MC/run/ANCHOR/2021/OCT/pass4/anchorMC.sh

We use prefetching and CCDB_CACHING mechanism to serve
the CCDB objects for MC.
Otherwise, they would currently not be fetched at a consistent timestamp
(in line with the run). See https://alice.its.cern.ch/jira/browse/O2-2852.

Prefetch CCDB objects for anchored MC

---

DATA/production/calib/its-threshold-processing.sh
DATA/production/standalone-calibration.desc

This goes with O2 PR8471 (https://github.com/AliceO2Group/AliceO2/pull/8471). In addition:
- refinements for o2-qc 
- 20 -> 40 EPNs (based on last tests at P2)

ITS calib: added chip-mod-selector and chip-mod-base + set default to 40 EPNs

---

DATA/testing/detectors/MID/mid_common.sh

Since the variables were overwritten to warning, no debugging info was available.
With this PR, we restore the default behaviour.

Do not overwrite SEVERITY and INFOLOGGER SEVERITY variables for MID

---

MC/analysis_testing/analysis_test.sh
MC/analysis_testing/o2dpg_analysis_test_workflow.py
MC/bin/o2_dpg_workflow_runner.py
MC/bin/o2dpg_sim_workflow.py
MC/config/analysis_testing/json/analysis-testing.json

* o2dpg_analysis_test_workflows wraps the analysis side of things now
It can be run
1. as script where workflow file with only the analysis tasks is
created
2. as a module to be used inside another workflow generation
==> analyses only need to be maintained in ine place
* no analyses directly implemented in o2dpg_sim_workflow
* changes in o2dpg_sim_workflow fully transparent, --include-analysis
works as before and expected
* change os.mkdir to os.makedirs in o2_dpg_workflow_runner to avoid the
necessity of the user to create certain directories if the soecified
cwd of a tasks is deeper than one directory

Make analysis fully modular

---

DATA/production/configurations/2021/OCT/apass4/setenv_extra.sh

TOF calibration included now
o2calib_tof.root generated
tested with 1 CTF  (66 TFs) from pilot beam
o2calib_tof.root size = 0.5% AO2D size

add TOF cal

---

MC/config/PWGDQ/EvtGen/EvtTRandomEngine.hh
MC/config/PWGDQ/EvtGen/GeneratorEvtGen.C

There was a wrong conversion of units which caused the decay length of the particles to be 10 times smaller.
The random engine used for EvtGen was EvtSimpleRandomEngine. It has a fixed seed and a short period. It is now replaced by EvtTRandomEngine, a wrapper for TRandom.

Add random engine based on TRandom and fix wrong units conversion

---

DATA/production/qc-workflow.sh

TMPDIR is used on many system for the user's temporary dir. Overriding
it and deleting has unwanted consequence that any subsequent usage might
fail, e.g. on macOS this happens when trying to create FairMQ channels
which are backed by unix domain sockets in $TMPDIR. I suspect ROOT would
also have troubles with it for some operations, even on linux.

Fix mishandling of TMPDIR

---

.gitignore
MC/bin/o2dpg_sim_workflow.py
MC/run/PWGHF/run_pp_HFtriggers_bbbar_userhook.sh
MC/run/PWGHF/run_pp_HFtriggers_ccbar_userhook.sh

Hi @benedikt-voelkel, @chiarazampolli, @sawenzel, @fgrosa,
how it was done before the seed was not propagated to the signal generator if a custom configuration of pythia8 was passed in the ini file. What I propose here is that we get a random number starting from the jobid using the python random number generator and then we increase it by 1 for each TF. The maximum seed is truncated to fit the Pythia8 requirements.
Then this number is given as general seed to o2-sim, that already gives it to Pythia and it will be the same we set from outside once AliceO2Group/AliceO2#8727 will be merged.
In the case of the HF injection we were also specifying the process in the bash script, thus leading to the on-the-fly generation of a pythia configuration that was overwriting the HF defaults (it was …

Seed propagation for injected productions

---

RelVal/ReleaseValidation.C
RelVal/o2dpg_release_validation.py

* rename some functions to give a better idea what they are doing
* always compare all found objects
* remove code duplications
* make a user to specify the whole file path, fon't assume or add
".root" file extension
* same for files on the GRID: user has to give full GRID path. When path
begins with ""alien", assume it is on the GRID and initialise
* remove pointers where not really needed
* use same extraction function for any ROOT input file, don't use
specific ones for QC ROOT files and others
* wrap object extraction and plotting as much as possible
No changes have been made wrt the actual comparison and comparison
summary
* add very small python wrapper for convenience

Rework file reading and object extraction

---

DATA/common/setenv.sh
DATA/common/setenv_calib.sh

@davidrohr , @shahor02 
@davidrohr : if you want, the function `add_semicolon_separated()` can be incorporated in `add_common_separated()` in a more general one where one passes also the separator.
Needed by https://github.com/AliceO2Group/AliceO2/pull/8736

adding calib-workflow

---

MC/config/PWGDQ/external/generator/GeneratorParamPromptJpsiToMuonEvtGen_pp13TeV.C
MC/run/PWGDQ/runBeautyToJpsi_fwdy_pp.sh
MC/run/PWGDQ/runPromptCharmonia_fwdy_pp.sh

Updating beam energy in forward scripts to 13.6 TeV. Prompt script updated to generate only a single J/psi per event.

Updating forward Jpsi in pp scripts

---

DATA/common/setenv_calib.sh
DATA/tools/epn/gen_topo.sh

@chiarazampolli : Haven't tested this yet, but this is what I had in mind for the proxy channels:
So for testing locally, but in 2 separate shells, i.e. without CALIB_LOCAL_INTEGRATED_AGGREGATOR, one has to set both CALIB_PROXIES and CALIB_LOCAL_AGGREGATOR. Then it will use SHM transport with a socket file based on the channel name.
If CALIB_PROXIES is set, but CALIB_LOCAL_AGGREGATOR is not, i.e. when we run online on the EPN, we use zeromq transport and leave the address empty, to be filled by FairMQ automatically, in the same way we are doing for the calib workflows at P2 right now already.

Use IPC for local calib connections

---

MC/config/PWGDQ/external/generator/GeneratorParamPromptJpsiToMuonEvtGen_pp13TeV.C

Fix a typo error due to clang-format in the R__ADD_INCLUDE_PATH function

fix wrong typo due to clang-format

---

DATA/common/setenv_calib.sh

@davidrohr 
@noferini : in the current implementation we attach the calibration for TOF (with tracks) also when we have the ITSTPCTOFTRD matching, but probably this case is not needed since, if I am not wrong, we only use ITSTPCTPOF tracks. Can you confirm? If so, I will remove it (even if it does not harm).

Fix condition for TOF calibration

---

DATA/production/qc-sync/its.json

@iravasen : Please note for next time that the QC JSONs in DATA/production/qc-sync are used for the FST. Please update them as well.

Fix ITS QC JSON

---

DATA/common/setenv_calib.sh

@chiarazampolli : I have to disable this since it runs in the default FST and it is way too slow. TPC should look into that, and probably process only a fraction of the data in case of Pb-Pb.

Temporarily disable TPC PADGAINCALIB, it is too slow

---

DATA/production/qc-sync/itstpctrdtof.json

@davidrohr 
I think that the name is too long and it may break with the recent changes in QC framework

fix for name too long in json

---

DATA/production/configurations/2022/MayJunePilotBeam/apass1/setenv_extra.sh
DATA/production/qc-async/trd.json

- TRD: remove the checks for QC: they are badly configured, and anyway
not used;
- VDRIFT: restore correct command
- REMAPPING: fix syntax
@catalinristea: this is though still WIP, I have issues with a PID QC task now. More news asap.

Fixes in apass1 for MayJune 2022 data

---

MC/bin/o2dpg_qc_finalization_workflow.py
MC/bin/o2dpg_sim_workflow.py
MC/config/QC/json/emc-cell-task.json

CellTask was branched off several months ago to
monitor cell level information (in AliRoot Digits and Cells
were the same objects for EMCAL as the time response
was not simulated, with the introduction of time sampling
they diverged). A transition period was kept to not affect
existing productions. The workflows should be adapted now
to allow using the DigitsQCTask to monitor digits (time
sample) level quantities.

[EMCAL-755] Change DigitsQCTask to CellTask in simulation

---

DATA/production/qc-async/mid.json
DATA/production/qc-sync/mid-digits.json
DATA/production/qc-sync/mid.json

This commit was kind of reverted because the corresponding commit in QC was not bumped. This resulted in a failure of the fullCI tests, that was still using an old QC version.
Now the QC is bumped, and the tagged version contains the needed information. The json files can be therefore safely modified accordingly.

Change MID digits query alias to cope with QC modifications now in QC 1.63.0

---

RelVal/ReleaseValidation.C
RelVal/o2dpg_release_validation.py

* previous functionality of comparing 2 files as usual
--> whenever user-specific comparisons are needed, 2 corresponding
files with histograms should be created and passed to the wrapper
Major developments of python wrapper
* include and steer all RelVals via python wrapper
* derive histograms from Kine, TPC tracks and Hit TTrees and perform
RelVal on them
In these cases, 1D histograms are simply extracted for all possible
TLeafs using TTree::Draw. It is made sure that the created histograms
have the same binning and ranges to be comparable
* QC now also part of it
* enable single RelVal with
--with-<which>
where <which> is one of
analysis, qc, kine, hits, tpctracks
These options can be combined arbitrarily.
If none is given, run all of them
* most plots can be disabled passing …

Towards more complete RelVal

---

RelVal/ReleaseValidation.C
RelVal/o2dpg_release_validation.py

* remove redundant plotting of simgle histograms, they are contained in
the ratio plots
* taken out previous ratio plotting and replace by more modular approach
TODO:
* Add for 3D
* write to summary ROOT file so that we can eventually extract
critical histograms when desired
* update labels shown in ratio plots
If only non-critical test failed, show "COMPATIBLE" label in ratio
plots.
If at least one critical test failed, show "BAD"
(before that was overwritten by each proceeding test such that it
could show compatoble even though an earlier critical test failed)
* resolve memory issues
many mem problems, in particular from previous plotting. Most of the
resolved by simply moving to new plotting;
others were fixed

Fixes and some changes

---

DATA/production/qc-async/tpc.json
DATA/production/qc-sync/tpc.json
MC/config/QC/json/tpc-qc-standard-direct.json

With the most recent updates to the **Tracks** and **PID** tasks in TPC QC, it is now possible (needed) to specify cuts on variables from the JSON file. Added the required task Parameters in the **MC, sync, and async TPC QC**.

TPC: Updating cut parameters in TPC QC JSONs

---

DATA/production/qc-workflow.sh

The full QC configuration is selected when the MCH_RECO is enabled, otherwise the minimal QC configuration for raw data decoding is chosen.

MCH: select QC config based on presence of RECO processing step

---

RelVal/README.md
RelVal/o2dpg_release_validation.py

* use flags --with-test-<test> and remove the need to know the correct
value of the bit mask --> replaces --test|-t option
* add relative path of where single histograms are stored to JSON
summary and influxDB file
* pipe RelVal macro verbosity to log file to focus on cerntral status
messages
* do not compare branches that cannot be compared
* add simple pie charts for each compared file pair per test showing the
fraction of test results
* udpate README accordingly wrt flags (see above) and explain plots that
are created

Update code and README

---

DATA/production/calib/mch-badchannel-aggregator.sh

It allows to define via environment variables the maximum acceptable pedestal and noise values, as well as the minimum statistics required to process the data and send the output to the CCDB.
The default maximum pedestal value is also changed to 500 to reflect the settings in the command-line tools.

MCH: make calibrator parameters configurable via environment variables

---

DATA/common/setenv_calib.sh

Now that the option is available in O2 we should enable it by default always

Enable TPC residual track data sending

---

RelVal/README.md
RelVal/ReleaseValidation.C
RelVal/o2dpg_release_validation.py

ReleaseValidation.C
* restructure JSON output and add more fields such as used threshold and
computed metric value per test and per histogram
* add reading of custom thresholds per histogram and per test
* only check once if comparable
* con-comparable (for all tests) if
* at least one histogram is empty
* different axis/binning
* integral yields inf or nan
* negative bin counts
o2dpg_release_validation.py
* add functionality to make histogram from log file content
(e.g. used to extract number of TPC clusters from tpcreco.log)
* unifiy JSON output of overall summary including QC, MC kine etc. and
single output from ROOT macro
* add summary plots comparing metric values and threshold per test and
histogram
* add option --use-values-as-thresholds to inject previously computed
matric values …

RelVal major update

---

DATA/production/qc-sync/mft.json
DATA/production/qc-sync/mft_track.json

Adding the cluster patterns also to the mft.json file in the sync folder to fix the issue with the fst check here: https://github.com/AliceO2Group/QualityControl/pull/1359 because it was missed in the previous PR: https://github.com/AliceO2Group/O2DPG/pull/551

MFT: Fix a mistake in the mft sync json.

---

DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh

Needs https://github.com/AliceO2Group/AliceO2/pull/9586
@shahor02 , @davidrohr 
ctf reader then becomes e.g.:
```
o2-ctf-reader-workflow --session default_835747_6385 --severity info --shm-segment-id 0 --shm-segment-size 16000000000  --resources-monitoring 50 --resources-monitor
ing-dump-interval 50 --early-forward-policy noraw --fairmq-rate-logging 0 --timeframes-rate-limit 1 --timeframes-rate-limit-ipcid 0 --delay 8 --loop 0  --ctf-input l
ist.list   --onlyDet ITS,TPC,TOF,FV0,FT0,FDD,MID,MFT,MCH,TRD,EMC,PHS,CPV --pipeline tpc-entropy-decoder:1  --allow-missing-detectors  --its-digits --mft-digits --con
figKeyValues "NameConf.mDirGeom=/home/zampolli/work/O2/PilotBeamMay22/LHC22f;NameConf.mDirMatLUT=/home/zampolli/work/O2/PilotBeamMay22/LHC22f;NameConf.mDirCollContex …
```

Special settings valid from run 521889, using digits for ITS and MFT

---

MC/config/QC/json/qc-mft-cluster.json

Fix issue with MC nightly productions crashing due to the MFT clusters patterns query missing in the json file.

MFT: Add cluster patterns to MC json.

---

MC/bin/o2_dpg_workflow_runner.py
MC/bin/o2dpg_sim_workflow.py

Can now specify in the workflow json which tasks
merit a "retry". This is useful for tasks that suffer
from random (e.g., race condition) failures. Retrying such
tasks might save compute resources, which would otherwise
be lost when leading to a complete exit of the workflow.
The feature complements the global option "--retry-on-failure"
in the workflow runner.
For the moment using the feature for TPC clusterization
until https://alice.its.cern.ch/jira/browse/O2-3069 is fixed.

Introduce retry_count as a task property

---

MC/bin/o2dpg_sim_workflow_anchored.py

it seems to be 'runNumber' and not 'run_number' (like sometime in the past)

adjust GRPECS meta-field for run number

---

DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh

In async reco, this will produce:
```
o2-tpcits-match-workflow --session default_1781296_1476 --severity info --shm-segment-id 0 --shm-segment-size 16000000000  --resources-monitoring 50 --resources-monitoring-dump-interval 50 --early-forward-policy noraw --fairmq-rate
-logging 0 --timeframes-rate-limit 1 --timeframes-rate-limit-ipcid 0 --disable-root-input  --disable-mc  --pipeline itstpc-track-matcher:1 **--use-ft0** --configKeyValues "NameConf.mDirGeom=/home/zampolli/work/O2/PilotBeamMay22/LHC22f;
NameConf.mDirMatLUT=/home/zampolli/work/O2/PilotBeamMay22/LHC22f;NameConf.mDirCollContext=/home/zampolli/work/O2/PilotBeamMay22/LHC22f;NameConf.mDirGRP=/home/zampolli/work/O2/PilotBeamMay22/LHC22f;keyval.input_dir=/home/zampolli/wo
rk/O2/PilotBeamMay22/LHC22f;keyval.output_dir=/dev/null;;TPCGa …
```

enabling TPC-ITS AfterBurner

---

DATA/production/qc-workflow.sh

Needed for FST on EPNs to use localhost:8084.
Trivial, merging

Add option to override CCDB server used by QC tasks

---

DATA/tools/parse

While DDS does individual slurm submissions, this should ensure that the calib nodes are filled in a better way and large workflows are not submitted last.

Workflow parser: sort calib workflows according to required CPU cores in descending order

---

DATA/production/configurations/2022/LHC22f/apass1/getTPCvdrift.C

@shahor02 : this should followed our discussion from yesterday. Please, check that it is indeed what you meant.

vdrift correction should be wrt refVDrift, when different from 0

---

MC/bin/o2_dpg_workflow_runner.py
MC/utils/o2dpg_sim_metrics.py

Central to this PR
* o2dpg_sim_metrics.py resources
produces a resource estimate for mem and CPU based on previously
derived metrics from one or more runs
--take argument can be used to define to take
* average
* min
* max
in case multiple metric JSONs are passed. The estimates are written to
a JSON again
Treat every TF the same so the estimate file only contains
"task_name": {
"mem": <memory>,
"cpu": <cpu>
}
without TF suffix
* o2_dpg_workflow_runner --update-resources
takes a JSON produced by previous resource estimation and updates the
resources on the fly
Due to above comment, all TFs get the same resource estimate
Other
some consolidation and help for argparse

Inject estimated resources into WF runner

---

DATA/common/setenv.sh
DATA/production/qc-workflow.sh

@aferrero2707 this will avoid crashing the MCH track QC when MID is not in the run. 
Tested at Pt2 (e.g. run 524404) with `mch-laurent-cosmics` ECS configuration (based on COSMIC one)

MCH QC : only activate MCH-MID track QC if MID is there

---

MC/bin/o2_dpg_workflow_runner.py
MC/bin/o2dpg_sim_workflow.py
MC/bin/o2dpg_workflow_utils.py

The graph pipeline runner can apply a specific
alienv/CVFMS software version on an individual task level.
This allows to mix multiple software versions during execution, which
is actually a benefit of the multi-process (microservice) approach.
Software packages can be defined in the workflow json under
the tag "alternative_alienv_package" as part of a task specification.
The new feature is for now (optionally) applied in the O2DPG MC workflow creation,
to all tasks that are RECO (or further) in the processing. This can be enabled
via the new "--alternative-reco-software" option.

New feature: Task-level software environments

---

DATA/production/qc-workflow.sh

This is to disentangle the jsons for flp and epn loaded from consul otherwise we didn't find any way to avoid conflicts (epn needs the possibility to adjust TOF matching QC setting independently of FLPs: with TRD w/o TRD)
At the moment we just cloned flp json (already done) so the situation is not yet changed wrt before (we just disentagled the two jsons).
Once this PR is available in EPNs we can run a test with synthetic runs.
@njacazio @ercolessi

disentangle jsons for flp and epn to avoid conflict in TOF matching QC

---

DATA/common/getCommonArgs.sh

The `o2sim_geometry-aligned.root` and `o2sim_grp.root` files are still required for some QC tasks...

Drop paths for madbud and coll.context from ARGS_ALL_CONFIG

---

RelVal/README.md
RelVal/ReleaseValidation.C
RelVal/config/rel_val_sim_dirs_default.json
RelVal/o2dpg_release_validation.py

* all file exploration, understanding and extraction happens now in
ReleasveValidation.C instead of having any additional preparation
steps in the Python script
* ROOT macro takes now 2 lists (comma-separated strings) of input files
instead of only one file per version. This enables more complex
comparisons and more generic comparisons in particular for TTrees
* more flexible configuration when comparing 2 directories
* o2dpg_release_validation.py --dirs-config <config.json>
==> see RelVal/config/rel_val_sim_dirs_default.json
* use --dirs-config-enable(--dirs-config-disable) <topKeys> to
enable(disable) specific top keys to be taken into account for
validation
* fix when passing 2 files to python wrapper

Move heavy lifting to macro, small fix

---

DATA/common/setenv_calib.sh

@davidrohr : this is just to set if we run the IDCs on both sides together or not from the setenv_calib. I put it here to be consistent with the rest: each calibration is on or off in this script.

to set the possibility to use one node for TPC IDCs

---

RelVal/ExtractAndFlatten.C
RelVal/ReleaseValidation.C
RelVal/config/rel_val_sim_dirs_default.json
RelVal/o2dpg_release_validation.py

* separate extraction of objects from RelVal --> now there are 2 macros
* extraction: ExtractAndFlatten.C Producing what was previously "newfile1.root"/"newfile2.root". These contain the objects to be compared.
* RelVal: ReleaseValidation.C This does the actual validation based on the extracted objects.
This allows to extract any number of files an merge them together in
one single file before comparsion.
(That was previously not possible since very long cmd lines could not
be processed by ROOT)
In addition it is now possible to have a baseline file of objects to
compare to without the need of extracting the baseline over and over
again.

Macro updates

---

DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh

Hi @chiarazampolli,
Merged task of AnalysisQC was removed while ago from O2DPG, thus we need to remove it from production script.
Thanks!
Yours,
Catalin.

Removed AnalysisQC merged task

---

DATA/production/qc-async/emc.json

Once the recalibrator will be included cells will be
available on 2 supsecifications: 1 - uncalibrated, 0 -
calibrated. Only calibrated cells must be monitored
by the cell-level QC during the asynchronous stage.

[EMCAL-756] Async QC at cell level must use subspec 0

---

DATA/common/setenv_calib.sh

@shahor02 and @chiarazampolli could we not simply change the check here so that we cannot have an inconsistent configuration?

Adjust check if ZDC calib is possible

---

RelVal/ExtractAndFlatten.C
RelVal/ReleaseValidation.C

small changes in ExtractAndFlatten.C and ReleaseValidation.C to detect if dealing with an efficiency plot in the NEntries test and make it critical in that case.

make NEntries test critical when dealing with TEfficiency

---

DATA/production/qc-sync/zdc.json
DATA/production/qc-workflow.sh

As discussed with Ole, we created the PR to implement the ZDC QC on EPN
!!Important: we did not yet modify the url and conditionDB in the .json file, please have a look

Added of ZDC EPN QC

---

DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
DATA/production/configurations/2022/LHC22f/apass1_TPCcalib/setenv_extra.sh
DATA/production/configurations/2022/MayJunePilotBeam/apass1/setenv_extra.sh

All past TOF data now calibrated, --for-calib no longer needed.
To be added only in sync reco/calib

tof reco: remove --for-calib option

---

MC/config/PWGDQ/external/generator/GeneratorBeautyToJpsi_EvtGen.C
MC/config/PWGDQ/external/generator/GeneratorBplusToJpsiKaon_EvtGen.C

Random:seed = 0 assign a random seed to pythia using Stdlib time(0). If the two timeframes are created in less than a second, they share the same seed. To avoid this, the random seed is now given by urandom.

Prevent two timeframes from having the same seed

---

RelVal/ReleaseValidation.C
RelVal/o2dpg_release_validation.py

* no longer necessary to run full RelVal if only thresholds are changed ==> makes threshold scan faster and more straightforward
* remove all unused functionality from ROOT macros
* align some functionality in Python script
* allow same threshold args for both rel-val and inspect command

Move value-threshold comparison to python

---

MC/config/analysis_testing/json/analysis-testing-mc.json

Makes the task fail because there seem to be values <0 which causes a FATAL.

Avoid log pT plot

---

MC/bin/o2_dpg_workflow_runner.py

tmprly done in the scheduler before we provide
this as a workflow property

force use of ALICEO2_CCDB_LOCALCACHE

---

DATA/production/configurations/2021/ctf_recreation/ctf_recreation.sh
DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh

@catalinristea , this is what we discussed. 
@catalinristea , @davidrohr , @shahor02 : I also added the possibility to use the same script for starting the reco from TFs, depending again on an ALIEN variable:
```
+if [[ -n $ALIEN_INPUT_TYPE ]] && [[ "$ALIEN_INPUT_TYPE" == "TFs" ]]; then
+  unset WORKFLOW_PARAMETER
+  export WORKFLOW_PARAMETERS=CTF
+  INPUT_TYPE=TF
+  export TPC_CONVERT_LINKZS_TO_RAW=1
+else
+  INPUT_TYPE=CTF
+fi
...
-env $SETTING_ROOT_OUTPUT IS_SIMULATED_DATA=0 WORKFLOWMODE=print TFDELAY=$TFDELAYSECONDS NTIMEFRAMES=-1 ./run-workflow-on-inputlist.sh CTF list.list > workflowconfig.log
+env $SETTING_ROOT_OUTPUT IS_SIMULATED_DATA=0 WORKFLOWMODE=print TFDELAY=$TFDELAYSECONDS NTIMEFRAMES=-1 ./run-workflow-on-inputlist.sh $INPUT_TYPE list.list > workflowconfig.log
-env …
```

Making script flexible to run on non-EPN or EPN GRID env, and on TFs

---

DATA/production/qc-sync/qc-global-epn.json

This reverts commit 8e5c89e701ccce473e35ff5d99d1c8707e8bb0c4.
Still produces excessive log files

Revert "Reenable logging for QC log files"

---

DATA/production/qc-sync/glo-itstpc-mtch-qcmn-epn.json
DATA/production/qc-sync/glo-qcmn-epn.json
DATA/production/qc-sync/glo-vtx-qcmn-epn.json
DATA/production/qc-workflow.sh

@knopers8 
I left untouched what we do in async. 
I tried in SYNC mode, which behaves like EPN, but taking the files from O2DPG instead of consul. I only built the json, and for me it looks fine. 
The only drawback is that in the json the tasks will always look active, it is just the argument passed to o2-qc that disables them, e.g.:
```
o2-qc --session default_3884606_24780 --severity info --shm-segment-id 0 --shm-segment-size 16000000000  --resources-monitoring 50 --resources-monitor
ing-dump-interval 50 --early-forward-policy noraw --fairmq-rate-logging 0 --timeframes-rate-limit 1 --timeframes-rate-limit-ipcid 0 --config json:///a
rchive/O2/testQCconfig/json_cache/20220921-222315-3884617-11198--ITS-GLO.json --local-batch=QC.root --override-values "qc.config.Activity.number=52314 …
```

Adding GLO QC for EPN and SYNC mode

---

MC/config/PWGDQ/external/generator/GeneratorCocktail.C

The mother/daughter track IDs get messed up when the list of particles from different generators in the vector of generators of the cocktail are joined at importParticles(). Should be shifted according to the position in new (full) list of particles. Please check if this makes sense.

fixed mother/daughter track IDs when joining  lists of particles

---

DATA/common/setenv.sh
DATA/production/qc-workflow.sh

@chiarazampolli @knopers8 : QC tasks should not be added solely by the presense of the detector, but only if requested in the list of QC tasks. Note that the default list of QC tasks is the list available detectors + $LIST_OF_GLORECO.

Fixes for qc-workflow.sh

---

DATA/production/qc-async/tpc.json

The sampling fraction can be set in line 105. For now, I put 10% that goes through.

TPC: add data sampling to Cluster task

---

DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh

Hi @noferini, @chiarazampolli
Here is the commit to add  CTP to the list of detectors for async reco.
Please review and merge if you find it appropriate.
Mail from Evgeny,
_I am trying to understand what is going on with ctp info in Run3 AO2Ds. According to Roman, ctp readout is available for all runs taken after 24/09/22 16:24 and the ctp reco workflow was ready before that. AO2D producer seems to support CTP info as well. However, I still see zeros in the trigger mask stored in AO2Ds that is supposed to be filled from CTP digits. It seems the reason is that o2-ctp-reco-workflow is not yet included in the reconstruction chain._
Follow-up from Francesco,
_I checked in the dpl-workflow.sh and it seems that the option is already there.
I guess it should be enough to add CTP to the detector …

Add CTP in production

---

RelVal/o2dpg_release_validation.py

I added the include_patterns argument and the regex comparison also in `plot_pie_charts` and `plot_values_threshold`, only then noticed that including it in `make_single_summary` already does the full job (at least for "inspect"). For the moment I left it also in the other function, but with default value None. Should I take it out again?

regex for --include-patterns in inspect command

---

DATA/README.md
DATA/testing/detectors/FDD/run_fdd_ctf.sh
DATA/testing/detectors/FDD/run_fdd_digits_ctf.sh
DATA/testing/detectors/FDD/run_fdd_digits_qc_ctf.sh
DATA/testing/detectors/FT0/run_ft0_ctf.sh
DATA/testing/detectors/FT0/run_ft0_digits_ctf.sh
DATA/testing/detectors/FT0/run_ft0_digits_qc_ctf.sh
DATA/testing/detectors/FV0/run_fv0_ctf.sh
DATA/testing/detectors/FV0/run_fv0_digits_ctf.sh
DATA/testing/detectors/FV0/run_fv0_digits_qc_ctf.sh
DATA/testing/private/afurs/run_fdd_ft0_fv0_ctf.sh
DATA/testing/private/afurs/run_fdd_ft0_fv0_digits_qc_ctf.sh
DATA/testing/private/afurs/run_ft0_fv0_ctf.sh
DATA/testing/private/afurs/run_ft0_fv0_digits_qc_ctf.sh
DATA/testing/private/shahoian/runTF_PB.sh
DATA/testing/private/shahoian/runTF_ext_dpl.sh
DATA/testing/private/shahoian/run_PB.sh
DATA/testing/private/shahoian/run_ext.sh
DATA/testing/private/shahoian/run_ext_dpl.sh
DATA/testing/private/shahoian/run_test.sh
DATA/testing/private/zampolli/runTF_ext_dpl.sh
DATA/testing/private/zampolli/run_ext_dpl.sh

So don't mention it in the README anymore and remove it from all workflows where it was set

GEN_TOPO_IGNORE_ERROR does not exist anymore

---

MC/config/PWGDQ/external/generator/GeneratorBeautyToJpsi_EvtGen.C
MC/config/PWGDQ/external/generator/GeneratorBeautyToMu_EvtGen.C
MC/config/PWGDQ/external/generator/GeneratorBeautyToPsi_EvtGen.C
MC/config/PWGDQ/external/generator/GeneratorCharmToMu_EvtGen.C

Prevent two timeframes from having the same seed using urandom instead of the pythia random seed method

Prevent two timeframes from having the same seed 

---

DATA/common/setenv_calib.sh

I tested only with local aggregator and there it was fine. Now with the proxy the CTP/DIGITS input is missing which is required when using the RecoContainer logic for loading the CTP input:
https://github.com/AliceO2Group/AliceO2/blob/7a344162ae2735fa5f436bb48248b588e3e861b5/DataFormats/Detectors/GlobalTracking/src/RecoContainer.cxx#L403-L412

Send CTP digits required by RecoContainer logic

---

MC/bin/o2dpg_sim_workflow.py

QC does not have this argument. Seen on alibi nightlies:
```
[ERROR] error parsing options of o2-qc: unrecognised option '--condition-not-after'
```

Do not use --condition-not-after for QC

---

MC/bin/o2_dpg_workflow_runner.py
MC/bin/o2dpg_sim_workflow.py

This introduces the possibility (using argument --pregenCollContext) to generate the collision/timeframe structure **before** the signal transport simulation, instead of the other way around.
This makes sure that, in particular for low interaction rates, a dynamic number of events per timeframe can be simulated.
I assume this mode will become the standard at some point.
Note that the scheme does not yet work with embedding.
Also applying a new limit to constrain TPC digits to within the timeframe limits (to prevent crashes in TPC clusterization).

Option to use pregenerated collision context in simulation

---

RelVal/ExtractAndFlatten.C
RelVal/o2dpg_release_validation.py

- removed `--print` option from `inspect` command
- removed empty plot test_values_thresholds_summary.png
- implemented merging of trees from different DF_\<number>  subdirectories in AO2D files at the histogram level (instead of first merging the trees and then writing it to a histogram)
-  advantage: Merging many trees from many DF directories can become very large. Writing each tree immediately to a histogram and then adding only the histograms avoids this problem.
- disadvantage: The first DF directory sets the binning and the histogram range for all following trees. Most physical distributions should be very similar in the different DFs, so it should not be a problem. But e.g. for IndexTables this can for sure cut away some parts of later trees, but I think it is anyhow questionable …

merging TTrees form AO2D files

---

DATA/production/qc-async/itstpctofwtrd.json
DATA/production/qc-async/pidft0tofwtrd.json
DATA/production/qc-workflow.sh

This is to use TRD tracks in TOF matching and PID QC (when available).
@ercolessi @njacazio

fix tof qc jsons to include TRD when available

---

RelVal/ReleaseValidation.C
RelVal/o2dpg_release_validation.py

- new `print` subcommand
- filters with `--include-patterns`, `--exclude-patterns`, `--flags` and `--flags-summary`
- for the moment prints only names of histograms to screen. More information could be added
- new `--flags-summary` filter also for `inspect` subcommand
- now uses all filters also for plotting test_values_thresholds_{TESTNAME}.png  (missing before) and pie charts (probably anyhow not useful when using filter on flags)
- switched to ROOT's Kolmogorov test instead of bin_cont test
- for the moment uses the probability that ROOT returns as a metric. Could also use directly the Kolmogorov distance?
- still have to find reasonable value for default threshold for the Kolmogorov test

print subcommand and Kolmogorov

---

DATA/common/setenv_calib.sh
DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh

This is to have the possibility to run some calib at async stage. 
I use setenv_calib.sh in conjunction with calib-workflow.sh (in O2, PR being opened) to be allowed to use all the wrokflow-setup etc functionalities. 
I took this PR to also include the switch to attach the residual extraction, which is in the apass1_TPCcalib
@davidrohr : this touches the scripts used also in sync processing, so could you please check?
Pinging also:
@mfasDa 
@ehellbar 
@wiechula 
@catalinristea

Adding possibility to re-run EMC calib and TPC residual extraction

---

MC/bin/o2dpg_sim_workflow.py
MC/config/QC/json/tofdigits.json

This is to introduce a delay of 3 s  in TOF digit reader since majority of QC digit are empty in the last MC production (digit reader too fast wrt QC init)

add delay in tof digit reader

---

GRID/utils/jdl_to_script.py

This introduces a small tool that can take a JDL or an ALIEN process id and produce a local script
that mimics/reproduces the ALIEN job on the local machine.
Output is a local shell script which can be run.
For now, the local script takes care of the following:
a) software setup
b) download of all necessary input files
c) launching the executable
Example:
./jdl_to_script.py --from-proc-id 2756275277 -o local_script.sh

Add local JDL runner script

---

DATA/tools/epn/gen_topo.sh

Not to be merged yet!
Only after O2 on the EPNs is updated to include https://github.com/AliceO2Group/AliceO2/pull/10347 and no more older O2 versions are used in production then this should be merged and used on the EPNs.

Remove duplicate CTF_METAFILES_DIR

---

DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
DATA/production/configurations/2022/LHC22f/apass1_TPCcalib/setenv_extra.sh

The `export CALIB_TPC_SCDCALIB_SENDTRKDATA=1 ` is already enabled in the scripts. The full output type is needed now, since its not the default anymore.

Async.: Enable full output of residual aggregator

---

DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh

also, suppress ZDC shifts for LHC22s runs w/o ZDC (in fact, the values were not correct, missed +1 BC)

Add zdc bc shift for 529038

---

DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh

- Reduce number of cluster bins used for track-finding optimization. This increases MFT acceptance with a slight increase in reconstruction CPU cost.
- Remove obsolete configurations (which are defaults and should not change any more)

Update MFTTracking param on setenv_extra.sh

---

MC/config/PWGDQ/external/generator/GeneratorBeautyToJpsi_EvtGen.C
MC/config/PWGDQ/external/generator/GeneratorBeautyToMu_EvtGen.C
MC/config/PWGDQ/external/generator/GeneratorBeautyToPsi_EvtGen.C
MC/config/PWGDQ/external/generator/GeneratorBplusToJpsiKaon_EvtGen.C
MC/config/PWGDQ/external/generator/GeneratorCharmToMu_EvtGen.C
MC/config/PWGDQ/pythia8/decayer/switchOffBhadrons.cfg
MC/config/PWGDQ/pythia8/decayer/switchOffBplus.cfg
MC/config/PWGDQ/pythia8/decayer/switchOffChadrons.cfg

These changes should fix the issue spotted by Giacomo in the JIRA ticket here: https://alice.its.cern.ch/jira/browse/O2-2794 
b-hadron decays were not properly switched off in pythia8, so they were decayed twice (first by Pythia "naturally", then by EvtGen in the forced decay modes). The issue also affects non-prompt jpsi barrel+muons (JIRA O2-2793 and O2-2792) and c,b -> muons (JIRA O2-3022) productions, so the proposed changes should fix all of them.

switch off hf-hadron decays in pythia8

---

DATA/production/qc-async/qc-global.json
DATA/production/qc-postproc-async/emc.json
DATA/production/qc-postproc-async/example.json
MC/config/QC/json/ITSTPCmatchedTracks_direct_MC.json
MC/config/QC/json/emc-cell-task.json
MC/config/QC/json/ft0-reconstruction-config.json
MC/config/QC/json/its-clusters-tracks-qc.json
MC/config/QC/json/its-mc-tracks-qc.json
MC/config/QC/json/pidft0tof.json
MC/config/QC/json/pidft0tofNoTRD.json
MC/config/QC/json/pidtof.json
MC/config/QC/json/pidtofNoTRD.json
MC/config/QC/json/qc-mft-async.json
MC/config/QC/json/qc-mft-cluster.json
MC/config/QC/json/qc-mft-digit-0.json
MC/config/QC/json/qc-mft-digit-1.json
MC/config/QC/json/qc-mft-digit-2.json
MC/config/QC/json/qc-mft-digit-3.json
MC/config/QC/json/qc-mft-digit-4.json
MC/config/QC/json/tof-trending-hits.json
MC/config/QC/json/tofMatchedTracks_AllTypes_direct_MC.json
MC/config/QC/json/tofMatchedTracks_ITSTPCTOF_TPCTOF_direct_MC.json
MC/config/QC/json/tofdigits.json
MC/config/QC/json/tpc-qc-standard-direct.json
MC/config/QC/json/tpc-qc-tracking-direct.json
MC/config/QC/json/trd-digits-task.json
MC/config/QC/json/vertexing-qc-direct-mc.json

It disables dumping QC monitoring metrics to stdout and it increases level and severity threshold for some tasks.

[QC-917] Less logs produced by QC

---

DATA/production/qc-postproc-async/emc.json

With the concerned value set to `true`, we save a new plot to QCDB for each new point in the plots (each `update` trigger). It is completely enough if we upload the plots only at `finalize`. cc @mfasDa

Do not produce plots on each update in EMC QC postprocessing

---

DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh

The TOF matching to ITS-TPC before was done with 30 sigma track time error window which is an overkill. Now it is changed to 4 sigma (configurable) but due to ITS-TPC time shift we may lost some matches. The effect is especially stronge with the new alignment and reducer ITS syst error which leads to smaller nominal time error. To account for that, we extend the TPCITSTIMERROR (used so far only in pbpb) to pp (but with 0.2 mus instead of 0.3). Also the PVertexing profits from this extra error.

Add extra TPCITSTIMEERR=0.2 mus in ALIGNLEVEL=1 mode

---

DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh

In order to disable the track selection for the residual extraction.
To be enabled for the reprocessing of low interaction rate runs: https://alice.its.cern.ch/jira/browse/O2-3512
And I am trying them as well for some 500kHz runs to see if we can enable them there as well.
@chiarazampolli would it work like this so that we can ask Catalin to export `ALIEN_JDL_DEBUGRESIDUALEXTRACTION=1` in the jdl? Or how should I add these custom options?

TPC residual extraction for debugging purposes

---

MC/run/ANCHOR/2021/OCT/pass4/anchorMC.sh
MC/run/ANCHOR/2022/JUN/pass1/anchorMC.sh

Option now already present by default, cannot be set twice

Use --TPCuseCCDB only once

---

DATA/production/qc-async/mch-digits.json
DATA/production/qc-async/mch-reco.json
DATA/production/qc-async/mch-tracks.json
DATA/production/qc-workflow.sh

This PR introduces the long overdue async part of the QC for MCH.
Note that I've moved the `add_QC_JSON` up in the `qc-workflow.sh` script in order to be able to use it in the async part to construct the MCH part from parts.
@aferrero2707 FYI

MCH: add async qc

---

MC/config/PWGEM/external/generator/GeneratorBeautyToEle_EvtGen.C
MC/config/PWGEM/external/generator/GeneratorCharmToEle_EvtGen.C
MC/config/PWGEM/ini/GeneratorHF_bbbarToDielectrons.ini
MC/config/PWGEM/ini/GeneratorHF_ccbarToDielectrons.ini
MC/config/common/pythia8/generator/pythia8_bbbar.cfg
MC/config/common/pythia8/generator/pythia8_pp_cr2.cfg

Dear all, 
this pull request is meant for the preparation of enhanced dielectrons MC from correlated heavy-flavour hadron decays. 
For charms, we would prefer to use inelastic pythia 8 with the colour reconnection mode 2, since it reproduced better the amount of baryons, relevant for DCAee templates.
For beauty, to save CPU, we would switch on only the bbbar process. If this is a problem, we can go back to the already existing pythia8 configuration for hf (both ccbar and bbbar) cfg.
We are opened to any comments....
Best regards,
Raphaelle

hftodielectronsMCconfiguration

---

DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh

Following PR [#10665](https://github.com/AliceO2Group/AliceO2/pull/10665), since the memory issue in O2 should be fixed now, the new default configuration for the MFT track finder can be updated here.

[MFT] Add new default settings for MFT track finder

---

DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
DATA/production/configurations/asyncCalib/createCorrectionMap.sh

Don't merge yet please!
In principle this should be all that is needed to skip writing the binned residuals and create the map directly from the unbinned ones. 
It requires https://github.com/AliceO2Group/AliceO2/pull/10736 to be merged first and I am not sure if the run number is known from `ALIEN_JDL_LPMRUNNUMBER` which I just assumed?

TPC SCD correction from unbinned residuals

---

DATA/production/qc-workflow.sh

@martenole : This will require current O2/dev, so we must not bump O2DPG afterwards without also bumping O2 on the EPNs.

qc workflow: remove compatibility with old O2

---

DATA/production/qc-async/mch-tracks.json

Following QC PR https://github.com/AliceO2Group/QualityControl/pull/1608
the reading of the geometry is now done using the GrpGeomHelper and
thus the JSON configuration must reflect that.

MCH: update qc-async mch-tracks.json

---

MC/bin/o2_dpg_workflow_runner.py
MC/bin/o2dpg_sim_workflow.py
MC/bin/o2dpg_workflow_utils.py
MC/doc/WorkflowRunner.md

Introducing a mechanism allowing to define
global environment variable that should be used in all tasks of a MC workflow.
This is done by defining a special task '__global_init_task__' which is parsed by the runtime engine. This task will not do anything else than defining environment variables for the moment.

Global init section for MC graph workflows

---

MC/bin/tests/embedding_test.sh
test/common/kine_tests/test_generic_kine.C
test/common/utils/utils.sh
test/run_generator_tests.sh
test/run_workflow_tests.sh

* general
* outsource some common functionality
* add workflow test script
* generator testing
* remove Pythia8 (was placeholder until now) for OmegaC but keep test for external
* small fixes
* workflow testing test/run_workflow_tests.sh
* test all workflow creations found in MC/run/*/*.sh
* extract lines up to including o2dpg_sim_workflow.py and run that
* do not test if there is any "exit" which might indicate an additional user condition which is at the moment not easy to understand automatically. --> needs refinement
* failing PWG-related tests are for now treated as warnings
* additional test in MC/bin/tests which is required to pass

Update and extend testing

---

DATA/production/configurations/CTFSkimming/ctf-skim-workflow.sh
DATA/production/ctf-skim-workflow.sh

Format: ctf-skim-workflow.sh -f <IRFramesFile> -c <CTFsList>
where IRFramesFile is the output of IRFrame selection workflow (tree or vector format) CTFsList: CTF (as a textfile or comma-separated list) fully covered by IRFramesFile
For the record: with the test IRFrame selection provided by @mpuccio the skimmed CTF yield is 10% of the original.

Prototype of the the CTF skimming workflow

---

RelVal/o2dpg_release_validation.py

* one entry/line per ROOT file and histogram
* do not push null/None entries at all, parsing does not work and they would anyway be stripped
* make everything a tag that is a tag and not push it as a value

[RelVal] Do not put None values to influx at all

---

DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh

Hello @chiarazampolli ,
Since the PbPb apass5 will be done with a recent O2 version (if I understood correctly), it can use the default reconstruction parameters, which have been updated recently (#10927).

use default MCH parameters for PbPb

---

MC/bin/o2dpg_sim_config.py

For the moment I will disable the softening of the cut on `nContributors` implemented in https://github.com/AliceO2Group/AliceO2/pull/10568 for PbPb. This is done by constraining the XY distance of low mult vertices to be `0.f`.
This should restore former behaviour (pre-19 Frebruary 2023)

[O2-3636] Disable low-multiplicity seeds in PbPb

---

MC/bin/o2dpg_sim_config.py

Fixing an error message "Error in setValue (string) bad lexical cast: source type value could not be interpreted as target" seen in PbPb MC jobs. Most likely the cut setting was then ignored and did not have the targeted effect.

ITSreco: Do not use 0.f in config values - just 0.

---

DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh
DATA/production/qc-async/its.json
DATA/production/qc-async/itstpc.json
DATA/production/qc-async/itstpctof.json
DATA/production/qc-async/itstpctofwtrd.json
DATA/production/qc-async/mft.json
DATA/production/qc-async/pidft0tof.json
DATA/production/qc-async/pidft0tofwtrd.json
DATA/production/qc-async/pidtof.json
DATA/production/qc-async/tof.json
DATA/production/qc-sync/glo-itstpc-mtch-qcmn-epn.json
DATA/production/qc-sync/its.json
DATA/production/qc-sync/itstpctof.json
DATA/production/qc-sync/itstpctrdtof.json
DATA/production/qc-sync/mft-full-no-tracks.json
DATA/production/qc-sync/mft-full.json
DATA/production/qc-sync/tof.json
MC/config/QC/json/ITSTPCmatchedTracks_direct_MC.json
MC/config/QC/json/its-clusters-tracks-qc.json
MC/config/QC/json/mft-clusters.json
MC/config/QC/json/pidft0tof.json
MC/config/QC/json/pidft0tofNoTRD.json
MC/config/QC/json/pidtof.json
MC/config/QC/json/pidtofNoTRD.json
MC/config/QC/json/tofMatchedTracks_AllTypes_direct_MC.json
MC/config/QC/json/tofMatchedTracks_ITSTPCTOF_TPCTOF_direct_MC.json
MC/config/QC/json/tofdigits.json

@knopers8 , @shahor02 , goes with 
https://github.com/AliceO2Group/AliceO2/pull/11044
https://github.com/AliceO2Group/QualityControl/pull/1692

Do not get B field from external file anymore, but from CCDB - O2DPG

---

DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh

@chiarazampolli : This supports other file list files with `.list` extension, also from other folders, as argument.
Was kind of convenient for me for testing.
Another comment is: shouldn't we move async_pass.sh to a proper directory, not inside `2022/LHC22f/apass1`, since now I think we use this script for everything.

Async pass: Support list input not as list.list from current folder

---

DATA/production/common/getStat.sh
DATA/production/configurations/2022/LHC22f/apass1/async_pass.sh

@costing @catalinristea 
This will produce an empty file named as follows:
${nCTFsFilesInspected}_${nCTFsFilesOK}_${nCTFsProcessed}_${PVs}_$1_stat.txt
where:
nCTFsFilesInspected = number of CTFs files for which "alien_cp" was called; this is 0 in case a local file(s) is (are) used;
nCTFsFilesOK = number of CTFs files that were successfully processed
nCTFsProcessed = number of single CTFs that were processed (not files, but CTFs!)
PVs = number of reconstructed prim vertices (can be interesting also for @shahor02 )
$1 = argument passed: it is the log file that is parsed to obtain the above. We need it since in case the wf is split, CTFs are read 2x, so I cannot use stdout. 
E.g., from a local test:
0_1_4_27792_latest_reco_1.log_stat.txt
I use these numbers also in case of split wf to …

Adding some statistics after processing

---

DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh

@chiarazampolli as discussed, this is a tuning for 22s: I have added a small unbiasing (apparently the static distortions effect) and TPC cov.matrix inflation, 10% of what we had in pp, so it should not affect strongly the resonances mass resolution. 
In principle, the same settings could be applied to 22q in case we want to reprocess it.

Add small unbiasing and TPC cov.mat. tuning for LHC22s

---

DATA/production/qc-async/trditstpc.json
DATA/production/qc-sync/trditstpc.json
DATA/production/qc-workflow.sh

-  qc json that matches with ITS TPC for the pulseheight that matches tracks to digits.
-  qc json that works when ITS or TPC are not there, and of course then excludes the track matching pulseheight.
This still leaves the correct workflow being chosen for the qc workflows.

TRD split the json file for pulseheight tasks that matching and do not match tracks

---

DATA/production/configurations/asyncReco/async_pass.sh

I missed this script which did not exist when I first did the changes. Not a problem, since there still exist the dummy workflow-setup.sh, but it is not needed anymore

workflow-setup is not needed anymore

---

DATA/common/setenv_calib.sh

I tested on prod, not on staging. On staging there is no CTP that's why I did not spot this in my test...

Make variable known for gen topo even if empty

---

DATA/production/qc-async/its.json
DATA/production/qc-sync/its.json
MC/config/QC/json/its-clusters-tracks-qc.json

Added:
- Param "publishDetailedSummary" which allows to publish more detailed hitmaps for qc async only (=1 for qc async) 
- Param "doNorm" equal to 1 which allows to normalize by n vertices --> no change here wrt what done before but behind doNorm there are now different normalization options. 
cc @chiarazampolli

Added params to ITS jsons

---

DATA/production/configurations/asyncReco/setenv_extra.sh

@chiarazampolli : On the EPNs with many TFs in flight, we should not mess with the pipeline length.
I am also not sure whether we need this on the GRID, why did you actually set it in the first place? I assume the memory for the metrics might have been quite high otherwise, but I think we don't use them anyway any more.

async reco: Don't change DPL_PIPELINE_LENGTH on the EPNs, since 1NUMA workflow will be affected

---

DATA/production/qc-async/mft.json
DATA/production/qc-sync/mft-full.json
MC/config/QC/json/mft-tracks.json

Add `clustersrofs:MFT/CLUSTERSROF/0` to query in MFT track task in view of https://github.com/AliceO2Group/QualityControl/pull/1742

MFT: add clustersrofs to query in MFT track task

---

MC/run/PWGEM/runHFToDielectrons_pp.sh

Second try. Sorry, for technical reasons I had to close the previous pull request.

Changes the composition, second try

---

MC/bin/o2dpg_sim_workflow.py
MC/bin/o2dpg_sim_workflow_anchored.py

Anchoring script now determined timestamp for a particular production.
In addition, we need to pass SOR to workflow script since this is still used with HBFUtils.

Improved timestamp determination in anchoring

---

DATA/production/calib/its-noise-aggregator.sh

Hi @shahor02, @mconcas, 
this is a simple modification to the P2 workflow of noise calibration so to have a validity of 2 years for the `NoiseMap` which is pushed to ccdb after a noise calib run. 
As discussed, we don't run a noise calibration very often hence it might well happen that we take data for 6 months with the same list of noisy pixels masked into ITS. In case a new calibration is done and a new object will be pushed to ccdb, you mentioned that the metadata `adjustableEOV = true` will make the proper job in avoiding that the old map (still with a validity of 2 years) will not be considered anymore if a new one appears. 
The modification for the `DeadMap` is instead ongoing in our DCS parser workflow.

Extended validity of noise calib object in ccdb to 2 years

---

DATA/production/configurations/asyncReco/setenv_extra.sh

The TPC calibration rescaling will be applied only if:
```
if [[ -z $ALIEN_JDL_DONOTAPPLYTPCSPDCALIBRATION ]] || [[ $ALIEN_JDL_DONOTAPPLYTPCSPDCALIBRATION != 1 ]]
```
which means that it will be ON by default. In this case, there will also be no TPCCLUSTERSHIFT.
@shahor02 , if you could check this PR, it would be very good.
I took at starting point the setenv_extra_v1.sh script in O2-3701.
One further remark: in the script we set:
```
TPCEXTRAERR=";GPU_rec_tpc.clusterError2AdditionalY=0.1;GPU_rec_tpc.clusterError2AdditionalZ=0.15;"
```
but according to @wiechula , it should have been:
```
TPCEXTRAERR=";GPU_rec_tpc.clusterError2AdditionalY=0.01;GPU_rec_tpc.clusterError2AdditionalZ=0.0225;"
```
i.e. the square of the values. @wiechula said to keep as in the tests done in O2-3701, but we …

Script that allows to use TPC calibration

---

DATA/production/configurations/asyncReco/setenv_extra.sh

@wiechula , @noferini , @shahor02 , @miranov25, @aschmah, as discussed at the meeting today. 
Here the effect of the different additional errors:
TPC tracks:
ITSTPC matched tracks:
Efficiency:
Ratios:
Since the value 0.1 and 0.15 were better QC'ed, it was decided at the meeting today (https://indico.cern.ch/event/1286650/) to keep them instead of those that should have been used (0.01 and 0.0225, i.e. square of 0.1 and 0.15).

Change additiona errors + correct logging

---

DATA/production/qc-async/mch-digits.json
DATA/production/qc-async/mch-errors.json
DATA/production/qc-async/mch-reco.json
DATA/production/qc-async/mch-tracks.json

This is a temporary measure to allow MCH async QC to at least  _not_ crash and produce _some_ histograms that can be used to assess async reco quality.
We still miss the post-processing part though. That will be added in another PR.
@csuire @aferrero2707

MCH: temp fix for QC ASYNC

---

MC/bin/o2dpg_qc_finalization_workflow.py
MC/bin/o2dpg_sim_workflow.py
MC/config/QC/json/its-clusters-tracks-qc.json
MC/config/QC/json/its-mc-tracks-qc.json

Hi @catalinristea and @JianLIUhep this is what discussed via email: add the ITS QC cluster and track to MC productions so that we will be able to check if MC anchoring will be done correctly (cc @chiarazampolli )
I have the following crash when testing the code (run the script `O2DPG_pp_minbias.sh`) on lxplus with the PDPSuite of 25/04 but it does not seem to be related to this code modification:
```
#0  0x00007ff66e822659 in waitpid () from /lib64/libc.so.6
#1  0x00007ff66e79ff62 in do_system () from /lib64/libc.so.6
#2  0x00007ff66e7a0311 in system () from /lib64/libc.so.6
#3  0x00007ff66f573f9c in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x1f79fd0) at /jenkins/workspace/DailyBuilds/AdHocO2Physics/daily-tags.pYGZGfKgjt/SOURCES/ROOT/v6-28-02/v6-28-02/core/unix/src/TUnixSystem.cxx …
```

Add QC task for ITS clusters and tracks to MC scripts

---

DATA/common/setenv_calib.sh

I wrongly put a sporadic output into the TF output list therefore shadowing all other sporadic inputs. Probably I forgot to explicitly add TPC dEdx calib in my tests and therefore did not notice.
Fix is trivial

Move sporadic calibration from TF block into sporadic one

---

MC/bin/o2_dpg_workflow_runner.py
MC/bin/o2dpg-workflow-tools.py
MC/bin/o2dpg_sim_workflow.py
MC/bin/o2dpg_workflow_utils.py
MC/utils/o2dpg_sim_metrics.py

* harmonise resource extraction
* everything is put into a pandas dataframe
* derive everything from there instead of re-organising everything first
* extract time estimates of each task now also from there (previously was relying on the times from <task>.log_time
* pass arguments from o2dpg_sim_workflow.py through so that all of them end up in pipeline_metric_<pid>.log for later usage
* 3 sub-commands:
* history: produce plots of 1. resources vs. iterations 2. resources of tasks grouped into categories (bar and pie chart) 3. resources distribution of tasks within digi and reco category (pie chart) 4. a stacked bar chart (one bar per iteration) showing the composition of resources by tasks
* compare: plot resources per task based on a feature e.g. eCM if various different pipeline_metric …

Revise o2dpg_sim_metrics.py

---

MC/bin/o2_dpg_workflow_runner.py
MC/bin/o2dpg_sim_workflow.py

Only allow one background job at a time.
Also Adjust CPU resource estimate for simulation to be more accurate (for long simulations).
This is trying to fix an issue where o2-sim cannot initialize due to timeout during FairMQ-based initialization. This happens probably for backfilled jobs which do not get enough attention from the kernel.

Limit number of backfilled jobs

---

MC/config/analysis_testing/json/analyses_config.json
MC/config/analysis_testing/json/analysis-testing-data.json

Tasks:
(minimal)
- EMCAL event selection
- EMCAL cell monitor
(optional)
- EMCAL cluster monitor
- EMCAL track matching monitor
Including dependencies (i.e. correction tasks).
Track matching and event selection QA will
likely not be portable to the async QC. Several
histos in the cell monitor are too heavy for the
QC framework.

[EMCAL-917] Add analysis-level QA tasks for EMCAL

---

DATA/production/calib/its-threshold-aggregator.sh
DATA/production/calib/its-threshold-processing.sh
DATA/production/standalone-calibration.desc

New calib workflows for ITS:
- Full threshold scan
- TOT-calibration 1 row (pulse shape scan 2D, 1 row per chip)
- TOT-calibration fast (pulse shape scan 2D, 512 rows per chip)
- removed ITS-thr-short-no-eos
cc @chiarazampolli @shahor02

New calib workflows for ITS

---

DATA/production/workflow-multiplicities.sh

- Use more ITS trackers for cosmic reco.
- Use by default 2 threads for ITS, TRD, ITS-TPC on EPN.

Some tuning of process multiplicities

---

DATA/production/configurations/CTFSkimming/ctf-skim-workflow.sh

@catalinristea , @mpuccio , @noferini : this extra file will contain the number of skimmed CTFs at the end of the processing. It is not an info important per se, but we can then trigger the validation of this job on the presence of this file instead of o2_ctf*.root, since we might have none of those when the bcRanges selects nothing in the current job.
Let me know if you have feedback!

Adding a log file with the number of files produced by the skimming

---

DATA/production/o2dpg_qc_postproc_workflow.py
DATA/production/qc-async/mch-digits.json
DATA/production/qc-postproc-async/mch.json

The PR adds the post-processing and checkers for the Digits and Preclusters QC tasks.
The code is the same that is used for the online processing. The PP tasks and the checkers should process the output of the ASYNC QC for each run, producing additional plots in the `MCH/Digits` and `MCH/Preclusters` folders, as well as QualityObjects with the check results in `MCH/QO`

MCH: add async post-processing

---

DATA/production/configurations/asyncReco/setenv_extra.sh

So that for runs w/o TRD we use the ITS-TPC-TOF tracks. Otherwise we would not have any tracks with outer points which are needed for the vDrift calibration

TPC interpolation don't skip ITS-TPC-TOF tracks

---

MC/bin/o2dpg_sim_workflow.py
MC/run/ANCHOR/2021/OCT/pass4/anchorMC.sh
MC/run/ANCHOR/2022/JUN/pass1/anchorMC.sh

do not prefetch CCDB object which are anyways not used, nor follow the current naming rule.
Cosmetic change, doesn't impact productions.

typo fix + remove reference to invalid CCDB objects

---

DATA/testing/detectors/TRD/trd-noise.sh

Tested today with Meike a new configuration for taking TRD noise runs. Now we can use an arbitrary number of EPNs and only a single node will upload a calibration object to the CCDB.
Still a very strange behavior was observed for the processing. Using 5 nodes in the beginning for 3 nodes the buffer was immediately full. Another EPN was OK for few minutes and then got a full buffer. The last EPN could happily process the data continuously. All EPNs should be seeing very similar input data, it is not clear to me how this can happen. In case the CCDB populator is by chance put on a node for which the buffer is filled immediately then we don't get a calibration object.

TRD noise workflow

---

MC/bin/o2dpg_sim_workflow_anchored.py
MC/run/ANCHOR/2021/OCT/pass4/anchorMC.sh
MC/run/ANCHOR/2022/JUN/pass1/anchorMC.sh

I changed the anchoring script to parse eCM and col to set ft0-eff.
Then the parameters are forwarded to the sim script
Note that in our scripts these two parameters have to be moved from
remainingargs -> baseargs
once this change is in, as shown also in this PR (and --ft0-eff flag should be no longer used)
Please check also syntax since I couldn't test the change

set ft0-eff with energy/coll_system

---

MC/config/PWGLF/pythia8/generator_pythia8_longlived_gaptriggered.C
test/common/kine_tests/test_generic_kine.C

@gconesab @benedikt-voelkel while testing locally the changes, I have spotted a bug in `test/common/kine_tests/test_generic_kine.C`. There was a second `;` in a for loop.
The correction triggerd the test of everything and many tests of other generators (not the one that I touched) are failing, but it is not related to the changes in `MC/config/PWGLF/pythia8/generator_pythia8_longlived_gaptriggered.C`

Set rapidity instead of pseudorapidity

---

DATA/production/calib/its-threshold-aggregator.sh
DATA/production/calib/its-threshold-processing.sh
DATA/production/standalone-calibration.desc

Hi @davidrohr, this is to include the feature you suggested in your email few days ago. 
I renamed RUNTYPE to RUNTYPE_ITS to avoid having a variable with the same name of the one used for the real run type set in ECS.

ITS: push to ccdb test for synthetic/staging calibration scans

---

DATA/production/qc-sync/qc-global-epn-staging.json
DATA/production/qc-workflow.sh

as discussed in https://alice.its.cern.ch/jira/browse/O2-4069 so far staging could use the same configuration as production, since the database was not used by the worker nodes. Soon the qc task will interface with bookkeeping, so we need to distinguish between staging and prod. Since more than a single key will change I believe its cleaner to have a second json for staging if fine with @davidrohr 
Will merge only after https://github.com/AliceO2Group/O2DPG/pull/1195

Add dedicated staging QC global config

---

DATA/production/workflow-multiplicities.sh

At the moment in the online PbPb the ITS reconstructs by defuilt 30-2000 tracks multiplicity range, corresponding to 53% of collisions and 28% of tracks of LHC22s spectrum. Additionally, we randomly downscale multiplicity-selected ROFs 5%, going to 2.6% collisions and naively 1.4% of all tracks but in reality more since we prioritize ROFs with triggers.
O2 https://github.com/AliceO2Group/AliceO2/pull/11853 makes more precise the mult estimated (tuned on LHC22s) and this PR sets the selected ITS multiplicity to 100:200 tracks range, which corresponds to ~7% of LHC22s ITS mult.spectrum and 1% of tracks. The random selection is turned off by default. The same settings are in the defaults of dpl-workflow.sh.
If needed, the prescaling can be modified via CUT_MULT_MIN_ITS and CUT_MULT_MAX_ITS …

Prescale ITS in pbpb with multiplicity only, no random cut

---

DATA/production/qc-async/trd.json
DATA/production/qc-sync/trd.json
DATA/production/qc-workflow.sh

@chiarazampolli this should be what is needed to have at least some tracking QC for async. But I still need to test on staging if this does not break something when there is no TPC-TRD matching enabled

Enable TRD QC tracking task by default

---

DATA/production/qc-async/emc.json

In the asynchronous stage uncalibrated and calibrated
cells and their corresponding trigger records are
available on different subspecs. Only calibrated
trigger records must be used.

[EMCAL-1037] Specifically request trigger records on subspec 0

---

DATA/production/configurations/2021/OCT/apass4/setenv_extra.sh
DATA/production/configurations/2021/OCT/apass5/setenv_extra.sh
DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
DATA/production/configurations/2022/MayJunePilotBeam/apass1/setenv_extra.sh
DATA/production/configurations/2022/MayJunePilotBeam/apass2/setenv_extra.sh
DATA/production/configurations/2022/extractCalib/setenv_extra.sh
DATA/production/configurations/asyncReco/setenv_extra.sh

This allows to use FT0 BC for producing TOF calib infos.
It will be effective once 
https://github.com/AliceO2Group/AliceO2/pull/11887
is in

use FT0 in TOF calibs

---

DATA/production/configurations/asyncReco/setenv_extra.sh

I found that TOF calib infos when using FT0 (recently introduced) are not as expected and cannot be used for calibration.
For the moment we cannot use it. Restore to previous behavior.

remove ft0 usage from TOF calib

---

DATA/production/configurations/asyncReco/setenv_extra.sh

@chiarazampolli the newly added TRD calibrations gain and t0 were simply not disabled by default in async... I have added the possibility to do the TRD gain calibration via setting `ALIEN_JDL_DOTRDGAINCALIB=1`. It would be good if this would be done, since we cannot run the gain calibration online since RC did not want to port the fix before HI started.
Also changes for the TPC calibration are in this PR, but in a different commit

Changes to async processing

---

DATA/production/configurations/asyncReco/setenv_extra.sh

Hi @chiarazampolli 
sorry, I did not think this through. If we run the gain calibration offline we need to enable the ROOT output, so that we can prepare the manual upload of calibration objects afterwards.
The additional file we'll need to keep is `trd_calibgain.root`.
Cheers,
Ole

Enable TRD gain calib ROOT output

---

DATA/production/qc-async/emc_PbPb.json

Total energy has pileup tail, 25 ns cut sufficient for a 50 ns filling scheme.

[EMCAL-756] Add pileup cut for total energy histograms

---

DATA/production/configurations/asyncReco/setenv_extra.sh

Hi @chiarazampolli @aschmah has asked me to
1) include back TRD+TOF matched tracks needed for vDrift extraction
2) reset ITS min cluster requirement for ITS-TPC tracks to default value of 6 now that ITS problem is fixed
could this be included for the async reco?
Cheers,
Ole

Update TPC residuals extraction settings for async again

---

DATA/testing/detectors/TRD/trd-krypton.sh
DATA/testing/detectors/TRD/workflows.desc

Standalone workflow to be carefully tested first.

Add TRD krypton run workflow

---

RelVal/PlotOverlays.C

in order to make the legend in the 2D overlay plots more readable

O2DPG/RelVal: few changes in the PlotOverlays.C

---

DATA/testing/detectors/TRD/trd-krypton.sh
DATA/testing/detectors/TRD/workflows.desc

Tested today that it works with these fixes

TRD Kr workflow bug fixes

---

MC/config/PWGHF/external/generator/generator_pythia8_gaptriggered_hf.C

Previously the requirement of having a heavy quark with rapidity within the defined window could be satisfied by another parton not composing the heavy-quark pair.
I tested the change generating 20000 b-bbar events with the old and new behavior and requiring a rapidity window between -1 and 1 (the seed is also the same for the two productions).  
The rapidity vs pt distribution for the old rapidity check
The same for the new rapidity check
Plotting the difference between the old and the new distributions (old-new), there is an improvement: events with b quarks at very low pT and large rapidity are removed, while new ones with larger pT and closer to the rapidity window are generated.
@fgrosa @fcolamar @cterrevo @ZFederica @zhangbiao-phy @mfaggin The difference w.r.t. the previous code is …

Small fix to heavy-quark rapidity check for HF generator

---

MC/analysis_testing/o2dpg_analysis_test_workflow.py

Extra dependency needed for AO2Ds produced with O2 tags not including this PR: [12087](https://github.com/AliceO2Group/AliceO2/pull/12087).
See also comment from David Chinellato in the O2 Analysis Announcements Mattermost channel on 27th October 2023: [link](https://mattermost.web.cern.ch/alice/pl/4esghoynzjyxtqnsgmgsb91dqe)

Add track-extra-converter dependency.

---

MC/bin/o2dpg_sim_workflow.py

- Chain cell-recalibrator workfow with reconstruction
workflow to reject bad channels seen in data
- Needs to disable cell writer within reconstruction
within reconstruction workflow and extra cell
writer at the end of the full chain

[EMCAL-1054] Include EMCAL cell recalibrator workflow for bad channel masking

---

DATA/production/qc-sync/glo-mchmid-mtch-qcmn-epn.json
DATA/production/qc-sync/glo-mftmch-mtch-qcmn-epn.json
DATA/production/qc-sync/glo-mftmchmid-mtch-qcmn-epn.json
DATA/production/qc-workflow.sh

Currently the SYNC QC for matched forward tracks is included in the MCH configuration, and limited to MCH-MID tracks. The PR introduces separate QC configuration files for forward matched tracks in SYNC processing, for three different combinations:
- MCH-MID matching (MFT not included)
- MFT-MCH matching (MID not included)
- full MFT-MCH-MID matching: in this case three set of plots are produced, corresponding to the possible matching combinations (MFT-MCH, MCH-MID and MFT-MCH-MID)

MUON: improve SYNC QC for global forward matched tracks

---

DATA/production/qc-async/mid.json

The QC of the synchronous reconstruction in consul has evolved since a while. This PR is meant to use similar parameters in the async_qc.

MID: match recent changes in consul

---

MC/config/PWGHF/ini/GeneratorHF_D2H_bbbar.ini
MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar.ini
MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_and_bbbar.ini

Needed since [this commit](https://github.com/AliceO2Group/AliceO2/commit/a3142359b3b535f0654077234eeeadc1c313b64e) changed the default behavior. This information is particularly useful in the debug phase of the MC production.

Keep parton-event information

---

MC/bin/o2dpg_sim_workflow.py

This is no longer needed and simplifies our processing. Tasks read this directly from CCDB now.

Remove manual material budget downloader

---

DATA/common/setenv.sh
DATA/production/configurations/asyncReco/setenv_extra.sh
UTILS/parse-async-WorkflowConfig.py

Following PR#12205 and PR#12237 instead of boolean switch --require-tpc-lumi one should use --lumi-type <int_type>  option with the meaning:
0 : no dynamic scaling
1 : require CTP lumi for TPC correction scaling
2 : require TPC scalers from CCDB for TPC correction scaling
--lumi-type 1 corresponds to previous ALIEN_JDL_INSTIRFORTPC=CTP --lumi-type 2 corresponds to previous ALIEN_JDL_INSTIRFORTPC=IDCCCDB

Change --require-tpc-lumi option to --lumi-type <type>

---

DATA/production/configurations/asyncReco/setenv_extra.sh

@chiarazampolli : in run: `544116  @38342 Hz`, these thresholds are beyond the measured distribution.
For instance, the attached image is the dist for `cellsPerClusters`-only, since `trackletPerClusters` never exceeds its threshold.
It is however the case for higher IR, therefore I set the two cuts such as I know they should work.
This should be ready for the tests. I left non-fatal behaviour to allow the processing of the logs to double-check, as I understood this is not yet in production.
CC-ing: @mpuccio @shahor02

ITS tracker: release tracklets/cells selection for Pb-Pb tests

---

MC/config/analysis_testing/json/EventSelectionQA/pbpb/analysis-testing-data.json
MC/config/analysis_testing/json/EventTrackQA/pbpb/analysis-testing-data.json
MC/config/analysis_testing/json/EventTrackQA/pp/analysis-testing-data.json
MC/config/analysis_testing/json/default/pbpb/analysis-testing-data.json
MC/config/analysis_testing/json/default/pbpb/analysis-testing-mc.json
MC/config/analysis_testing/json/default/pp/analysis-testing-data.json
MC/config/analysis_testing/json/default/pp/analysis-testing-mc.json

- clean all obsolete Configurables
- remove most of Configurables set to default values
- switch-on the overwriteAxisRangeForPbPb flag, to rearrange multiplicity axes for Pb-Pb
!!! O2Physics PR https://github.com/AliceO2Group/O2Physics/pull/3883#pullrequestreview-1735107548 mandatory!!!
- enable the processing only for PV contributor tracks

Clean and adapt config files for EventaTrack AnalysisQC

---

MC/config/QC/json/trd-digits-task.json

@chiarazampolli @catalinristea 
This is needed to resume Pb-Pb MC

fixing missing inputs in TRD digit

---

DATA/production/qc-async/emc.json
DATA/production/qc-async/emc_PbPb.json

Input Spec for DPL CCDB backend for CTP
configuration added, as the DPL CCDB backend
replaced the QC CCDB backend in the task.

[EMCAL-1037]  Add CTP config input spec

---

MC/bin/o2dpg_sim_config.py

These selections are obsoleted, and the behaviour has been changed in https://github.com/AliceO2Group/AliceO2/pull/12256
See https://github.com/AliceO2Group/O2DPG/pull/1336 proposing the same change for data.
@mpuccio

[PbPb-async-MC-RelVal][O2-4445]: Remove obsolete cuts for ITS iterations

---

DATA/production/qc-async/emc_PbPb.json
MC/bin/o2dpg_qc_finalization_workflow.py
MC/bin/o2dpg_sim_workflow.py
MC/config/QC/json/emc-bc-task.json

Include EMCAL BC QC in simulations in case
CTP is included.

[EMCAL-1054] Enable BC task in simulations

---

DATA/production/configurations/asyncReco/setenv_extra.sh

Hi @chiarazampolli 
for the release validation I understood from Alex that the TPC residuals will be extracted for one full run, right? In that case it would be good to only use ITS-TPC tracks for the map, because otherwise we will create a bias to tracks matched to TRD/TOF which leads to an efficiency loss in some regions (PHOS hole).
Sorry for the late update.

TPC residual extraction with ITS-TPC tracks only

---

MC/bin/o2dpg_sim_workflow_anchored.py

Dear @benedikt-voelkel , @chiarazampolli , @sawenzel , @shahor02 , @gconesab,
this is to recover the right behaviour in pp anchored MC (temporary solution) since ctpinput=0 is invalid.
Final solution has to be discussed with Roman

fix ft0 ctp input for pp case

---

MC/bin/o2dpg_sim_workflow.py

Recent disabling of FT0 calibrations in the reco workflow internally disables the CCDB fetcher. In result, the option --condition-not-before vanishes and the workflow crashes when the option is given on the command line.
This is a generic problem with "dynamic" options.
For now fixing, by taking away this option for FT0 reconstruction.

Fix ft0reco crash

---

DATA/production/qc-async/its.json

This commit switches ON the flag for V0 inv. mass reconstruction in ITS a-QC, which is OFF by default

ITS: Added V0 reconstruction in async workflow

---

DATA/production/configurations/asyncReco/async_pass.sh

@noferini , if you agree, we can merge this for apass1.

Keep TOF output if explicitly requested, not just in CPass

---

MC/bin/o2dpg_sim_config.py
MC/bin/o2dpg_sim_workflow.py

So far, transport sim takes configKey values solely from the command line.
But we might want to apply default configs directly in the script. This is achieved with this commit.
Needed to apply a default MFT setting.

Better construction of configKey values for transport simulation

---

DATA/production/qc-async/mft.json

MFT json file modified to include moving windows for some A-QC objects. The feature was successfully tested locally. @JianLIUhep

Adding moving windows feature for some MFT A-QC objects

---

MC/bin/o2dpg_sim_workflow.py

The work presented in https://indico.cern.ch/event/1351889/contributions/5696031/attachments/2762206/4810535/291123.pdf has been merged, and TPC only tracks have been added by default to the reconstruction. This PR updates the reconstruction in the simulation as well. @ddobrigk @shahor02 @f3sch

Add TPC as default source for the svertexer

---

MC/bin/o2dpg_sim_config.py

Provide FT0 and FV0 gain settings for MC anchored to 2023 PbPb. This is temporary and will be removed when these settings are pulled from CCDB.

FIT: add digitizer settings for MC anchored to 2023 PbPb

---

MC/bin/o2_dpg_workflow_runner.py

* introduce functionality to update resource estimates based on values
which are collected during monitoring
(the same that go into pipeline_metric_<pid>.log)
* disentangle resource management from WorkflowExecutor
* manage resources via ResourceManager object
* memory and cpu
* semaphores
* number of parallel tasks to be launched
* niceness
* main interfaces of ResourceManager
* ok_to_submit
* book
* unbook
* add_monitored_resources
* group corresponding tasks together to be able to update resource
estimates for upcoming tasks
* TaskResources as container of a task's resource estimate
holding
* resource estimates (initial and new estimates)
* references to Semaphore object (optional
* reference to list of related tasks (optional)
* make sure, final niceness assigned to a launched process …

[WFRunner] Estimate resources dynamically

---

DATA/production/qc-async/trd.json
DATA/production/qc-sync/trd.json
MC/config/QC/json/trd-digits-task.json

Given the chamber status object changes, set new path to `TRD/Calib/DCSDPsFedChamberStatus`.
---
Relevant JIRA: [TRD 109](https://alice.its.cern.ch/jira/browse/TRD-109)
Relevant PRs: https://github.com/AliceO2Group/AliceO2/pull/12319 https://github.com/AliceO2Group/QualityControl/pull/2075

TRD: New CCDB path for Chamber Status

---

DATA/production/configurations/asyncReco/async_pass.sh

@jgrosseo : I kept the same logic as before, but in principle, failing merging should make the process exit now.

Forbid AOD merging to fail

---

MC/config/PWGDQ/external/generator/GeneratorCocktailPromptCharmoniaToElectronEvtGen_pp13TeV.C
MC/config/PWGDQ/external/generator/GeneratorCocktailPromptCharmoniaToMuonEvtGen_PbPb5TeV.C
MC/config/PWGDQ/external/generator/GeneratorCocktailPromptCharmoniaToMuonEvtGen_pp13TeV.C
MC/config/PWGDQ/external/generator/GeneratorParam.C
MC/config/PWGDQ/external/generator/GeneratorParamPromptJpsiToElectronEvtGen_pp13TeV.C
MC/config/PWGDQ/external/generator/GeneratorParamPromptJpsiToMuonEvtGen_pp13TeV.C
MC/config/PWGDQ/external/generator/GeneratorPromptCharmonia.C

Generator configs accessing TPythia6Decayer now need to load the pythia6 library explicitely, following https://github.com/AliceO2Group/AliceO2/pull/12514
Somehow the EGPythia6.so lib (where TPythia6Decayer is coming from) from ROOT is missing an automatic resolution link to these symbols.

load pythia6 library

---

DATA/production/configurations/2021/OCT/apass4/setenv_extra.sh
DATA/production/configurations/2021/OCT/apass5/setenv_extra.sh
DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
DATA/production/configurations/2022/MayJunePilotBeam/apass1/setenv_extra.sh
DATA/production/configurations/2022/MayJunePilotBeam/apass2/setenv_extra.sh
DATA/production/configurations/2022/extractCalib/setenv_extra.sh
DATA/production/configurations/asyncReco/setenv_extra.sh

This is to remove --use-fit in tof calibration from async, it would be added in O2 both for sync and async

remove use-fit option in tof matcher (to be added in O2 default)

---

MC/bin/o2dpg_sim_config.py
MC/bin/o2dpg_sim_workflow.py

In case of generator pythia8, we have so far always constructed a Pythia8 config file from the parameters given to o2dpg_sim_workflow.py
However, some expert users may want to use an external configuration for Pythia8.
This commit provides the possibility to do so via sensitivity to the `GeneratorPythia8.config` ConfigurableParam (so far ignored).
An example is:
```
${O2DPG_ROOT}/MC/bin/o2dpg_sim_workflow.py -eCM 14000 -col pp -gen pythia8 -proc cdiff -tf 2      \
-ns 20 -e ${SIMENGINE}                                 \
-j ${NWORKERS} -interactionRate 500000                 \
-run 302000 -seed 624                                  \
-confKey "GeneratorPythia8.config=/SOMEPATH/pythia8_powheg.cfg"
```
The new feature allows expert studies with specially setup Pythia8 configs. The development …

Possibility to take external config for Pythia8

---

MC/bin/o2_dpg_workflow_runner.py
MC/bin/o2dpg_sim_workflow.py
MC/bin/o2dpg_workflow_utils.py

Use new feature of O2 to scan for leaked CCDB semaphores related to CCDB caches and clean them up before workflow execution.
To this end, expand the __global_init__ mechanism with a "cmd" (not just environment variables) field. The pipeline runner will execute such init command before workflows start.
Solves a problem, where second run/pass of workflow running hangs due to previously leaked semaphores.

Clean possibly leaked CCDB semaphores at workflow start

---

MC/config/PWGLF/pythia8/generator_pythia8_LF.C

@njacazio this fixes the "number of events between trigger" to be correct. At the moment, for N > 1, the gap-to-triggered ratio is (N-1):1 and not N:1 as the name of the variable suggests. Note this may offset our conclusions regarding [O2-3702](https://its.cern.ch/jira/browse/O2-3702) - though AFAIK this is the only use case so far.

LF: fix bug in N:1 gap-triggering

---

DATA/production/qc-sync/tpc.json

To avoid triggering the error here in the FST CI:
```
Detectors/TPC/qc/src/Tracks.cxx:185:          LOGP(error, "o2::base::Propagator not properly initialized, MatLUT ({}) and / or Field ({}) missing, will not fill DCA histograms", (void*)propagator->getMatLUT(), propagator->hasMagFieldSet());
```

TPC QC allow proper init of propagator to avoid error message in FST

---

DATA/production/configurations/asyncReco/setenv_extra.sh

1) removed TPC cluster additive errors
2) reduces Z and tgL track syst errors
3) decreased matching chi2 cut and allowed max abs difference between TPC and ITS q/pt 
4) set the matching reference X = 60
5) default TPCSCALINGSOURCE changed from CTP to IDCCCDB
@miranov25 this sets the errors and matching chi2 cuts which should be reasonable with the tested corrections. If you have better ones, let me know.

Adjust syst errors and ITS/TPC matching pars, use IDCCCDB as default scaling src

---

RelVal/config/QC/async/ITS_include_patterns_default.txt
RelVal/config/QC/async/TOF_include_patterns_defautl.txt
RelVal/config/QC/async/TPC_include_patterns_default.txt
RelVal/utils/o2dpg_release_validation_utils.py

* put files with include patterns at RelVal/config/QC/async/<DET>_include_patterns_default.txt
* add pattern files for ITS, TPC, TOF
* allow comments starting with "#"

[RelVal] Add specific QC objects to compare

---

DATA/production/configurations/asyncReco/setenv_extra.sh

Hello @costing, this was a rule till some time ago at least; is it still the case?

JDL vars don't allow spaces or underscore: only 1 word

---

DATA/tools/epn/gen_topo.sh
DATA/tools/epn/gen_topo_o2dpg.sh

This would allow to run the `epn-topo-merger` with the option `--force-exact-node-numbers --nodes-mi50 1 --nmin-mi50 0 --nodes-mi100 1 --nmin-mi100 0` in case the user specifies `DEBUG_TOPOLOGY_GENERATION=1`. In that case also the temporary xml file would be kept for inspection.
Ping @davidrohr to see if its fine with you?

Debug mode for topology generation

---

MC/run/ANCHOR/anchorMC.sh

Reverts AliceO2Group/O2DPG#1462
Needs to be reverted, doesn't work for PbPb. In that case, `heavy_ion` should be taken which would be the default if no `-proc` is set explicitly by the user.

Revert "Update anchorMC.sh - added proc arg"

---

MC/bin/o2dpg_sim_workflow_anchored.py
MC/run/ANCHOR/anchorMC.sh

Use as ALIEN_JDL_ANCHOR_SIM_OPTIONS="-ini <ini_file> -confKey
"key=value;otherKey=otherValue" -trigger <trigger_file>
-productionTag myTag"
Build the final remainingargs by prepedning it.
The last argument wins, hence in this case -productionTag would not be
overwritten with this user choice

[AnchorMC] Allow for any additional option for sim WF

---

DATA/common/gen_topo_helper_functions.sh
DATA/common/setenv_calib.sh
DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh
DATA/production/configurations/asyncReco/async_pass.sh

To make the new check added in https://github.com/AliceO2Group/O2DPG/pull/1469/files happy.
The functionality remains the same, only the `DATA/production/configurations/2022/LHC22f/apass1/setenv_extra.sh` script had a bug but I believe this is not used anymore in any case.

Fix syntax checks for shell scripts

---

DATA/common/setenv.sh
DATA/production/workflow-multiplicities.sh

Hi @shahor02 I have set `TPC_CORR_SCALING` as discussed in https://its.cern.ch/jira/browse/O2-4666. Shall we for synthetic runs disable the correction as we do for cosmics? The current central synthetic configurations don't have `TPC_CORR_SCALING` set, so they are using the default settings at the moment. If the behaviour should remain the same I will update this PR.

Cleanup of predefined ECS configurations

---

DATA/common/setenv_calib.sh

In the predefined configs the SAC processing is disabled for SYNTHETIC runs while the IDC processing is always enabled. Not sure if I should keep the SAC processing disabled for synthetic runs @rmunzer ?

Enable IDC and SAC processing by default

---

.github/workflows/async-auto-label.yml
.github/workflows/async-list-label.yml

Following what was introduced in https://github.com/alisw/ali-bot/pull/1293

Add asyn-label workflows for PRs

---

DATA/production/configurations/asyncReco/async_pass.sh

This reverts commit fd619fe62c5c4f622492992a367da6945f1d5186.
@chiarazampolli : This is an old workaround I put in place for correct SHMSIZE and TIMEFRAME_RATE_LIMIT, since before O2 PR 12412 this was not used correctly.
I assume we are no longer running such old O2 tags, do we?
If not, I'd merge this to clean up the constants, since otherwise they are copy and pasted, and can get out of sync.
All is defined and used from workflow-multiplicities.sh now.

Revert "Temporary workaround, to be reverted once O2 PR 12412 is in all async tags"

---

MC/run/ANCHOR/anchorMC.sh

@benedikt-voelkel , @miranov25, @catalinristea , @noferini , @sawenzel

Running extraction of TPC time series in anchored MC

---

MC/run/ANCHOR/anchorMC.sh

* help messages
* set ALIEN_JDL_ADDTIMESERIESINMC to a value at the beginning

[Anchor] Add some more help messages

---

MC/run/ANCHOR/anchorMC.sh

Reverts AliceO2Group/O2DPG#1513
I am sorry, I mixed up various different return codes from various places which led me to the conclusion that with the `-k` option it would return with `0` overall.
But it returns with `1` already.

Revert "[Anchor] Remove -k from QC run, return error code"

---

MC/analysis_testing/o2dpg_analysis_test_workflow.py

Since o2-analysis-v0converter produces the v0_002 table, it should be checking for that and not O2v0_001 to decide whether to run the converter

Fix converter logic for o2-analysis-v0converter in test workflow

---

MC/run/examples/O2DPG_pp_minbias.sh

Achieved by changing `-tt Analysis_` to `--target-labels Analysis`. Upload tasks to not have that label, instead they can be triggered with `--target-labels AnalysisUpload`

Run only analyses, no QCDB upload

---

RelVal/utils/ExtractAndFlatten.C

* e.g. missing dictionary in case of QC files that have been constructed with older SW tags

[RelVal] Fix to really skip unreadable objects

---

MC/config/PWGLF/pythia8/generator/resonancelist.gun
MC/config/PWGLF/pythia8/generator/resonancelistgun.json
MC/config/PWGLF/pythia8/generator/resonances.cfg

From Pythia 8.303, The PDG code of Lambda(1520) has been updated to `102134` instead of `3124`

Update Lambda1520 pdg code

---

MC/bin/o2dpg_sim_workflow.py

spotted when running with non-parallel execution in the pipeline runner

TPC reco needs CTP digits

---

UTILS/o2dpg_make_github_pr_report.py

Logic is now the following:
1. Fetch all labels (optionally given some regex).
2. Get closed PRs that have at least one of those labels.
3. Split into merged and not merged.
4. Populate a table per label and list merged PRs. (A PR can therefore appear in more than one table.)
5. Write everything to a txt file.

Get all labels and change table organisation

---

DATA/production/common/setVarsFromALIEN_PROC_ID.sh

@shahor02 
I am still checking why I had `wc -l`...

Fixing cases in which the number starts with 0 and is considered base 8

---

MC/bin/o2_dpg_workflow_runner.py

* Account for relative CPU factor in case of sampling
Studies have shown that being able to backfill tasks can have a
difference for CPU efficiency, especially for transport.
That is in particular important for high-efficiency jobs such as
high-interaction-rate pp simulations.
* Abort by default if estimated resources exceed limits
* Run anyway, if --optimistic-resources is passed
* Fix: Actually reset the overestimated resources to the limits as
otherwise the runner would silently quit when nothing else can be
done.
* In case of dynamically sampled resources and if a corresponding task
has been run already:
Reset the assigned resources to the limits if they exceed the
boundaries.

[WFRunner] Handle resource limits and CPU better

---

DATA/production/qc-async/mft.json
DATA/production/qc-sync/mft-full-no-tracks.json
DATA/production/qc-sync/mft-full.json
MC/config/QC/json/mft-clusters.json
MC/config/QC/json/mft-digits-0.json
MC/config/QC/json/mft-digits-1.json
MC/config/QC/json/mft-digits-2.json
MC/config/QC/json/mft-digits-3.json
MC/config/QC/json/mft-digits-4.json
MC/config/QC/json/mft-tracks.json

Update the MFT json files in:
- DATA/production/qc-async/ ... onlineQC = 0
- MC/config/QC/json/ ... onlineQC = 0
- DATA/production/qc-sync/ ... onlineQC = 1
grpGeomRequest settings modified everywhere to normalize the QC objects to the # orbits 
Relates to https://github.com/AliceO2Group/QualityControl/pull/2198

Update MFT json files: 'onlineQC' flag in Cluster task + grpGeomRequest

---

DATA/production/qc-async/mch-tracks.json

@aferrero2707 : at present, master + dev are broken in async reco, I guess due to https://github.com/AliceO2Group/QualityControl/pull/2150

Adding missing input

---

MC/bin/o2dpg_sim_workflow.py

Without this, passing -embedding would work and produce a workflow.json. However, the resulting WF has nothing to with embedding, since the real flag for that has 2 dashed: --embedding
What really happened was that the engine would now be "mbedding"
So far there are no clashes for -j or -o which are also valid arguments.

[SimWF] Protect the -e argument

---

MC/config/PWGDQ/external/generator/GeneratorPromptCharmonia.C
MC/config/PWGDQ/external/generator/generator_pythia8_withInjectedPromptSignals_gaptriggered_dq.C
MC/config/PWGDQ/ini/Generator_InjectedChiCToElectronMidy_TriggerGap.ini
MC/config/PWGDQ/ini/tests/Generator_InjectedChiCToElectronMidy_TriggerGap.C

This is the new commit. I had to include the definitions of the ChiC1, ChiC2 cocktail inside the GeneratorPromptCharmonia.C to avoid double include's

New commit on ChiC1, ChiC2 to avoid duplicated included

---

MC/run/ANCHOR/anchorMC.sh
MC/run/ANCHOR/tests/test_anchor_2023_apass2_PbPb.sh
MC/run/ANCHOR/tests/test_anchor_2023_apass2_pp.sh

* check for GRID token at the very beginning
* check for jq tool at the very beginning
* set a default seed if nothing is given
* adjust tests

Tidy a bit and abort as early as possible

---

GRID/utils/grid_submit.sh

* changes to reflect novel Alien behaviour to get sub-job ids
* less calls to alien.py
* some cleanup

Improvements to grid_submit

---

MC/config/PWGLF/xsection/g4config_had_x2.in

For bookkeeping: hadronic processes for the different nuclei are defined starting from L. 150 of the 
`G4IonPhysics::ConstructProcess()` function: [link](https://apc.u-paris.fr/~franco/g4doxy/html/classG4IonPhysics.html#e1df0b79959a6330ab6d53d9ec02d911)
@njacazio , now the proper scaling is applied to the different XSs

Use proper hadronic process for the different nuclear species

---

DATA/production/configurations/asyncReco/setenv_extra.sh

The matching chi2 cut for pbpb is set to 80. It is still an overkill but will add a ~2% of fakes only (should be much more below the main chi2 peak)
Already the tracks with Chi2>40 seem not to have any contribution to the K0's.

Adjust matching chi2 cut to 80 for pbpb

---

GRID/utils/grid_submit.sh

`alien.py cp ...` is not returning (after the copy).... probably related to a software-platform inconsistency (to be confirmed).
Avoid this hang meanwhile, until issue is fully understood.
Related to https://its.cern.ch/jira/browse/O2-4804

avoid hang in grid submit

---

GRID/utils/grid_submit.sh

provide environment variables
```
export ALIEN_O2DPG_GRIDSUBMIT_PRODSPLIT=${PRODSPLIT}
export ALIEN_O2DPG_GRIDSUBMIT_SUBJOBID=${SUBJOBID}
```
which contain the total jobs submitted for the workload and the assigned subjod id.
These numbers can be used by the workload to contextualize.

Grid_submit: Provide prodsplit and subjob id to workload

---

MC/config/examples/external/generator/SimpleCocktail.C

Providing a custom generator example that can serve as a template for generators using multiple internal o2::eventgen::Generator generators (cocktails, gap triggers, ...).

External generator example for simple cocktails/gap gens

---

MC/bin/o2dpg_sim_workflow.py

did not take into account first-orbit, which is used in anchoring MC.

Fix options for collision context creation in (old) embedding path

---

DATA/production/calib/emc-pedestal-aggregator.sh
DATA/production/calib/emc-pedestal-processing.sh

Allow adjustable QC workflow as stand-alone or
multi-node workflow with separate configurations.
In addition minor fixes in the input proxy configuration.

[EMCAL-1118] Make QC workflow mode settable

---

MC/bin/o2dpg_sim_workflow.py
MC/run/PWGLF/run_HyperNucleiInjectedGap.sh
MC/run/PWGLF/run_StrangenessInjected.sh
MC/run/PWGLF/run_StrangenessTriggered.sh

This ensures consistency between MC and data reconstruction conditions, where strangeness tracking is enabled by default both in pp and Pb--Pb

Enable strangeness tracking by default

---

MC/bin/o2dpg_sim_workflow_anchored.py

Use BasicCCDBManager's getRunDuration to determine time range to be covered by simulation.
This will first try to get STF and ETF. If not available, the fallback chain is
1. SOX and EOX
1. SOR and EOR

[Anchor] Use STF and ETF

---

MC/config/ALICE3/ini/pythia8_ArAr.ini
MC/config/ALICE3/ini/pythia8_KrKr.ini
MC/config/ALICE3/ini/pythia8_OO.ini
MC/config/ALICE3/ini/pythia8_PbPb.ini
MC/config/ALICE3/ini/pythia8_XeXe.ini
MC/config/ALICE3/pythia8/generator_pythia8_ALICE3.C

This purpose of this pull request is to allow the use of the default pythia8 generator without changing the command specifying which generator to use from "external" to desired generator on hyperloop.

[ALICE3] Add empty external generator and adjust ini files to adhere to hyperloop workflow

---

MC/run/ANCHOR/anchorMC.sh

Goes together with https://github.com/AliceO2Group/AliceO2/pull/12761 : since MC creates its own snapshot of GeometryAligned, it should also create the lightweight ITS and MFT geometries. This is because now many workflows don't use GeometryAligned directly but fetch ITS(MFT)/Config/Geometry objects created from GeometryAligned.

Create ITS/MFT light geom snapshots together with geometry-aligned

---

DATA/tools/epn/gen_topo.sh

@martenole : Could we deploy this with the next software update?
It moves the gen_topo temp folder to a local folder on the infra node.
Not sure if you'll need to adapt any of your fetch/check scripts.

gen_topo.sh: Use /var/tmp/gen_topo as gen_topo temp folder

---

DATA/production/configurations/asyncReco/setenv_extra.sh

Dear @chiarazampolli , @shahor02 ,
I realized that we are missing one flag needed for cpass0 to disable the check on problematic channels.
Today from QC (@ercolessi) we realized that two runs had problem with sync calibrations and the problem was propagated to cpass0 sine of this missing flags.
In such cases we cannot use cpass0 to calibrate.
We need this fix as soon as possible for cpass0 reco.
Cheers,
Francesco

adding missing flag for TOF in cpass0

---

DATA/production/qc-async/mch-tracks.json

The loading of the GRPECS object needs to be enabled in order to retrieve the correct value of orbits/TF, otherwise the default value of 128 is used. The orbits/TF is used for the absolute normalization of the histograms.

MUON: fixed normalization of tracks histograms

---

DATA/production/qc-async/mch-tracks.json
DATA/production/qc-async/mchmid-tracks.json
DATA/production/qc-async/mftmch-tracks.json
DATA/production/qc-async/mftmchmid-tracks.json

The loading of the magnetic field is needed to correctly extrapolate the tracks to the interaction point.

MUON: enabled magnetic field in tracks QC

---

MC/config/ALICE3/pythia8/generator/pythia8_ArAr.cfg
MC/config/ALICE3/pythia8/generator/pythia8_KrKr.cfg
MC/config/ALICE3/pythia8/generator/pythia8_OO.cfg
MC/config/ALICE3/pythia8/generator/pythia8_PbPb.cfg
MC/config/ALICE3/pythia8/generator/pythia8_XeXe.cfg
MC/config/ALICE3/pythia8/generator_pythia8_ALICE3.C

Since we specify the use of an external generator on hyperloop the o2-sim-dpl-eventgen task does not accept a seed given using the "--seed" command line option and we instead have to give the seed manually when we initialize the generator.

ALICE3: Allow external generator to accept seed during initialization

---

MC/bin/o2_dpg_workflow_runner.py
MC/bin/o2dpg_sim_workflow.py

Fix warnings about invalid escape sequences

---

MC/bin/o2dpg_sim_workflow.py

- ctp readout create does not properly work in
2023 as only 1 trigger class per trigger is
expeected
- By design it is impossible to recover the trigger
classes from the trigger records as they are not
encoded in the trigger record, so the min. bias trigger
is assumed. This does not work for triggers that
provide triggers themselves.

Remove option ctp-readout-create

---

MC/config/ALICE3/ini/pythia8_pp.ini
MC/config/ALICE3/ini/pythia8_pp_136tev.ini
MC/config/ALICE3/ini/pythia8_pp_ropes.ini
MC/config/ALICE3/ini/pythia8_pp_ropes_136tev.ini
MC/config/ALICE3/ini/pythia8_pp_shoving.ini
MC/config/ALICE3/ini/pythia8_pp_shoving_136tev.ini
MC/config/ALICE3/ini/tests/pythia8_pp.C
MC/config/ALICE3/ini/tests/pythia8_pp_136tev.C
MC/config/ALICE3/ini/tests/pythia8_pp_ropes.C
MC/config/ALICE3/ini/tests/pythia8_pp_ropes_136tev.C
MC/config/ALICE3/ini/tests/pythia8_pp_shoving.C
MC/config/ALICE3/ini/tests/pythia8_pp_shoving_136tev.C
MC/config/ALICE3/pythia8/generator/pythia8_pp.cfg
MC/config/ALICE3/pythia8/generator/pythia8_pp_136tev.cfg
MC/config/ALICE3/pythia8/generator/pythia8_pp_ropes.cfg
MC/config/ALICE3/pythia8/generator/pythia8_pp_ropes_136tev.cfg
MC/config/ALICE3/pythia8/generator/pythia8_pp_shoving.cfg
MC/config/ALICE3/pythia8/generator/pythia8_pp_shoving_136tev.cfg

Hi! With this pull request we want to add some different pp configurations to be used for OTF simulations on hyperloop

[ALICE3] Add configuration files for pythia8 pp

---

DATA/production/qc-workflow.sh

PR for QC follows later. This passes the list of active detectors to the QC task so that it can publish only the histograms for the active detectors

Add CTF size QC and pass active detector list

---

DATA/production/qc-async/emc.json
DATA/production/qc-async/emc_PbPb.json

Histograms from cell task:
- Amp vs. SM
- Time vs. SM
- Occupancy > 500 MeV
- Av. energy
- Av. time
For calibration checks. Cycle duration: 5 minutes.

[EMCAL-756] Moving windows for EMCAL async QC

---

DATA/production/calib/tpc-laser-aggregator.sh
DATA/production/calib/tpc-laser-filter.sh
DATA/production/calib/tpc-laser.sh
DATA/production/calib/tpc-pedestal.sh
DATA/production/calib/tpc-pulser-long.sh
DATA/production/calib/tpc-pulser.sh
DATA/production/qc-workflow.sh

Change from consol to apricot usage for retrieving qc configuration.
Changes were tested in REPLAY runs in production with all detectors.

Change from consul to apricot (tpc standalone + global sync)

---

DATA/production/calib/tpc-pedestal.sh

If syncfilter is not active the first sync signal can spoil the result of the pedestal fit. 
Values are suppressed by minADC cut.

TPC - Add min ADC value in pedestal workflow

---

MC/config/ALICE3/pythia8/generator_pythia8_ALICE3.C

...does not yet guarantee PYTHIA will accept it!

ALICE 3: proc_id is actually a long

---

DATA/production/common/getStat.sh
DATA/production/configurations/asyncReco/async_pass.sh

@catalinristea , please, let me know in case something is missing. I thought this was done already, but I was wrong.

To make it possible to run without the nodownload

---

DATA/production/configurations/CTFSkimming/ctf-skim-workflow.sh

@chiarazampolli  @mpuccio the TFs with no data in the skimmed CTFs corresponded to TFs for which nothing was selected but the following 3TFs had something selected. The reason is that we did not set from the command line the NHBFPERTF (via HBFUTILS), as a result, the workflow was taking default 128 HBF. So, the `ctf-reader` was seeing something selected for the `[1st_orbit : 1st_orbit+128]` but detector encoders did not find any selected BC overlapping with the TF being processed and were writing empty CTF. Effectively, the `--skip-skimmed-out-tf` was not working for most of TFs, but this should be fully transparent for further processing.
The corruption reports is something else, still debugging.

Skimming needs to know NHBPERTF, extract from ALIEN_JDL_LPMRUNNUMBER

---

MC/run/ANCHOR/anchorMC.sh

We need to put `--run` to DPL workflows which are prefixed with echo "echo ... pipe".
This should fix a problem where (under so far unknown circumstances), the geometry alignment workflow did not execute properly.

Add --run to alignment geometry creation

---

DATA/production/qc-workflow.sh

To avoid conflict between parallel runs, the QC task on the EPNs is only started if CTP readout is enabled. 
In this case the task is only executed for one partion in parallel.

CTF Size QC task - Only for Global run

---

MC/config/PWGHF/pythia8_gun/generator_pythia8_gun.C

This fixes a very old bug in which a random uniform number is chosen for py and then px is calculated accordingly, which is not a valid manner of randomly emitting particles uniformly in azimuth and will lead to a modulation versus azimuthal angle. Not sure if this is relevant for anyone at all but it's best fixed for posterity. 
Note that the relevant generation is still done in p (total momentum) and not pT (transverse momentum): this remains unchanged.

Fix px/py bug in generator_pythia8_gun.C

---

DATA/production/calib/tpc-laser-aggregator.sh
DATA/production/calib/tpc-laser-filter.sh
DATA/production/calib/tpc-laser.sh

In order to reconstruct more laser tracks, the trackig tolerances are relaxed. The laser intensity is very weak. This leads to very few clusters above threshold and very low dE/dx.
What was modified is
- lower the track dEdx max cut from minimum 20 to 8
- switch off the addition of sub-threshold clusters. This will tear down the dE/dx even more, if enabled
- increase the tracking tolerances in terms of gaps between clusters from 4/2 in tracking/seeding to 15/15

TPC: Simplify and uinfy remapping, relax traking toleances

---

DATA/production/qc-async/mft.json

* New MFT configuration check. New code already merged to QC (https://github.com/AliceO2Group/QualityControl/pull/2357).
* This is a changed configuration for async qc for proper timestamp retrieval.

MFT: new configuration check for async qc

---

MC/config/PWGLF/pythia8/generator/resonancelistgun_inj.json
MC/config/PWGLF/pythia8/generator/resonancelistgun_inj_pbpb.json
MC/config/PWGLF/pythia8/generator/resonancelistgun_trig.json
MC/config/PWGLF/pythia8/generator/resonancelistgun_trig_pbpb.json

By default, f0 is not generated in Pythia8 so we need to inject it.

[PWGLF] Move f0(980) to injection particle list

---

DATA/production/configurations/asyncReco/setenv_extra.sh

@chiarazampolli Here I've added to the maser version of `setenv_extra.sh` the TPC errors and extra flags for shared treatment as they were in apass4_test3. Note that they are always applied, not only for pbpb.
Also enabled the AOD thinning (` --thin-tracks`) but only for pbpb23. Please confirm that this is what we need.

Adopt settings of pbpb23 apass4 test3 + --thin-tracks in AOD

---

MC/analysis_testing/o2dpg_analysis_test_utils.py
MC/config/analysis_testing/json/dpl/o2-analysis-qa-event-track.json

This should fix the issue seen in the analysis QC for the qa-event-track task for which the axis range is always the one of PbPb instead of changing in case of pp data. 
@mfaggin , @alcaliva

Set the analysisQC axis range depending on the coll system

---

MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_and_bbbar_gap5_DReso.ini
MC/config/PWGHF/ini/tests/GeneratorHF_D2H_ccbar_and_bbbar_gap5_DReso.C
MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_DReso.cfg

This PR adds the configuration for pp MC simulations with enhanced D resonances.

PWGHF: add ini for D resonances MCs for pp collisions

---

MC/config/PWGDQ/external/generator/GeneratorPromptCharmonia.C
MC/config/PWGDQ/external/generator/generator_pythia8_withInjectedPromptSignals_gaptriggered_dq.C
MC/config/PWGDQ/ini/Generator_InjectedPromptCharmoniaFwdy_TriggerGap_PbPb5TeV.ini
MC/config/PWGDQ/ini/tests/Generator_InjectedPromptCharmoniaFwdy_TriggerGap_PbPb5TeV.C
MC/config/PWGDQ/pythia8/generator/pythia8_inel_triggerGap_5TeV.cfg

Adding scripts to run DQ simulations in Pb-Pb collisions

[PWGDQ] Adding scripts to run DQ simulations in Pb-Pb collisions

---

DATA/production/configurations/asyncReco/setenv_extra.sh

@chiarazampolli  this activates by default the new UPC settings for pbpb processing. 
Can be disabled by providing ALIEN_JDL_DISABLE_UPC=1 from the JDL.

Activate non-invasive UPC settings for pbpb reconstruction

---

MC/config/ALICE3/ini/tests/xicc_PbPb.C
MC/config/ALICE3/ini/tests/xicc_pp.C
MC/config/ALICE3/ini/xicc_PbPb.ini
MC/config/ALICE3/ini/xicc_pp.ini
MC/config/ALICE3/pythia8/generator/config_custom_xicc.cfg
MC/config/ALICE3/pythia8/generator/pythia8_hi.cmnd
MC/config/ALICE3/pythia8/generator/pythia8_pp.cmnd
MC/config/ALICE3/pythia8/generator_pythia8_gun_PbPb.C
MC/config/ALICE3/pythia8/generator_pythia8_gun_pp.C

Adding generators that inject xicc for both pp and PbPb. There is also ini files that make use of these generators so I also added test scripts for respective ini file. However, I'm not sure if the tests are done properly yet so I'm currently marking as a draft for now.

ALICE 3: Add xicc injector for pp and PbPb

---

MC/config/PWGLF/pythia8/generator_pythia8_LF.C

1. fixing : error: use of undeclared identifier 'nlohmann'
2. fixing : error: reference to 'Pythia' is ambiguous

Minor fix to generator_pythia8_LF.C

---

DATA/production/qc-async/mft.json
DATA/production/qc-sync/mft-full-no-tracks.json
DATA/production/qc-sync/mft-full.json
MC/config/QC/json/mft-clusters.json
MC/config/QC/json/mft-digits-0.json
MC/config/QC/json/mft-digits-1.json
MC/config/QC/json/mft-digits-2.json
MC/config/QC/json/mft-digits-3.json
MC/config/QC/json/mft-digits-4.json

MFT had changes for check parameter for digits and clusters (both names and values).

MFT: new parameter name for digits and clusters

---

DATA/production/configurations/asyncReco/setenv_extra.sh

This will apply `tpcitsMatch.askMinTPCRow[..]=20` for all PbPb23 run with `tpcitsMatch.askMinTPCRow[11]=78` for `runs >=544511` to account for missing IROC11, but with exception of runs processed with version async-async-v1-01-12 or async-async-v1-01-14, where affected runs >544886 were not overridden by `tpcitsMatch.askMinTPCRow[11]=78`:
whole LHC24al and:
```
batch 1, version 12:
544947
batch 3, version 12:
545289, 545004, 545060, 544931, 545184
batch 4, version 14:
545345, 544963
batch 5, version 14:
544991, 544911, 545103, 545086
```

Apply custom askMinTPCRow with IROC11 exception for unprocessed runs

---

DATA/tools/epn/gen_topo_o2dpg.sh
DATA/tools/parse

This fixes the topology generation failures which we started to see today.
No idea why it never happened before, and why now many environments are affected.
What happens is that stdin is passed from the script called by ODC to the topology parser and then to the DPL executables, and apparently in some cased we get an stdin file descriptor which reports to be not empty, but reading from it fails with `bad file descriptor`. This fix just overrides the stdin for all the scripts called by the parser with an empty one.

Topology parser: Override stdin file descriptor of the scripts that are called with an empty one

---

MC/bin/o2dpg_sim_workflow.py
UTILS/InitHepMCEventSkip.sh
UTILS/ReadHepMCEventSkip.sh

This is useful when simulating different SPLITIDs/CYCLEs of a run in separate jobs.
For given parameters:
PRODSPLIT
NTIMEFRAMES
NSIGEVENTS
SPLITID
CYCLE
the offset can e.g. be calculated with:
HEPMCOFFSET`echo "(${CYCLE}+${PRODSPLIT}*(${SPLITID}-1))*${NTIMEFRAMES}*${NSIGEVENTS}" | bc`

Added possibility to define a general HEPMCOFFSET.

---

test/run_generator_tests.sh

O2DPG_MC_CONFIG_ROOT is not set in the script, so the CI fails. It is set by default equal to O2DPG_ROOT. This PR should fix the issue seen in https://github.com/AliceO2Group/O2DPG/pull/1756

Fix for run_generator_tests.sh using new configuration varibale

---

DATA/production/qc-async/itstpctof.json
DATA/production/qc-async/itstpctofwtrd.json
DATA/production/qc-async/pidft0tof.json
DATA/production/qc-async/pidft0tofwtrd.json
DATA/production/qc-async/pidtof.json
DATA/production/qc-async/tof.json

This PR is to add moving window for asynch TOF objects:
DecodingErrors
HitMap
OrbitVsCrate
mEffPt_ITSTPC-ITSTPCTRD
EvTimeTOF
DeltaEvTimeTOFVsFT0AC
Cc @noferini

TOF: Add moving window in TOF asynch jsons

---

MC/bin/o2dpg_sim_workflow.py

Introducing --orbits-early <N> option in MC workflow generation. This, together with --pregenCollContext, will simulate events in the <N> orbits before each timeframe start, so that (in particular TPC) readout sees digits from the previous timeframe.
For now, this just accepts multiple orbits. Finer granularity will come.

Allow to generate events before timeframe start

---

MC/bin/o2dpg_determine_eventstat.py

Fixing a problem in detecting the right number of events from AO2D due to a recent name change O2mccollision --> O2mccolision_001 in the AOD format.

More resilient logic in determining MC events from AO2D file

---

DATA/tools/epn/gen_topo_o2dpg.sh

I tested this locally both from scratch and with a corrupt repository from one of the topology generations today.

protection against corrupt O2DPG repository during topology generation

---

MC/config/PWGLF/ini/GeneratorLF_Resonances_PbPb.ini
MC/config/PWGLF/ini/GeneratorLF_Resonances_PbPb_exotic.ini
MC/config/PWGLF/ini/GeneratorLF_Resonances_pp.ini
MC/config/PWGLF/ini/GeneratorLF_Resonances_pp_exotic.ini
MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_PbPb.C
MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_PbPb_exotic.C
MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_pp.C
MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_pp_exotic.C
MC/config/PWGLF/pythia8/generator/resonancelistgun_exotic.json
MC/config/PWGLF/pythia8/generator/resonancelistgun_exotic_pbpb.json
MC/config/PWGLF/pythia8/generator/resonancelistgun_pbpb.json

- Update general injection scripts (for pp and Pb-Pb)
- Add exotic resonance injection scripts.

PWGLF: Add exotic resonance injection scripts

---

MC/config/PWGLF/pythia8/generator_pythia8_extraStrangeness.C

Necessary to fix https://its.cern.ch/jira/browse/O2-5402 (at 10% QA)

PWGLF: improve Xi/Om injected spectra

---

UTILS/get_cherrypick_commit_list.sh

Script which helps to determine the complete list
of commits so that a given commit can be
cherry-picked without problems.

utility script to facilitate cherry-picking

---

MC/config/PWGEM/external/generator/GeneratorEMCocktailV2.C

fix the path of the LMee decaytable after introducing a new environment variable in https://github.com/AliceO2Group/O2DPG/pull/1756

MC/PWGEM: O2DPG_ROOT --> O2DPG_MC_CONFIG_ROOT

---

MC/config/PWGLF/ini/GeneratorLF_SyntheFlowXi.ini
MC/config/PWGLF/ini/tests/GeneratorLF_SyntheFlowXi.C
MC/config/PWGLF/pythia8/generator_pythia8_syntheFlow.C
MC/config/PWGLF/pythia8/generator_pythia8_syntheFlowXi.C

@njacazio @ChiaraDeMartin95 @ercolessi - this: 
* moves the access to the v2 vs b and vs pT histograms to a verified-to-be-working address in the CCDB
* adds a synthetic-flow-enabled generator that also injects cascades at the same time to allow for a bona fide closure test for Chiara's analysis

Synthetic flow exercise: add Xi-enriched, flow-enabled generator

---

MC/config/PWGLF/pythia8/generator_pythia8_extraStrangeness.C
MC/config/PWGLF/pythia8/generator_pythia8_syntheFlow.C
MC/config/PWGLF/pythia8/generator_pythia8_syntheFlowXi.C

This fixes a seeding issue in a few generators from LF: see plot from current simulations coming from one of them (the `extraStrangeness` one):
@sawenzel I think these all inherit from `GeneratorPythia8` so the seeding should have been taken care of automatically, should they not? I am not sure why this was not the case...

PWGLF: fix seeding issues

---

MC/run/PWGDQ/runBeautyToJpsi_fwdy_PbPb.sh
MC/run/PWGDQ/runBeautyToJpsi_fwdy_pp.sh
MC/run/PWGDQ/runBeautyToJpsi_midy_pp.sh
MC/run/PWGDQ/runBeautyToPsiAndJpsi_fwdy_pp_triggerGap.sh
MC/run/PWGDQ/runBeautyToPsiAndJpsi_midy_pp_triggerGap.sh
MC/run/PWGDQ/runBeautyToPsi_fwdy_PbPb.sh
MC/run/PWGDQ/runBeautyToPsi_fwdy_pp.sh
MC/run/PWGDQ/runBeautyToPsi_midy_pp.sh
MC/run/PWGDQ/runBplusToJpsi_midy_pp.sh
MC/run/PWGDQ/runBplusToJpsi_midy_pp_triggerGap.sh
MC/run/PWGDQ/runFwdMuBoxGen_PbPb.sh
MC/run/PWGDQ/runFwdMuBoxGen_pp.sh
MC/run/PWGDQ/runPromptCharmonia_fwdy_PbPb.sh
MC/run/PWGDQ/runPromptCharmonia_fwdy_pp.sh
MC/run/PWGDQ/runPromptCharmonia_fwdy_pp_assessment.sh
MC/run/PWGDQ/runPromptCharmonia_fwdy_pp_assessment_triggerGap.sh
MC/run/PWGDQ/runPromptCharmonia_midy_pp.sh
MC/run/PWGDQ/runPromptCharmonia_midy_pp_triggerGap.sh
MC/run/PWGDQ/runPromptJpsi_fwdy_pp_assessment_triggerGap.sh
MC/run/PWGDQ/runPromptJpsi_midy_pp.sh
MC/run/PWGDQ/runPromptPsi2S_fwdy_pp_assessment_triggerGap.sh
MC/run/PWGGAJE/run_jets.sh
MC/run/PWGGAJE/run_jets_embedding.sh
MC/run/PWGHF/analysis_benchmark.sh

Many scripts are failing at the moment while the CI runs (most of them need the -interactionRate flag).

Attempt to fix failing test scripts

---

DATA/production/qc-async/emc.json
DATA/production/qc-async/emc_PbPb.json
MC/config/QC/json/emc-bc-task.json

Fixes https://its.cern.ch/jira/browse/O2-5575?focusedId=6620005&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-6620005

ccdb-run-dependent metadata should be int

---

MC/config/PWGUD/external/generator/GeneratorUpcgen.C
MC/config/PWGUD/ini/makeUpcgenConfig.py
MC/run/PWGUD/runUpcgenANCHOR.sh

Adding scripts which are required to use the event generator upcgen in O2 simulations.

[MC] Scripts needed to run upcgen as external generator

---

DATA/production/qc-async/mch-tracks.json
DATA/production/qc-async/mchmid-tracks.json
DATA/production/qc-async/mftmch-tracks.json
DATA/production/qc-async/mftmchmid-tracks.json

Added several moving window objects to the MCH and global MUON aQC:
* TracksPerTF
* TrackPt
* TrackEta
* TrackPhi
* Minv (mu-mu invariant mass)
For the global MUON tasks, the MW objects are only associated to plots after the track selection cuts.
The QC cycle duration is 300 seconds for all the tasks.

MUON: added MW objects to MCH and MUON tracks tasks

---

DATA/production/configurations/asyncReco/setenv_extra.sh

Goes with https://github.com/AliceO2Group/AliceO2/pull/13762
@shahor02 , @catalinristea

Possibility to apply TF selection in async reco

---

DATA/production/configurations/asyncReco/setenv_extra.sh

@chiarazampolli : as discussed, I also added the label for apass4 of PbPb 2023 let me know if this does require more work.

ITS tracking: update PbPb params for apass1

---

DATA/common/gen_topo_helper_functions.sh
DATA/production/configurations/asyncReco/setenv_extra.sh
DATA/production/qc-async/itstpc.json
DATA/production/qc-sync/glo-itstpc-mtch-qcmn-epn.json
DATA/production/qc-workflow.sh

@shahor02 @f3sch
It was tested in the FST enabling the sec vtx:
```
export PRINT_WORKFLOW=1
export NHBPERTF=32
export SHMSIZE=8000000000
export NJOBS="$JOBS"
export DPL_REPORT_PROCESSING=1
export ARGS_EXTRA_PROCESS_o2_secondary_vertexing_workflow='--disable-cascade-finder --disable-3body-finder --disable-strangeness-tracker'
export WORKFLOW_EXTRA_PROCESSING_STEPS=TPC_DEDX,MFT_RECO,MID_RECO,MCH_RECO,MATCH_MFTMCH,MATCH_MCHMID,MUON_SYNC_RECO,ZDC_RECO,MATCH_SECVTX,MATCH_TPCTOF 
export FST_SYNC_EXTRA_WORKFLOW_PARAMETERS=QC,CALIB_LOCAL_AGGREGATOR,CALIB_LOCAL_INTEGRATED_AGGREGATOR 
export QC_REDIRECT_MERGER_TO_LOCALHOST=1 
export GEN_TOPO_WORKDIR=`pwd` 
export ALICE_O2SIM_DUMPLOG=1 
export NEvents=5 
export NEventsQED=100 
export O2SIMSEED=12345 
export QC_CONFIG_PARAM="--local-batch=QC.root" …
```

Possibility to set the input specs for GLO QC dynamically, for K0s

---

MC/config/PWGUD/external/generator/GeneratorStarlight.C
MC/config/PWGUD/ini/makeStarlightConfig.py

Re-enable DPMJET part. In constructor we need to reset random seed for dpmjet in the config file.

Enable DPMJET

---

DATA/production/qc-async/mch-tracks.json

Add the Clusters task to the async configuration, using parameters similar to those already validated in online.
The task also adds three moving window plots that are updated every 5 minutes.

MCH: add Clusters task in async

---

DATA/production/configurations/asyncReco/setenv_extra.sh
DATA/production/o2dpg_qc_postproc_workflow.py
MC/bin/o2dpg_qc_finalization_workflow.py
MC/bin/o2dpg_sim_workflow.py

QC-1188, QC-1002
Seeing no available run type in the surrounding scripts, I naively assume that absolutely all runs in async and MC are considered to be of type PHYSICS.

Add run type and beam type metadata for async and MC QC

---

MC/config/PWGHF/ini/GeneratorHF_D2H_bbbar_Mode2_OmegaC.ini
MC/config/PWGHF/ini/GeneratorHF_D2H_bbbar_Mode2_XiC0_XiCplus.ini
MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_Mode2_OmegaC.ini
MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_Mode2_XiC0_XiCplus.ini
MC/config/PWGHF/ini/tests/GeneratorHF_D2H_bbbar_Mode2_OmegaC.C
MC/config/PWGHF/ini/tests/GeneratorHF_D2H_bbbar_Mode2_XiC0_XiCplus.C
MC/config/PWGHF/ini/tests/GeneratorHF_D2H_ccbar_Mode2_OmegaC.C
MC/config/PWGHF/ini/tests/GeneratorHF_D2H_ccbar_Mode2_XiC0_XiCplus.C

@fgrosa @fcolamar @mfaggin @creetz16 @pstahlhu @stefanopolitano, this PR adds the `ini` files for the production of generated MC pools for XiC0 + XiC+ and OmegaC0 (separately for charm and beauty)
P.s. I launched the tests for these configurations locally (but they are slow as we know)

[PWGHF] Add configurations for D2H XiC0, XiC+ and OmegaC  MCs (gen only, no gap trigger)

---

MC/config/PWGHF/ini/GeneratorHF_D2H_bbbar_Mode2_OmegaC_to_Omega.ini
MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_Mode2_OmegaC_to_Omega.ini
MC/config/PWGHF/ini/tests/GeneratorHF_D2H_bbbar_Mode2_OmegaC_to_Omega.C
MC/config/PWGHF/ini/tests/GeneratorHF_D2H_ccbar_Mode2_OmegaC_to_Omega.C
MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_Omegac_to_Omega.cfg

Hi @mpuccio @atriolo, this PR adds the configurations to produce a pool of generated events triggered on an OmegaC decaying to Omega + X. Could you please check that it's ok?
@creetz16 @pstahlhu @mfaggin @fcatalan92 @stefanopolitano we should do the same for OmegaC and Xic with forced decays (only `ini` files to be added, for the decay table we can use the usual config file).

[PWGHF] Add configurations for non-prompt Omega MCs (gen only, no gap trigger)

---

MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_and_bbbar_gap5_Mode2_CharmBaryons_pp_ref.ini
MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_Mode2_pp_ref.cfg

Adding two new pythia8 MC files for pp ref run (only changes from original files are beam energy and pythia8 path)

[PWGHF] Configuration for charm-baryon enriched MC anchored to pp ref run

---

MC/bin/o2dpg_sim_workflow.py

This is a bigger development related to https://its.cern.ch/jira/browse/O2-3622
It makes it possible to run embedding workflows with the --pregenCollContext feature. This means that the collision structure of all timeframes are now systematically generated before any event generation or GEANT transport stage.
The O2DPG MC workflows are restructured so that they
* generate the collision structure (collision context) at a very high level
- this contains information about how collisions are composed (background-signal)
- this also fixes the vertex of the collisions
- this fixes the number of background and signal events to be generated
- this is now done for all timeframes at once instead of in isolation (necessary to know how many background events are needed)
* thereafter we generate and …

Significant MC Workflow restructuring

---

DATA/production/configurations/asyncReco/setenv_extra.sh

Change the default behaviour, provided https://github.com/AliceO2Group/AliceO2/pull/13791 is included.
We stop breaking the processing if too much memory is required, we cleanup and move to the next TF.
@shahor02 @chiarazampolli @alcaliva

ITS::tracking: stop fatalising job, drop TF instead

---

DATA/production/qc-workflow.sh

and minor formatting changes (spaces instead of tabs)
this is required to make #1834 work also in online
- downloading the json from apricot to local and adding it to the `JSON_FILES`
- when using local jsons to begin with, they are also added to `JSON_FILES` in the `add_QC_JSON` function
- manipulating the local json taken from `JSON_FILES` and store it in a temporary file
- replace the initial local json with the manipulated temporary file in `JSON_FILES`
**please do not merge yet, should be tested in online first**

dynamically manipulating always the local json file in GLO QC, for K0s

---

MC/bin/o2dpg_sim_workflow.py

This commit introduces the possibility to create event pools under a given TTL. So even, if the event search times out, events already found will be saved to the pool. This feature allows to make best use of a TTL GRID job and there is no danger of overestimating an event count in the script.
The actual number of events found in an event pool job is now also reported in a special 0_0_0_N.stat file, just like in ordinary AO2D productions. This will help for (MonaLisa) accounting.

EventPools: Timeout option and stat file

---

DATA/production/qc-async/mch-tracks.json

The addition of the `ClustersPerDualSampa` plot to the moving windows list will allow to use the [cluster-map display](https://github.com/AliceO2Group/QualityControl/blob/master/Modules/MUON/MCH/src/Clustermap-Display.cxx) tool with data from short time ranges.

MCH: add ClustersPerDualSampa plot to moving windows

---

MC/config/PWGLF/pythia8/generator_pythia8_LF.C

The change introduced in #1431 had the side effect that no signal events were present in recent productions using this generator, as for operator precedence one could never satisfy the condition of the if regulating the generation of signal events.
@njacazio @ddobrigk

Fix injection gap math

---

MC/bin/o2_hybrid_gen.py

More versatile approach for the JSON creation: parameters and default values are taken from parameters structs and ROOT dictionary. Based on suggestion proposed in the https://github.com/AliceO2Group/O2DPG/pull/1863 PR

Improved hybrid template generator

---

MC/bin/o2dpg_sim_workflow.py
MC/bin/o2dpg_workflow_utils.py

This commit provides the possibility to inject external choices for configurable params into the MC workflow construction.
This is done by setting up a JSON file, e.g. local_config.json, an by passing this file to the workflow construction with the new `--overwrite-config local_config.json` command line option.
This new option allows to conveniently set configurable params from the outside (without having to specify the global list of configurations).
The motivation for this development came from the wish to set the busy time for EMC digitization. This is now possible with the following local_config.json:
```
{
"EMCSimParam": {
"mBusyTime": 0
}
}
```
Overall, this development scales to all such external settings and avoids adding specific detector-specific command line options in …

O2DPG-MC: Possibility to pass additional external user settings

---

MC/run/ANCHOR/anchorMC.sh

Improvements to anchoredMC so that we can use
the 2-tag software strategy for MC production.
In other words, we can
* use (latest) O2sim tag for everything related to O2DPG workflow setup, Geant transport and digitization.
* a tagged (more stable) software release for the reconstruction steps. This reconstruction software should be selected through the ALIEN_JDL_O2DPG_ASYNC_RECO_TAG variable.

anchoredMC: Development for 2-tag strategy

---

MC/config/PWGUD/external/generator/DecayTablesEvtGen/OPENCHARM.DEC
MC/config/PWGUD/external/generator/GeneratorStarlight.C
MC/config/PWGUD/external/generator/GeneratorStarlightToEvtGen.C
MC/config/PWGUD/external/generator/Generator_nOOn.C
MC/config/PWGUD/ini/makeStarlightConfig.py
MC/config/PWGUD/trigger/selectParticlesInAcceptance.C
MC/config/PWGUD/trigger/triggerDpmjetParticle.C

Redirecting decays of various DPMJET particles to EvtGen (instead of Geant).
Interface to forward neutron generator. 
Would be good to have this merged in advance, but it is not strictly necessary: https://github.com/alisw/alidist/pull/5732

Tuning of the dpmjet decays and inclusion of neutron generator

---

MC/bin/o2dpg_sim_workflow_anchored.py

Apparently the separator can change each line and be part of the comment message. Hence, simple csv parsing does not work.

Change bad-data-interval parsing to account for more requirements

---

MC/config/PWGGAJE/ini/GeneratorJE_gapgen5_hook.ini

keep parton information for jet-jet MB gap simulation

fix to keep parton information

---

MC/config/PWGGAJE/external/generator/generator_pythia8_powheg.C
MC/config/PWGGAJE/external/powheg/powheg_beauty_F05.input
MC/config/PWGGAJE/external/powheg/powheg_beauty_F05_R05.input
MC/config/PWGGAJE/external/powheg/powheg_beauty_F2.input
MC/config/PWGGAJE/external/powheg/powheg_beauty_F2_R2.input
MC/config/PWGGAJE/external/powheg/powheg_beauty_MHigh.input
MC/config/PWGGAJE/external/powheg/powheg_beauty_MLow.input
MC/config/PWGGAJE/external/powheg/powheg_beauty_R05.input
MC/config/PWGGAJE/external/powheg/powheg_beauty_R2.input
MC/config/PWGGAJE/external/powheg/powheg_beauty_default.input
MC/config/PWGGAJE/external/powheg/powheg_charm_F05.input
MC/config/PWGGAJE/external/powheg/powheg_charm_F05_R05.input
MC/config/PWGGAJE/external/powheg/powheg_charm_F2.input
MC/config/PWGGAJE/external/powheg/powheg_charm_F2_R2.input
MC/config/PWGGAJE/external/powheg/powheg_charm_MHigh.input
MC/config/PWGGAJE/external/powheg/powheg_charm_MLow.input
MC/config/PWGGAJE/external/powheg/powheg_charm_R05.input
MC/config/PWGGAJE/external/powheg/powheg_charm_R2.input
MC/config/PWGGAJE/external/powheg/powheg_charm_default.input
MC/config/PWGGAJE/ini/GeneratorPythia8POWHEG.ini
MC/config/PWGGAJE/ini/tests/GeneratorPythia8POWHEG.C
MC/config/PWGGAJE/pythia8/generator/pythia8_powheg.cfg

The generator has been tested using both o2-sim and the normal workflow system. 
Nothing to report with normal o2-sim, however for the workflow system I noticed that it's not possible 
to configure properly the parameters in the funcName => There might be a small bug that doesn't allow \" to be used or that discards it. With the workflow framework both the configuration via iniFile and hybrid JSON worked flawlessly.

External Pythia8+Powheg generator

---

MC/bin/o2dpg_sim_workflow_anchored.py

1) Greater flexibility to set the timeframe length in orbits.
The `--orbitsPerTF` options now,
* either takes a precise integer number
* or a comma-separated string of triples f:t:o which denote to use `o` orbits when the interaction rate falls between `f` (inclusive) and `t` (exclusive)
example: `--orbitsPerTF 0:10000:32,10001:10000000:8` will apply 32 orbit-sizes timeframes when the interaction rate is below 10kHz, otherwise 8 orbits.
This improvement caused a larger refactoring of the code, because we now
need to query the interaction rate twice.
2) Improvements in the bad-data exlusion treatment:
* We now report the global fraction of run-space excluded by the list
* We now determine each line, wether the treatment is in orbits or in timestamps

Two improvements for the MC anchoring service

---

MC/bin/o2dpg_sim_workflow.py

Waiting for https://github.com/AliceO2Group/AliceO2/pull/13853
This is to enable FT0 recpoints reading in MC for TPC Time series
@miranov25 @ercolessi

reading FT0 recpoints for TPCtimeseries

---

MC/config/PWGGAJE/external/generator/generator_pythia8_powheg.C

Various improvements and fix for number of events using the dpl-eventgen executable. Linked to https://github.com/AliceO2Group/AliceO2/pull/13936

Fix for dpl-eventgen usage, added nEvents protection and executable selection

---

MC/config/PWGDQ/external/generator/GeneratorParamMuon.C

Port of the generator used in Run 2 for MC tuning and efficiency studies in the muon spectrometer
Original: https://github.com/alisw/AliDPG/blob/master/MC/CustomGenerators/PWGDQ/Muon_GenParamSingle_PbPb5TeV_1.C

Add parameterized single muon generator

---

MC/bin/o2dpg_sim_config.py
MC/bin/o2dpg_sim_workflow.py
MC/run/ANCHOR/anchorMC.sh

a) make workflow construction more independent from actual
O2 commit: Allow to detect if options are present in DPL executables
and react accordingly. This can allow to write more resilit workflow construction
code.
b) Improvements to swap in and out software environments in the anchoring script

Developments for 2-tag software processing

---

MC/bin/o2dpg_sim_workflow.py

This goes together with https://github.com/AliceO2Group/AliceO2/pull/13955 and ensures a more consistent primary vertex location during the event generator phases in O2DPG MC.
Fixes a bug where the primary vertex was applied twice.

Improvements in generator vertexing

---

UTILS/Parsers/workflowToJSON.sh

First of the series script to be ported from the TPC gitlab to the DPG script:
* duPython.py        duQuery.sh        monalisaQuery.py    monalisaQuery.sh    workflowToJSON.sh
Described in detail in the
https://indico.cern.ch/event/1423563/contributions/5987247/attachments/2868815/5022209/ATO-648%20-synchronization%20AliEn%20%E2%86%92%20GSI%20and%20ALICE%20monalisa%20queries.pdf
- • Purpose: Convert workflow configuration logs into structured JSON format for enhanced data analysis and readability.
- • Components:
- **Initialization:** Sets up the environment for script execution.
- **• Parsing:** Transforms verbose workflow logs into a JSON format.
- **• Comparison**: Compares JSON files to identify differences.
- **• Usage:** Interactive Analysis: Facilitates easier data manipulation and …

ATO-648 - workflowToJSON.sh -  porting the code from the TPC gitlab to the O2DPG tools

---

DATA/production/qc-async/mid.json

This PR allows for a better comparison between data and MC.
The masks are applied during reconstruction for both data and MC. But data are already masked since this is done at the electronics level, while MC is masked only during reconstruction.
So far the QC checked for digits **before** the masks are applied, which leads to a difference between data and MC.
This PR introduces a check on digits **after** the masks are applied, so that we can compare apples to apples.

MID: check the filtered digits in the async QC

---

UTILS/checkCorruptedAO2Ds.C
UTILS/findCorruptedAO2Ds.sh

- Added check for "repair" messages in the `checkCorruptedAO2Ds.C` macro to also catch files, where some problem appears and root tries to repair on the fly. This addition is made based on the recent report by Nicolas on the JIRA ticket O2-5725 that we see still some AO2D files with problems that can not be catched with the old version of `checkCorruptedAO2Ds.C`.
- Modified `findCorruptedAO2Ds.sh` to correctly read those cases and identify them as "broken" aswell.

[O2DPG,UTILS,O2-5725] Expand macros to find corrupted AO2Ds

---

MC/bin/o2dpg_sim_workflow.py

TPC digitization currently crashes when multiple workers try to load FEEConfig via TPC/Config/RunInfoV2.
Recently the TPC code was changed to use this redirecting object. The hypothesis is that there is a problem in the CcdbApi when using CCDB redirects which is bypassing semaphore syncronization of CCDB loads. This leads to race conditions and corrupted CCDB snapshots.
This commit reduces such a race condition by pre-downloading TPC/Config/RunInfoV2 before launching multi-process TPC digitization procedures.
We can take the change back once a proper fix is available in O2-CCDB.

Workaround crash in TPC digitization

---

MC/bin/o2_dpg_workflow_runner.py
MC/bin/o2dpg_sim_config.py
MC/bin/o2dpg_sim_workflow.py
MC/bin/o2dpg_sim_workflow_anchored.py
MC/bin/o2dpg_workflow_utils.py
MC/run/ANCHOR/anchorMC.sh

With this commit, we achieve support for 2tag operation in anchoredMC.

Support for 2tag anchoredMC

---

MC/run/ANCHOR/anchorMC.sh
MC/run/ANCHOR/tests/test_anchor_2023_apass2_pp.sh

@sawenzel @mconcas @alcaliva 
I opened a new PR on the addition of the parallel world feature to the steering scripts.
As suggested in the previous thread by Sandro, I removed the overriding `confKey` setting in the `anchorMC.sh` script. As an example, the activation of the parallel world feature is shown in the pp test script.
I still include the changes in `anchorMC.sh` that toggle the usage of the ideal geometry for ITS in anchored simulations. First, we avoid fetching the ideal alignment object for ITS from the ccdb in case we require the parallel world. Additionally, if the parallel world is requested, the ITS geometry snapshot is not added to the local ccdb cache, while this is always done for MFT.

set pw in test script + toggle ideal ITS in anchored simulation

---

DATA/common/setenv.sh
DATA/production/configurations/asyncReco/setenv_extra.sh

This reverts commit bafcb11a1dd5cedc579c9c03935ec2e7138aa4af partially.

Move some part back to setenv.sh

---

MC/config/ALICE3/ini/tests/xi_PbPb.C
MC/config/ALICE3/ini/tests/xi_pp.C
MC/config/ALICE3/ini/xi_PbPb.ini
MC/config/ALICE3/ini/xi_pp.ini

Add xi injector for pp and PbPb for the on-the-fly studies on hyperloop

[ALICE3] Add xi injector for pp and PbPb

---

DATA/production/calib/mid-badchannels.sh

With the PR https://github.com/AliceO2Group/O2DPG/pull/1914 , the MID calibration run was changed in order to use QC files from apricot. However, this led to a bug since the path to consul had to be changed as well.
This PR should solve the issue, allowing to launch calibration runs at P2.

Fix path to file in consul

---

GRID/utils/getReproducerScript.sh
GRID/utils/grid_submit.sh
MC/run/ANCHOR/anchorMC.sh

* cleanup, fixes and adjustments in grid_submit
* a new script getReproducerScript.sh, which downloads a GRID reproducer script and modifies it to ensure automatic execution in apptainer:
- the script needs a ALIEN_PROC_ID
- creates a script reproducer_script_${ALIEN_PROC_ID}.sh which executes the job of ALIEN_PROC_ID within an apptainer environment (just as on the GRID)
* anchorMC now creates a reproducer script automatically

Several tooling improvements

---

DATA/production/workflow-multiplicities.sh

Two new environment variables are introduced to provide the fraction of rejected MCH events separately for the cases where ITS is either included (CUT_RANDOM_FRACTION_MCH_WITH_ITS) or excluded (CUT_RANDOM_FRACTION_MCH_NO_ITS) from the data taking.
The CUT_RANDOM_FRACTION_MCH variable, as well as the two new ones, can still be overridden by setting them explicitly in the shell environment, therefore the changes are backward compatible.
JIRA ticket: https://its.cern.ch/jira/browse/MCH-18

MCH: add cut random fraction setting for the cases with and without ITS

---

MC/config/analysis_testing/json/analyses_config.json
MC/config/analysis_testing/json/dpl/o2-analysis-time-dependent-qa.json

o2-analysis-time-dependent-qa to the suite of AnalysisQC tasks
Regards, Catalin.

Add o2-analysis-time-dependent-qa to the suite of AnalysisQC tasks

---

MC/bin/o2dpg_qc_finalization_workflow.py
MC/bin/o2dpg_sim_workflow.py

QC tasks are now only executed at runtime
*if* the mentioned qc-config file is actually found.
This prevents crashes/errors that we have seen when this was not the case. In practice the situation may arise if the workflow is constructed with a different O2DPG tag than the executing software environment (2-tag mechanism for MC).

MC-QC stability fix

---

MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_and_bbbar_gap5_Mode2_corrBkg.ini
MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_CorrBkg.cfg

This PR adds the configuration and the .ini file to relative to the correlated bkg production in pp

[PWGHF] Add config for correlated bkg production in pp

---

MC/config/PWGLF/ini/GeneratorLFHyperNucleiPbPbGapWithFlow.ini
MC/config/PWGLF/pythia8/generator_pythia8_longlived_gaptriggered.C

@lbariogl this adds a `bool` to the standard LF gap-triggered pythia generator such that flow can be added if desired (default: off). Tested to work just fine; also added a corresponding `ini` file following the nuclei prescription. Let me know if there's something that needs adjusting :-) 
N.B.: all particles will have v2 vs pT set to that of inclusive charged particles. Thus, for nuclei, the objective of a MC generated with flow will be to find out the modulation of the efficiency instead (and not directly the fractional change of the v2 reco vs v2 generated).

Add switch for synthetic flow in standard gap triggered LF generator

---

UTILS/Parsers/READMEtreeFastCache.md
UTILS/Parsers/treeFastCache.C
UTILS/Parsers/treeFastCacheND.C
UTILS/Parsers/workflowToJSON.sh

This PR introduces the `makeDiffWorkflow` shell function, designed to streamline comparison of two `workflowconfig.log` files — whether local or from Alien.
- Compares two JSON workflow configs line-by-line using `diff`
- Accepts both local and `alien://` paths
- Automatically parses logs using `makeParse`
- Supports filtering by command (default: `gpu`)
- Supports unified diff or side-by-side diff (default: side-by-side)
- Output is piped to `less -R` with color for readability
---
If no arguments are provided:
```bash
makeDiffWorkflow
```
Output:
```
makeDiffWorkflow: Compare two O2 workflowconfig logs (local or Alien).
Usage:
makeDiffWorkflow <file0> <file1> <diffType> <filter>
...
```
---
```bash
makeDiffWorkflow alien:///alice/data/2023/LHC23zzk/544515/apass5/1140/o2_ctf_run00544515_o …
```

Adding makeDiffWorkflow using path to local or alien workflow.config + treeFastCache.C+treeFastCacheND.C 

---

DATA/production/configurations/asyncReco/setenv_extra.sh

to set GPU_rec_tpc.mergerInterpolateRejectAlsoOnCurrentPosition and GPU_rec_tpc.clustersEdgeFixDistance parameters from the JDL (if needed). Defaults are eqiuvalent to: GPU_rec_tpc.mergerInterpolateRejectAlsoOnCurrentPosition=1;GPU_rec_tpc.clustersEdgeFixDistance=0

Add options ALIEN_JDL_TPCCHICUTOPT and ALIEN_JDL_TPCCLUSEDGEREDEF

---

MC/config/ALICE3/ini/tests/xicc_background_PbPb.C
MC/config/ALICE3/ini/xicc_background_PbPb.ini
MC/config/ALICE3/pythia8/generator_pythia8_strangeness_gun_PbPb.C

Hi! With this PR I would like to add a generator that better reproduces the Xi yields in PbPb. Specifically with the purpose for estimating the background in the ALICE 3 multi-charm studies, since a significant portion of the background comes from primary Xi

[ALICE 3] Add generator and ini files for PbPb 5.52 TeV with more abundant Xi

---

MC/config/common/pythia8/utils/mkpy8cfg.py

- Beams with different energies need to be treated accordinly (frameType = 2). 
- PbPb heavy ion settings limited to PbPb 5.52 TeV --> in other configurations Angantyr will fit the values automatically
These modifications make mkpy8cfg.py ready to generate various collision systems configurations for Pythia8.

Frametype fix for asymmetric beams

---

MC/config/PWGHF/external/generator/generator_pythia8_hfhadron_to_nuclei.C
MC/config/PWGLF/ini/GeneratorLF_Coalescence.ini
MC/config/PWGLF/pythia8/generator_pythia8_coalescence.C
MC/config/common/external/generator/CoalescencePythia8.h

This PR adds:
- Common header file with simple coalescence implementation (`CoalescencePythia8.h`) (@sawenzel , @jackal1-66 thank you for your suggestions!)
- Adapt existing nuclex code (@mpuccio)
- Add HF to nuclei generator (@fgrosa)

Add common coalescence utility + HF -> nuclei generator

---

MC/run/examples/O2DPG_pp_minbias.sh

Added the seed number to avoid the precollcontext crash. Otherwise a crash on precollcontext:  
`Running: TIME="#walltime %e\n#systime %S\n#usertime %U\n#maxmem %M\n#CPU %P" /usr/bin/time --output=precollcontext.log_time ./precollcontext.log_tmp.sh
the argument ('None') for option '--seed' is invalid`
Please have a look to see if this is ok.

Add seed number for MC test script

---

DATA/production/configurations/asyncReco/setenv_extra.sh

As it prevents passing extra options, like the limit on the N TFs to process

Do not unset ARGS_EXTRA_PROCESS_o2_ctf_reader_workflow

---

DATA/production/qc-async/mftmchmid-tracks.json

The GLO-MUONTracksMFT QC task has been reported to use 100% CPU in some async reconstructions, thus reducing the overall CPU efficiency of the production.
The input data for this task is now sampled to 10%. A similar sampling is also introduced, but not enabled by default, for the GLO-MUONTracks task.
See https://its.cern.ch/jira/browse/O2-5931 for further details.

MUON: added dataSampling policies for muon tracks in async QC configuration

---

MC/bin/o2dpg_workflow_utils.py
MC/run/ANCHOR/anchorMC.sh

* config transfer needs to happen in new environment
* ability to specify from_stage for async tag env

Fixes for 2tag

---

MC/config/PWGHF/ini/GeneratorHFTrigger_LambdaBToNuclei.ini
MC/config/PWGHF/ini/tests/GeneratorHFTrigger_LambdaBToNuclei.C
MC/config/PWGHF/pythia8/generator/pythia8_lambdab_with_decays_Mode2.cfg

Add generator for LambdaB --> nuclei

---

MC/config/PWGHF/external/generator/generator_pythia8_gaptriggered_hf.C
MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_and_bbbar_gap5_DResoTrigger.ini
MC/config/PWGHF/ini/tests/GeneratorHF_D2H_ccbar_and_bbbar_gap5_DResoTrigger.C
MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_DResoTrigger.cfg

This PR adds the possibility to replace particles in the PYTHIA stack with a given frequency. Custom particles, not present in PYTHIA, are also allowed (specifically for the moment Ds1* and Ds3* states and Xic resonances).
It also adds a config for the MC production needed for the analyses of Ds and Xic excited states with 2024 pp triggered data (Ds1+, Ds2*+ and excited Xic states)
Please @Luca610 check the forced decays, in case we want to add something.

[PWGHF] Add possibility to replace particles in the stack for HF generator

---

MC/bin/o2dpg_qc_finalization_workflow.py
MC/bin/o2dpg_sim_workflow.py

This fix is meant to cure the bug in the nightlies reported in https://its.cern.ch/jira/browse/O2-5885
The aQC MCH+MFT task is enabled only if the MID is not active in the run

Fix for the MC aQC MCH+MFT task to avoid MID active cases

---

MC/bin/o2dpg_sim_workflow.py
MC/config/common/external/generator/QEDepem.C

Generated dictionary with all available collision systems and added special runs

Include special runs in wf creator

---

MC/config/PWGEM/ini/Pythia8_Beauty_Cocktail_pp13.ini
MC/config/PWGEM/ini/Pythia8_Beauty_Cocktail_pp502.ini
MC/config/PWGEM/ini/Pythia8_Beauty_Cocktail_pp536.ini
MC/config/PWGEM/ini/Pythia8_Charm_Cocktail_pp502.ini
MC/config/PWGEM/ini/Pythia8_Charm_Cocktail_pp536.ini
MC/config/PWGEM/pythia8/decayer/force_semileptonic.cfg
MC/config/PWGEM/pythia8/generator/pythia8_hf_cocktail_pp502.cfg
MC/config/PWGEM/pythia8/generator/pythia8_hf_cocktail_pp536.cfg

Force as well the decay of open-beauty hadron mesons for the beauty cocktail. Add different energies.

Forced decays + other energies

---

MC/config/PWGHF/external/generator/generator_pythia8_gaptriggered_hf.C

This PR fixes the history in case of particle replacement.
In particular, the indices of the mothers of the replaced particles are not updated correctly after `remove` and it is necessary in case of `includePartonEvent=false` (while not important if we keep the parton event, since the new particle -> mothers indices are always OK).

Fix mother -> daughter indices in case of replacement in HF gerator

---

DATA/common/setenv_calib.sh
DATA/production/configurations/asyncReco/setenv_extra.sh

The track types for which residuals are extracted can be steered with TPC_RESIDUAL_TRK_SOURCES_MAP_EXTRACTION env.var, default is ITS-TPC (as before).

Allow CALIB_TPC_SCDCALIB in runs w/o TRD or TOF

---

MC/config/examples/epos4/generator_EPOS4.C
MC/config/examples/ini/GeneratorEPOS4.ini
MC/config/examples/ini/GeneratorEPOS4HQ.ini

Each instance of GeneratorEPOS4 will now have a different seed, based on the call order to the gRandom function, and the options files will be separated for each instance. This should fix some issues when calling the generator in parallel or simply in sequence.

Improved seed and option files handling

---

MC/bin/o2dpg_sim_workflow.py

Hadronic cross section was not forwarded to QED step, showing default 8 b value in qedgenparam.ini. Now value is set from xSecSys defined in the workflow creator. This didn't affect data because QED ratio was correctly calculated without using the external parameter.

Forward xSectionHad to qedgenparam.ini

---

MC/bin/o2dpg_sim_workflow.py

Improvement for configuration: Apply the key-values from the generic config on top of the anchorConfig, if the anchorConfig does not have these keys themselves. Useful for key-values in the digitization space for instance since they are not mentioned in async reco workflows.
In addition, actually apply FT0DigParam and FV0DigParam to the digitization of FIT. This didn't have any effect so far.

Apply keys from generic config if applicable

---

MC/bin/o2dpg_sim_workflow.py
MC/bin/o2dpg_sim_workflow_anchored.py
MC/prodinfo/README.md
MC/prodinfo/mcprodinfo_ccdb_upload.py
MC/run/ANCHOR/anchorMC.sh

This commit provides code that publishes
MonteCarlo MetaData "MCProdInfo" describing a production.
The information is stored into CCDB, into folders
specific to the executing user as well as the LPM production tag.
We now also write the username into AO2D.root, so that clients can retrieve the username next to the LPM production tag.
By default upload of MCProdInfo is attempted for the first few JobIDs within a production. This is decided based on the split-id.

Publish MCProdInfo

---

DATA/tools/epn/gen_topo.sh
DATA/tools/epn/gen_topo_logged.sh
DATA/tools/epn/gen_topo_o2dpg.sh

in case of topology generation error, this does the following:
1) in InfoLogger GUI, it prints the last message from the gen_topo scripts stderr first, directly after the "Topology generation script failed" message from ODC, as a fatal so it is displayed as level 1 and, afterwards, the full stderr message stream will be printed as it is now.
2) the error string in AliECS GUI contains the first one or two lines of the gen_topo scripts stderr output. With this, the last line of the gen_topo stderr output will be printed first also in the AliECS GUI error string.
The scripts contain a few foreseen error sources for which we print a corresponding error message. Especially for these cases, this should help the shifter to distinguish between different topology failure reasons.
Two examples of …

gen_topo scripts: on error, print the last stderr message first

---

MC/run/ANCHOR/anchorMC.sh

It should be enough, and less confusing, to just specify the number of timeframes to be simulated (as well as potentially the timeframe length in orbits).
So we now do the setting for NSIGEVENTS internally (the o2dpg_sim_workflow script still needs it) but keep the option to provide it for expert studies.
Also taking away the need to provide CYCLE (which is mostly 0 in any case).

anchorMC: Take away need to specify NSIGEVENTS

---

MC/config/examples/epos4/generator_EPOS4.C

Previous method was wrong and would cause indexing issues when analysing the events. 
Now the two unidentified charmonia states will simply not be transported, instead of removing them from the particles list.

Skip Chi0c and Chi1c transport by default for EPOS4

---

MC/bin/o2dpg_sim_workflow.py

Changed number of QED events based on https://its.cern.ch/jira/browse/O2-5861

Adaptable QED events based on INTRATE

---

MC/bin/o2dpg_sim_workflow.py
MC/run/ANCHOR/anchorMC.sh

1) The TPC residuals extraction/aggregation is triggered by `ALIEN_JDL_DOTPCRESIDUALEXTRACTION=1` env.var, as in the standard cpass. The only difference wrt cpass processing is that the calibration slot duration for the `o2-tpc-scdcalib-interpolation-workflow` is set to 1s (`--sec-per-slot 1 `) to maximise the yield of tracks with residuals (virtually all tracks will be used).
In opposite, the `o2-calibration-residual-aggregator` uses `--sec-per-slot` as in the original anchored workflow.
The output is `o2tpc_residuals_<tsmin>_<tsmax>_<tfmin>_<tfmax>.root` files.
2) if `ALIEN_JDL_REMAPPINGS` is defined, it will be applied as `--condition-remap $ALIEN_JDL_REMAPPINGS` added to all workflows supporting this option.

Allow TPC residual extraction in MC and data corr maps in the reco

---

MC/run/ANCHOR/tests/test_looper.sh

improve 2tag testing output

---

MC/bin/o2dpg_sim_workflow_anchored.py
MC/prodinfo/mcprodinfo_ccdb_upload.py
MC/prodinfo/mcprodinfo_harvester.py

A tool which can extract MCProdInfo from logs on the GRID. Can be used to push MCProdInfo info retroactively to the CCDB.
Slight extension of MCProdInfo to contain software tags used.

Improvements for MCProdInfo; MCProdInfo harvester tool

---

DATA/production/configurations/asyncReco/async_pass.sh
DATA/production/configurations/asyncReco/setenv_extra.sh
DATA/production/workflow-multiplicities.sh

First version, still needs testing

Simplify multiplicity settings in async reco scripts  - DO NOT MERGE

---

DATA/production/workflow-multiplicities.sh

needs https://github.com/AliceO2Group/AliceO2/pull/14625 to be effective

workflow-multiplicities.sh: use two mch-data-decoder instances by default in synchronous pp and PbPb processing

---

DATA/production/configurations/asyncReco/setenv_extra.sh

If ITS is running on GPU as part of an asynchronous pass we need to give the gpu-reco-wfx all options from its-reco-wfx. Instead of setting these individually, I think it is better to just summarily set all options.

Set ITS options on gpu workflow if included

---

MC/bin/o2dpg_sim_workflow.py
MC/run/ANCHOR/anchorMC.sh

So far, we are creating geometry files as step of the anchorMC script. However, it is better to do this as part of the actual MC workflow in order to benefit from the features of the workflow runner (checkpointing, etc).

anchorMC: Integrate aligned geometry download into O2DPG workflow

---

MC/bin/o2dpg_sim_workflow.py

While studying file-access graphs in O2DPG MC, I noticed that trdtracklets.root get written twice: Once from the digitizer workflow and once from the TRD-DIGI-QC task. This can corrupt the processing and is probably a bug. QC should only read digits/trdtracklets.
The reason appears to be the use of `o2-trd-trap-sim` as the reader command for digits and tracklets.
For now, the problem can probably be avoided by using `o2-trd-trap-sim --disable-root-output true`.
However, this might still create new trdtracklets in memory which should not be needed as they have been previously created during digitization.
So it would be good to just use a true `o2-trd-sim-artefacts-reader` workflow or similar in the future.

TRD QC: Do not write tracklets

---

MC/bin/o2dpg_sim_workflow.py

Built the pvfinder needs only for active detectors.
I noticed that when just having 'ITS TPC...' and other relevant barrel detectors as readout.
The pvfinder still depended on MFT/MCH/MID.
I extended thus the already present functionality to all inputs.

MC: pvfinder need reco input only if det active
